docs/01-getting-started.md, docs/02-deployment-guide.md, scripts/deploy/buildAndDeploy.sh, scripts/deploy/deploy.sh, scripts/deploy/pre-deployment.sh, scripts/deploy/removeUploads.sh, scripts/deploy/tearDown.sh, scripts/deploy/uploadDockerImages.sh, scripts/deploy/uploadJars.sh, scripts/test/buildDeployTest.sh
First run through of code and small documentation tweaks.
* Small fixes (`/usr/bin/env`, avoid use of `sed -i` where possible or give temp file extension and document versions of tools required) to run on MacOS
* Fix broken link to 02-deployment-guide
* Add note on bash version (MacOS comes with v3 and `declare -A` needs v4
* Add note on `cdk bootstrap`.  Although instructions are in 02-deployment-guide, I hadn't read that yet
* Add note on needed S3 VPC - stopped `cdk deploy` from working on my first attempt.
* Fix typo
=> First run through of documentation to deploy

scripts/deploy/removeUploads.sh, scripts/deploy/uploadDockerImages.sh
Removing `declare -A` which requires bash v4 or later, as per #36.
Instead this potential solution uses an "array" (a shared common prefix on a number of variables).  e.g.
```bash
Stacks_CompactionStack="compaction-job-execution"
Stacks_IngestStack="ingest"
Stacks_SystemTestStack="system-test"
Stacks_EksBulkImportStack="bulk-import-runner"
```
Tested on MacOS with GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21).
=> Remove declare -A from bash scripts

scripts/deploy/pre-deployment.sh, scripts/dev/updateVersionNumber.sh
Apologies, the whitespace in the sed command `-i ""` broke the pre-deploy.sh script.  The pull request fixes that issue.
```
JAR_DIR:/home/ec2-user/environment/sleeper/scripts/jars
VERSION:0.11.1-SNAPSHOT
Generating properties
sed: can't read : No such file or directory
```
=> whitespace breaks sed command

NOTICES, java/bulk-import/bulk-import-common/pom.xml, java/bulk-import/bulk-import-common/src/test/java/sleeper/bulkimport/job/BulkImportJobSerDeTest.java, java/bulk-import/bulk-import-starter/pom.xml, java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/StateMachineExecutorTest.java, java/pom.xml
**Note that this PR is stacked on top of #120, please merge that one first**
JsonUnit is a library for AssertJ-style assertions on JSON. It parses the JSON, does detailed comparison, and outputs a diff when assertions fail. It lets you use whitespace in exact comparisons even if the actual value doesn't have whitespace.
This adds this as a dependency and migrates existing assertions on JSON to use the library.
=> Issue 107 - Use JsonUnit for AssertJ-style JSON assertions

code-style/checkstyle.xml, java/athena/src/test/java/sleeper/athena/metadata/IteratorApplyingMetadataHandlerIT.java, java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/ExecutorFactoryIT.java, java/clients/src/test/java/sleeper/status/update/ReinitialiseTableIT.java, java/tables/src/test/java/sleeper/table/job/TableInitialiserIT.java
Blocks usage of `org.junit.Assert` in tests in the checkstyle
Resolves #153
=> Issue 153 - Enforce AssertJ usage in tests

java/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobRun.java, java/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStatus.java, java/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusInPeriodTest.java, java/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusTaskIdAssignedTest.java, java/compaction-status-store/src/main/java/sleeper/compaction/status/job/DynamoDBCompactionJobStatusStore.java, java/compaction-status-store/src/test/java/sleeper/compaction/status/job/QueryCompactionJobStatusByTaskIdIT.java, java/compaction-status-store/src/test/java/sleeper/compaction/status/job/QueryCompactionJobStatusUnfinishedIT.java
The issue with unfinished jobs was resolved by the reporting PR, since we also wanted to report the status of the job correctly: #265
Resolves #264
=> Issue 264 - Fix compaction job queries with multiple runs

java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBAttributesTest.java
=> Issue 326 - Use Instant.parse() in tests to avoid issues with later java versions

java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesEmptyOutputTest.java, java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIteratorTest.java, java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesReportingTest.java, java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesSplittingTest.java, java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesTest.java, java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/testutils/CompactSortedFilesTestUtils.java, java/ingest/ingest-core/src/main/java/sleeper/ingest/IngestResult.java, java/ingest/ingest-core/src/test/java/sleeper/ingest/IngestResultTestData.java, java/ingest/ingest-core/src/test/java/sleeper/ingest/job/FixedIngestJobHandler.java, java/ingest/ingest-core/src/test/java/sleeper/ingest/task/IngestTaskStatusTestData.java, java/ingest/ingest-core/src/test/java/sleeper/ingest/task/IngestTaskTest.java, java/ingest/ingest-runner/src/main/java/sleeper/ingest/IngestRecords.java, java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/IngestCoordinator.java, java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/IngesterIntoPartitions.java, java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/RetryStateStoreException.java, java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowRecordBatchAcceptingRecords.java, java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobQueueConsumer.java, java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobRunner.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsFromIteratorIT.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsFromIteratorTest.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsIT.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsResultTest.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsTest.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestResultTest.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestRecordsTestDataHelper.java, java/statestore/src/test/java/sleeper/statestore/FileInfoTestData.java, java/statestore/src/test/java/sleeper/statestore/inmemory/FixedPartitionStore.java, java/statestore/src/test/java/sleeper/statestore/inmemory/FixedPartitionStoreTest.java, java/statestore/src/test/java/sleeper/statestore/inmemory/StateStoreTestHelper.java
Resolves #431 
Also stopped IngestCoordinator clearing thread interrupted state incorrectly.
Simplified FixedPartitionStore a bit, and standardised test code for setting it up.
=> Issue 431 - Report records read during ingest

java/pom.xml
Resolves #585
The maven-shade-plugin was generating a dependency-reduced pom which only had the dependencies that are not included in the fat jar. We have configuration to only attach the fat jar rather than replace it in the main Maven artifact, but it was still replacing the pom. That's disabled now.
=> Issue 585 - Declare dependencies in built Maven artifacts

java/system-test/src/main/java/sleeper/systemtest/ingest/WaitForGenerateData.java, scripts/test/compactionPerformance/system-test-instance.properties
=> Issue 555 - Limit task ID count to 100 for each DescribeTaskRequest

java/athena/src/main/java/sleeper/athena/record/SleeperRecordHandler.java, java/clients/src/main/java/sleeper/clients/QueryClient.java, java/parquet/src/main/java/sleeper/utils/HadoopConfigurationProvider.java, java/query/src/main/java/sleeper/query/executor/QueryExecutor.java, java/query/src/main/java/sleeper/query/lambda/SqsQueryProcessor.java
Resolves https://github.com/gchq/sleeper/issues/668
Note: there is a need for a unit test for HadoopConfigurationProvider - this is covered in https://github.com/gchq/sleeper/issues/673
=> S3A readahead property now set on query lambdas

java/bulk-import/bulk-import-starter/pom.xml, java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/ExecutorIT.java
Resolves #745.
We decided not to start the bulk import job in the executor (the Lambda that takes jobs off the queue and submits them to Spark). This will be picked up in https://github.com/gchq/sleeper/issues/746 instead.
We refactored the tests a little while we were looking through it.
=> Issue 745 - Refactor tests for how bulk import jobs are started

java/system-test/src/main/java/sleeper/systemtest/ingest/WaitForGenerateData.java
=> Issue 784 - Fix WaitForGenerateData excluding one task from checks

docs/05-ingest.md, docs/08-python-api.md, example/full/instance.properties, example/full/table.properties, java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java, scripts/templates/instanceproperties.template
=> Issue 949 - Update default EMR x86 instance types to m6i equivalents

java/system-test/src/main/java/sleeper/systemtest/cdk/TearDownTestInstance.java
=> Issue 977 - Don't wait for system test cluster when configuration is deleted

.github/workflows/docker-cli-main.yaml
PR"
- Resolves https://github.com/gchq/sleeper/issues/995
- It's only a workflow change, and that's been tested on a fork: https://github.com/patchwork01/sleeper/actions/runs/5530872428
=> Issue 995 - Only push images to base repository

scripts/cli/environment/scripts/subcommands/deploy.sh
PR"
- Resolves https://github.com/gchq/sleeper/issues/1028
=> Issue 1028 - Use CDK parameters when only one is given

scripts/cli/environment/scripts/subcommands/destroy.sh
PR"
- Resolves https://github.com/gchq/sleeper/issues/1040
- Same as change in https://github.com/gchq/sleeper/pull/1029
=> Issue 1040 - Use CDK parameters when only one is given for destroy

java/clients/src/main/java/sleeper/clients/status/update/ReinitialiseTable.java, java/clients/src/main/java/sleeper/clients/status/update/ReinitialiseTableFromExportedPartitions.java, java/clients/src/main/java/sleeper/clients/status/update/ReinitialiseTableFromSplitPoints.java
#1033 Issue
PR"
- Resolves https://github.com/gchq/sleeper/issues/1033
- Doesn't need testing (it is for logging that was previously implemented)
=> Issue 1033 - Use logger in ReinitialiseTable instead of System.out

.vscode/README.md, .vscode/settings.json
PR"
- Resolves https://github.com/gchq/sleeper/issues/1082
- No tests needs just an update to settings.json and the README
- .vscode/README.md updated
=> Issue 1082 - vscode settings file causes issues if not using Corretto or if Java 11 is not installed

java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperties.java, java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperty.java, java/system-test/system-test-configuration/src/test/java/sleeper/systemtest/configuration/SystemTestPropertyTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1113
- SystemTestPropertyTest
=> Issue 1113 - Stop preventing duplicate property descriptions

java/ingest/ingest-batcher-job-creator/src/test/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambdaIT.java, java/ingest/ingest-batcher-store/src/main/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStore.java, java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreIT.java, java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreTestBase.java
Reverts gchq/sleeper#1121
These changes complicate the system and didn't work because DynamoDB's local version doesn't support consistent reads:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html
=> Revert "Issue 929 - Force consistent reads in IngestBatcher integration tests"

java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceFleets.java, java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java, java/configuration/src/main/java/sleeper/configuration/Utils.java, java/configuration/src/main/java/sleeper/configuration/properties/instance/NonPersistentEMRProperty.java, java/configuration/src/main/java/sleeper/configuration/properties/instance/PersistentEMRProperty.java, java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java, java/configuration/src/main/java/sleeper/configuration/properties/validation/EmrInstanceTypeConfig.java, java/configuration/src/test/java/sleeper/configuration/UtilsTest.java, java/configuration/src/test/java/sleeper/configuration/properties/validation/EmrInstanceTypeConfigTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1127
- EmrInstanceTypeConfigTest.ValidateValue
=> Issue 1127 - Allow same weight for multiple instance types

java/configuration/src/main/java/sleeper/configuration/properties/validation/EmrInstanceTypeConfig.java, java/configuration/src/test/java/sleeper/configuration/properties/validation/EmrInstanceTypeConfigTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1127
- EmrInstanceTypeConfigTest.ValidateValue.shouldFailValidationWhenInstanceTypesPropertyIsNull
=> Issue 1127 - Fail validation when instance types property is unset

java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/StateMachinePlatformExecutor.java, java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/StateMachinePlatformExecutorTest.java, java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java, java/cdk/src/main/resources/step-functions/delete-driver-pod.json, java/cdk/src/main/resources/step-functions/delete-job.json, java/cdk/src/main/resources/step-functions/run-job.json
PR"
- Resolves https://github.com/gchq/sleeper/issues/1087
- Changes to CDK and Spark configuration. Tested in AWS, saw all EKS pods were deleted after each of 5 jobs.
=> Issue 1087 - Delete EKS bulk import job pods

.github/workflows/chunk.yaml
PR"
- Resolves https://github.com/gchq/sleeper/issues/1163
- Just GitHub workflow changes
- Site generation tested in PR: https://github.com/gchq/sleeper/pull/1166
=> Issue 1163 - Only build Maven site if tests failed

java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStatus.java, java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTaskStatus.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusInPeriodTest.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskStatusInPeriodTest.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/CompactionTaskStatusStoreInMemoryTest.java, java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByPeriodIT.java, java/core/src/main/java/sleeper/core/record/process/status/TimeWindowQuery.java, java/core/src/test/java/sleeper/core/record/process/status/TimeWindowQueryTest.java, java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatus.java, java/ingest/ingest-core/src/main/java/sleeper/ingest/task/IngestTaskStatus.java, java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusInPeriodTest.java, java/ingest/ingest-core/src/test/java/sleeper/ingest/task/IngestTaskStatusInPeriodTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1160
- TimeWindowQueryTest
- Updated tests checking whether each process is in a period
=> Issue 1160 - Include running processes in reports by period

java/core/src/main/java/sleeper/core/record/process/AverageRecordRate.java, java/core/src/test/java/sleeper/core/record/process/AverageRecordRateTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1134
- AverageRecordRateTest.shouldExcludeRunsWithRateOfNaNFromAverageRateCalculation
=> Issue 1134 - Exclude runs with rate of NaN from average rate calculation

python/setup.py, scripts/dev/updateVersionNumber.sh
PR"
- Resolves https://github.com/gchq/sleeper/issues/1177
- Just changed `updateVersionNumber.sh`, tested manually
=> Issue 1177 - Use Python dev version in `updateVersionNumber.sh`

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/OutputInstanceIds.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestParameters.java, scripts/functions/systemTestUtils.sh, scripts/functions/test/testSystemTestUtils.sh, scripts/test/nightly/runTests.sh
PR"
- Resolves https://github.com/gchq/sleeper/issues/1077
- testSystemTestUtils.sh
- Manually tested tear down in AWS
- Tear down is included in nightly test script
=> Issue 1077 - Remove hard coded teardown for Maven system tests

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestInstanceContext.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1196
=> Issue 1196 - Upload custom resources jar even when system test cluster is disabled

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/TearDownMavenSystemTest.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/OutputInstanceIds.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java, scripts/test/nightly/runTests.sh
PR"
- Resolves https://github.com/gchq/sleeper/issues/1204
- Logging, nightly test bash script change
=> Issue 1204 - Fix reference to system test instances in nightly test script tear down

docs/01-getting-started.md, docs/02-deployment-guide.md, example/full/instance.properties, example/full/table.properties, java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java, java/configuration/src/main/java/sleeper/configuration/properties/instance/EMRServerlessProperty.java, java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java, scripts/templates/instanceproperties.template
Update documentation and configuration examples to use consistent CPU architecture names.
- Resolves https://github.com/gchq/sleeper/issues/1229
Documentation changes only
=> docs(config, docs): normalise CPU architecture names

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/TestContext.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/TestContextTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1239
- TestContextTest.NestedClass
=> Issue 1239 - Include nested test class name in report filename

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/python/PythonRunner.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1251
=> Issue 1251 - Use `ClientUtils.runCommandLogOutput` in PythonRunner

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingIT.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/PartitionsTestHelper.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1247
- Updated PartitionSplittingIT
=> Issue 1247 - Assert on partitions created in PartitionSplittingIT

java/compaction/compaction-status-store/pom.xml, java/configuration/pom.xml, java/dynamodb-tools/pom.xml, java/ingest/ingest-status-store/pom.xml, java/parquet/pom.xml, java/statestore/pom.xml
Remove shade plugin from 6 modules that are never used externally.
- Resolves https://github.com/gchq/sleeper/issues/1245
=> fix(build) remove unnecessary JAR shading.

java/clients/src/main/java/sleeper/clients/admin/AdminClientPropertiesStore.java, java/clients/src/test/java/sleeper/clients/admin/AdminClientPropertiesStoreIT.java, java/configuration/src/main/java/sleeper/configuration/properties/PropertiesUtils.java, java/configuration/src/main/java/sleeper/configuration/properties/instance/InstanceProperties.java, java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperties.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1278
- AdminClientPropertiesStoreIT.LoadInvalidProperties
=> Issue 1278 - Allow loading invalid properties in admin client

java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1291
- Tested by running EmrPersistentBulkImportIT
=> Issue 1291 - Remove `m4.large` from EMR instance types in system tests

java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1304
=> Issue 1304 - Use big enough instances for EMR executors in system tests

docs/10-deploy-to-localstack.md, scripts/cli/runInDocker.sh, scripts/deploy/localstack/startContainer.sh
PR"
- Resolves https://github.com/gchq/sleeper/issues/1345
- Docker configuration
- Updated deploy to LocalStack documentation
=> Issue 1345 - Make Docker containers use default `bridged` network mode

java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/BulkImportArguments.java, java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrPlatformExecutor.java, java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrServerlessPlatformExecutor.java, java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/PersistentEmrPlatformExecutor.java, java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/PlatformExecutor.java, java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/StateMachinePlatformExecutor.java, java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/BulkImportArgumentsTest.java, java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrServerlessPlatformExecutorIT.java, java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/StateMachinePlatformExecutorTest.java, java/bulk-import/bulk-import-starter/src/test/resources/example/emr-serverless/jobrun-request.json, java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrServerlessBulkImportStack.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/DirectEmrServerlessDriver.java, java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/ingest/SystemTestDirectEmrServerless.java
Fixed setting Spark properties when none were set in the job.
Made Spark properties set on a job consistent between bulk import types. The Sleeper property prefix is no longer used for EMR Serverless.
PR"
- Resolves https://github.com/gchq/sleeper/issues/1491
- Improved EmrServerlessPlatformExecutorIT
- Added StateMachinePlatformExecutorTest.shouldIgnoreUserConfigurationIfSetToNull
=> Issue 1491 - Fix EMR Serverless bulk import

java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFilesRunner.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1528
=> Issue 1528 - Remove unnecessary catch in CompactSortedFilesRunner

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/NightlyTestOutput.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/NightlyTestUploadFile.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/NightlyTestUploader.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/TestResult.java, java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/nightly/NightlyTestOutputFileSystemIT.java, java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/nightly/NightlyTestOutputS3IT.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1536
- Updated NightlyTestOutputFileSystemIT, NightlyTestOutputS3IT
=> Issue 1536 - Upload each system test's output to its own folder

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceTablesDriver.java, java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/SleeperInstanceTablesDriverIT.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1546 
- SleeperInstanceTablesDriverIT.shouldDeleteNothingWhenNoTablesArePresentAndInstancePropertiesAreSavedInConfigBucket
=> Issue 1546 - Clear system test instance when only config file is present

java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsFromIteratorIT.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsFromIteratorLocalStackIT.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsIT.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsLocalStackIT.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsTestBase.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1585
- Updating IngestRecords*IT tests
=> Issue 1585 - Tidy assertions in IngestRecords*IT tests

java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1613
- Updating log message
=> Issue 1613 - Make logger output number of active files created in DynamoDBFileInfoStore

java/pom.xml, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceIT.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EksBulkImportIT.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceIT.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrPersistentBulkImportIT.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceIT.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesIT.java, scripts/test/nightly/runTests.sh
PR"
- Resolves https://github.com/gchq/sleeper/issues/1609
- Updates slow system tests with new tag
- Reduces number of tables in MultipleTablesIT further to keep it relatively quick
=> Issue 1609 - Move optional stack system tests to performance test suite

java/clients/src/main/java/sleeper/clients/status/update/ReinitialiseTable.java, java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java, java/core/src/main/java/sleeper/core/statestore/FileInfoStore.java, java/core/src/main/java/sleeper/core/statestore/PartitionStore.java, java/core/src/main/java/sleeper/core/statestore/StateStore.java, java/core/src/test/java/sleeper/core/statestore/inmemory/FixedPartitionStore.java, java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileInfoStore.java, java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryPartitionStore.java, java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java, java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBPartitionStore.java, java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java, java/statestore/src/main/java/sleeper/statestore/s3/S3PartitionStore.java, java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreMultipleTablesIT.java, java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreMultipleTablesIT.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1646
- Javadoc updates
=> Issue 1646 - Add missing Javadoc to state store methods

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonApiIT.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1679
- Updated PythonApiIT tests
=> Issue 1679 - Purge queues on test failures in PythonApiIT

java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStore.java, java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java, java/statestore/src/main/java/sleeper/statestore/s3/S3FileReference.java, java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java, java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java, java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java, java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreTestBase.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1693
- Add S3FileReferenceStoreIT.SplitFileReferences
=> Issue 1693 - Implement splitting file references in S3StateStore

java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateJobs.java, java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/strategy/DelegatingCompactionStrategy.java, java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsTest.java, java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/strategy/impl/BasicCompactionStrategyTest.java, java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesSplittingIT.java, java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/testutils/CompactSortedFilesTestBase.java, java/core/src/main/java/sleeper/core/statestore/SplitFileReferences.java, java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestCompaction.java
Functional system test is passing
PR"
- Resolves https://github.com/gchq/sleeper/issues/1672
- Updated CreateJobs / CompactSortedFiles tests
=> Issue 1672 - Run splitting compactions before compaction jobs are created

java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1733
- Only adds logging
=> Issue 1733 - Adding logging of number of attempts and total sleep time when updating S3 state store

example/full/instance.properties, example/full/table.properties, java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java, java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java, java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java, scripts/templates/instanceproperties.template
PR"
- Resolves https://github.com/gchq/sleeper/issues/1739
- Only changes configuration
- Branch has been tested on AWS and compactions with 49 input files ran successfully.
=> Issue 1739 - Changed default value of sleeper.fs.s3a.max-connections to 100 and added note to compaction batch size property

java/clients/src/test/java/sleeper/clients/status/report/filestatus/FilesStatusReportTest.java, java/core/src/main/java/sleeper/core/statestore/SplitFileReferences.java, java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStore.java, java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java, java/core/src/test/java/sleeper/core/statestore/inmemory/SplitFileReferencesTest.java, java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java, java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java, java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java, java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1720
- SplitFileReferencesTest
- Updating state store tests
=> Issue 1720 - Only split files references with no job ID assigned

example/basic/instance.properties, example/full/instance.properties, java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java, java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java, scripts/templates/instanceproperties.template
PR"
- Resolves https://github.com/gchq/sleeper/issues/1770
- Default property changes
=> Issue 1770 - Add TableMetricsStack and IngestBatcherStack to default optional stacks

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/AfterTestPurgeQueues.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/AfterTestPurgeQueuesTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1802
- Updated AfterTestPurgeQueuesTest
=> Issue 1802 - Do not wait for queue purge when purging no queues

java/clients/src/main/java/sleeper/clients/status/update/CreateJobsClient.java, java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateCompactionJobs.java, java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsTest.java, scripts/utility/compactAllFiles.sh, scripts/utility/compactFiles.sh
PR"
- Resolves https://github.com/gchq/sleeper/issues/1829
- Added new test in CreateCompactionJobsTest
=> Issue 1829 - Add ability to run compactAllFiles.sh for a specific table

java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java, java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1860
- Updated DynamoDBFileReferenceStoreIT
=> Issue 1860 - Assign job IDs to files for a batch of multiple jobs in DynamoDB state store

java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/StateMachinePlatformExecutor.java, java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/StateMachinePlatformExecutorTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1869
- Updated StateMachinePlatformExecutorTest
=> Issue 1869 - Truncate table name in EKS state machine execution name

example/full/instance.properties, java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java, java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java, java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java, java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java, java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java, scripts/templates/instanceproperties.template
PR"
- Resolves https://github.com/gchq/sleeper/issues/1960
- Resolves https://github.com/gchq/sleeper/issues/1965
- Adding new properties used in CDK
=> Issue 1960 - Add properties for table batching lambdas memory & timeout

code-style/checkstyle-idea/checkstyle.xml, code-style/checkstyle.xml, code-style/eclipse-style.xml, java/build/src/main/java/sleeper/build/maven/dependencydraw/DrawDependencyGraph.java, java/cdk/src/main/java/sleeper/cdk/Utils.java, java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateCompactionJobs.java, java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactSortedFilesTestData.java, java/configuration/src/main/java/sleeper/configuration/properties/table/CompressionCodec.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsTestBase.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorCommonIT.java, java/query/query-lambda/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java, java/sketches/src/test/java/sleeper/sketches/testutils/AssertQuantiles.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceIT.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceIT.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/1937
- Checkstyle configuration
=> Issue 1937 - Validate indentation and unnecessary semicolons in checkstyle

example/full/instance.properties, java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java, scripts/templates/instanceproperties.template
PR"
- Resolves https://github.com/gchq/sleeper/issues/2022
- Changing property definitions
=> Issue 2022 - Rename instance properties with prefix sleeper.table

java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/SystemTestCompaction.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/2219
=> Issue 2219 - Raise timeout in SystemTestCompaction.createJobs

.github/dependabot.yml
PR"
- Resolves https://github.com/gchq/sleeper/issues/2223
- Just Dependabot configuration
=> Issue 2223 - Raise limit of open Dependabot PRs

java/cdk/src/main/java/sleeper/cdk/stack/DashboardStack.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/2160
- This doesn't seem worth a system test, and we can't test it any other way
=> Issue 2160 - Limit tables to show in DashboardStack

.github/workflows/dependency-check-nightly.yaml, .github/workflows/maven-full.yaml
PR"
- Resolves https://github.com/gchq/sleeper/issues/2296
- Just workflow changes
=> Issue 2296 - Run workflows to refresh/check Maven cache

java/clients/src/main/java/sleeper/clients/QueryWebSocketClient.java, java/clients/src/main/java/sleeper/clients/exception/MessageMissingFieldException.java, java/clients/src/test/java/sleeper/clients/QueryWebSocketCommandLineClientTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/2327
=> Issue 2327 - Log bad JSON when web socket message is missing a required field

java/clients/src/main/java/sleeper/clients/status/report/partitions/PartitionStatus.java, java/clients/src/main/java/sleeper/clients/status/report/partitions/PartitionsStatus.java, java/clients/src/main/java/sleeper/clients/status/report/partitions/PartitionsStatusReporter.java, java/clients/src/test/java/sleeper/clients/admin/PartitionsStatusReportScreenTest.java, java/clients/src/test/java/sleeper/clients/status/report/partitions/PartitionsStatusTest.java, java/clients/src/test/resources/reports/partitions/noPartitions.txt, java/clients/src/test/resources/reports/partitions/nonLeafPartitionRecordCountExceedsThreshold.txt, java/clients/src/test/resources/reports/partitions/rootWithNestedChildrenSplitOnDifferentFields.txt, java/clients/src/test/resources/reports/partitions/rootWithNoChildren.txt, java/clients/src/test/resources/reports/partitions/rootWithTwoChildren.txt, java/clients/src/test/resources/reports/partitions/rootWithTwoChildrenBothNeedSplitting.txt, java/clients/src/test/resources/reports/partitions/rootWithTwoChildrenSplitOnByteArray.txt, java/clients/src/test/resources/reports/partitions/rootWithTwoChildrenSplitOnLongString.txt, java/clients/src/test/resources/reports/partitions/rootWithTwoChildrenWithSplitFiles.txt, java/core/src/main/java/sleeper/core/partition/PartitionTree.java, java/core/src/test/java/sleeper/core/partition/PartitionTreeTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/2369
- Updated partition reporting tests
=> Issue 2369 - Report on whether partitions will be split

example/full/table.properties, java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java, java/statestore/src/main/java/sleeper/statestore/StateStoreFactory.java, java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStore.java, java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStoreNoShapshots.java, java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStoreNoSnapshots.java, java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreDynamoDBSpecificIT.java, java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreTestBase.java, scripts/templates/tableproperties.template
PR"
- Resolves https://github.com/gchq/sleeper/issues/2400
- Updated TransactionLogStateStoreDynamoDBSpecificIT
=> Issue 2400 - Disable transaction log state store snapshots by class name

java/clients/src/main/java/sleeper/clients/status/report/filestatus/TableFilesStatistics.java, java/clients/src/test/java/sleeper/clients/status/report/filestatus/FilesStatusReportTest.java, java/clients/src/test/resources/reports/filestatus/json/fileWithPartitionThatNoLongerExists.json, java/clients/src/test/resources/reports/filestatus/standard/fileWithPartitionThatNoLongerExists.txt
PR"
- Resolves https://github.com/gchq/sleeper/issues/2422
- FilesStatusReportTest.shouldReportFilesStatusWhenPartitionsNoLongerExist
=> Issue 2422 - Handle files in partitions that no longer exist in FilesStatusReport

java/clients/src/main/java/sleeper/clients/util/AssumeSleeperRole.java, java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestClusterStack.java, java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperty.java, java/system-test/system-test-data-generation/pom.xml, java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/AssumedRoleClients.java, java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomData.java, java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataViaBatcher.java, java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataViaQueue.java, java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/InstanceIngestSession.java, java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataDirect.java, java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataFiles.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/RunWriteRandomDataTaskOnECS.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperInstance.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSystemTestResources.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceConfiguration.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceIT.java
This is in draft because it currently fails to load the instance properties in the system test writer task. It doesn't have permissions for that. We can either add permissions to load the instance properties for any instance, or assume the correct role when loading instance properties.
PR"
- Resolves https://github.com/gchq/sleeper/issues/2467
- Ran SetupInstanceIT in AWS on top of stack with system test cluster enabled
- Ran deployAll system test in AWS on top of stack
- Ran quick system test suite without system test cluster enabled
=> Issue 2467 - Assume ingest roles in system test cluster

docs/01-getting-started.md, docs/02-deployment-guide.md, docs/11-dev-guide.md
PR"
- Resolves https://github.com/gchq/sleeper/issues/2479
=> Issue 2479 - Update installation documentation

java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogSnapshot.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogSnapshotLoader.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java, java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogSnapshots.java, java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStateStoreTestBase.java, java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java, java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreSnapshotsTest.java, java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotStore.java, java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStore.java, java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogSnapshotCreator.java, java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogSnapshotMetadata.java, java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogSnapshotSerDe.java, java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotStoreIT.java, java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogSnapshotCreatorIT.java, java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogSnapshotSerDeIT.java
Tasks:
PR"
- Resolves https://github.com/gchq/sleeper/issues/2519
- TransactionLogStateStoreSnapshotsTest
=> Issue 2519 - Logic to load snapshot on state store update

java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogSnapshot.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogSnapshotCreator.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogSnapshotUtils.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java, java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogSnapshots.java, java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreSnapshotsTest.java, java/statestore-lambda/src/main/java/sleeper/statestore/TransactionLogSnapshotCreationLambda.java, java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotCreator.java, java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotStore.java, java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogSnapshotCreator.java, java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogSnapshotCreatorIT.java, java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreDynamoDBSpecificIT.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/2524
- Covered by existing tests, removed some in TransactionLogStateStoreSnapshotsTest
=> Issue 2524 - Remove setting transaction log state in builder

java/clients/src/main/java/sleeper/clients/status/update/DeleteTable.java, java/clients/src/test/java/sleeper/clients/status/update/DeleteTableIT.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/2550
- `DeleteTableIT.shouldDeleteTableWhenSnapshotIsPresent`
=> Issue 2550 - Handle deleting tables with snapshots

java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitter.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java, java/core/src/main/java/sleeper/core/util/ExponentialBackoffWithJitter.java, java/core/src/test/java/sleeper/core/util/ExponentialBackoffWithJitterTest.java, java/statestore/src/main/java/sleeper/statestore/s3/S3StateStoreDataFile.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/2529
- Updated ExponentialBackoffWithJitterTest
=> Issue 2529 - Use attempts count consistently with exponential backoff retries

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrPersistentBulkImportIT.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/2615
- Covered by system test
=> Issue 2615 - Don't purge deleted bulk import job queue in system test

java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/PersistentEmrPlatformExecutor.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/2616
- Ran persistent EMR system test in AWS
=> Issue 2616 - Read persistent EMR cluster name from instance properties

scripts/deploy/deleteTable.sh, scripts/utility/adminClient.sh, scripts/utility/filesStatusReport.sh, scripts/utility/fullStatusReport.sh, scripts/utility/partitionsStatusReport.sh, scripts/utility/query.sh, scripts/utility/reinitialiseTable.sh
PR"
- Resolves https://github.com/gchq/sleeper/issues/2671
=> Issue 2671 - Add missing java flags required by Arrow to read statestore files

java/core/src/main/java/sleeper/core/record/process/status/ProcessRunsBuilder.java, java/core/src/test/java/sleeper/core/record/process/status/ProcessRunsTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/2727
- Updated ProcessRunsTest
=> Issue 2727 - Handle status updates before start of run

example/full/instance.properties, example/full/table.properties, java/clients/src/test/java/sleeper/clients/admin/properties/UpdatePropertiesWithTextEditorIT.java, java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java, java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java, java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java, java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java, scripts/templates/instanceproperties.template, scripts/templates/tableproperties.template
PR"
- Resolves https://github.com/gchq/sleeper/issues/2761
- Renaming properties
=> Issue 2761 - Keep statestore property prefixes consistent

shell.nix
PR"
- Resolves https://github.com/gchq/sleeper/issues/2820
- Manually tested that both the AWS CLI and the Sleeper Python code work
=> Issue 2820 - Avoid botocore version clash in Nix shell

java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperTablesForTest.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/NoInstanceConnectedException.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/NoTableChosenException.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceContext.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/reporting/SystemTestReporting.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/extension/AfterTestReportsBase.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/SleeperInstanceTablesTest.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/reporting/SystemTestReportingTest.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestByQueue.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryReports.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/2822
- Added SystemTestReportingTest
- Updated SleeperInstanceTablesTest
=> Issue 2822 - Test system test reporting, add exceptions when no instance/table chosen

scripts/cli/builder/Dockerfile
PR"
- Resolves https://github.com/gchq/sleeper/issues/2855
=> Issue 2855 - Add JDK and sources to builder Docker image

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperTablesDriver.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/DirectQueryDriver.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/SQSQueryDriver.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/2846
- Ran MultipleTablesIT in AWS
=> Issue 2846 - Separate Hadoop config per parallel query

scripts/cli/buildAll.sh
PR"
- Resolves https://github.com/gchq/sleeper/issues/2883
- Ran full build script locally
=> Issue 2883 - Remove full Maven build from CLI build

scripts/cli/builder/Dockerfile, scripts/cli/environment/Dockerfile
PR"
- Resolves https://github.com/gchq/sleeper/issues/2899
- Tested manually running `scripts/cli/builder/build.sh` then `sleeper builder ./scripts/build/buildForTest.sh`
=> Issue 2899 - Use Bash as the entrypoint for CLI Docker images

java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskAssignFilesTest.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTestBase.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/2966
- Updated CompactionTaskAssignFilesTest
=> Issue 2966 - Do not report on failure waiting for compaction input file assignment

java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitRequestSerDe.java, java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobIdAssignmentCommitRequestSerDe.java, java/core/src/main/java/sleeper/core/statestore/commit/CommitRequestType.java, java/core/src/main/java/sleeper/core/statestore/commit/StateStoreCommitRequestInS3.java, java/core/src/main/java/sleeper/core/statestore/commit/StateStoreCommitRequestInS3SerDe.java, java/core/src/test/java/sleeper/core/statestore/commit/StateStoreCommitRequestInS3SerDeTest.java, java/core/src/test/java/sleeper/core/statestore/commit/StateStoreCommitRequestInS3SerDeTest.shouldSerialiseCommitRequestInS3.approved.txt, java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitRequest.java, java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitRequestDeserialiser.java, java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitter.java, java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitRequestDeserialiserTest.java, java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitterTest.java, java/statestore-lambda/src/main/java/sleeper/statestore/committer/lambda/StateStoreCommitterLambda.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/2974
- StateStoreCommitRequestInS3SerDeTest
- Updated StateStoreCommitRequestDeserialiserTest, StateStoreCommitterTest
=> Issue 2974 - Add support for storing state store commit requests in S3

java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportJobDriver.java, java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverIT.java, java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/commit/AddFilesToStateStore.java, java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTaskRunner.java, java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobRunner.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/commit/AddFilesToStateStoreIT.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java, java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/InstanceIngestSession.java, java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataDirect.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/2969
- Added AddFilesToStateStoreIT
- Updated BulkImportJobDriverIT
=> Issue 2969 - Store add files commit requests in S3 if they are too large

example/full/instance.properties, java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java, java/configuration/src/main/java/sleeper/configuration/properties/instance/PartitionSplittingProperty.java, scripts/templates/instanceproperties.template
PR"
- Resolves https://github.com/gchq/sleeper/issues/2930
- Just setting new properties, nightly system tests should be enough coverage
=> Issue 2930 - Set reserved concurrency for partition splitting lambdas

java/common/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBUtils.java, java/common/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBUtilsTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3005
- DynamoDBUtilsTest.RetryOnThrottlingException
=> Issue 3005 - Add DynamoDB helper for retrying code that throws throttling exception

example/full/instance.properties, java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java, java/configuration/src/main/java/sleeper/configuration/properties/instance/PartitionSplittingProperty.java, scripts/templates/instanceproperties.template
PR"
- Resolves https://github.com/gchq/sleeper/issues/3025
=> Issue 3025 - Remove reserved concurrency on find partitions to split lambda

java/core/src/main/java/sleeper/core/util/LoggedDuration.java, java/core/src/test/java/sleeper/core/util/LoggedDurationTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3099
- Updated LoggedDurationTest
=> Issue 3099 - Handle singular & negative in LoggedDuration

example/full/instance.properties, example/full/table.properties, java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java, java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java, java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java, java/statestore-lambda/src/main/java/sleeper/statestore/committer/lambda/StateStoreCommitterLambda.java, java/statestore/src/main/java/sleeper/statestore/StateStoreFactory.java, java/statestore/src/main/java/sleeper/statestore/StateStoreProvider.java, java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStore.java, java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStoreNoSnapshots.java, java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogSnapshotCreatorIT.java, java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreTestBase.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java, scripts/templates/instanceproperties.template
PR"
- Resolves https://github.com/gchq/sleeper/issues/2932
=> Issue 2932 - Avoid extra reads in state store committer

java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java, java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStore.java, java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3118
=> Issue 3118 - Avoid wait on first retry in state store committer

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3193
- Covered by testing in StateStoreCommitterThroughputST
=> 3193 State Store Committer throughput lower than expected after high throughput queue

java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/SystemTestCluster.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3239
=> Issue 3239 - Find generated job IDs before invoking ingest tasks

java/clients/src/main/java/sleeper/clients/status/report/ingest/job/PersistentEMRStepCount.java, java/clients/src/main/java/sleeper/clients/teardown/ShutdownSystemProcesses.java, java/clients/src/main/java/sleeper/clients/teardown/TerminateEMRClusters.java, java/clients/src/main/java/sleeper/clients/util/EmrUtils.java, java/clients/src/test/java/sleeper/clients/status/report/ingest/job/PersistentEMRStepCountIT.java, java/clients/src/test/java/sleeper/clients/teardown/ShutdownSystemProcessesIT.java, java/core/src/main/java/sleeper/core/util/RateLimitUtils.java, java/core/src/main/java/sleeper/core/util/StaticRateLimit.java, java/core/src/test/java/sleeper/core/util/StaticRateLimitTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3247
- StaticRateLimitTest
- Tested tear down script manually
=> Issue 3247 - Avoid EMR rate limit in Maven teardown script

code-style/dependency-check-suppressions.xml
PR"
- Resolves https://github.com/gchq/sleeper/issues/3310
=> Issue 3310 - Suppress vulnerability in WireMock dependency

java/common/common-task/src/main/java/sleeper/task/common/EC2InstanceDetails.java, java/common/common-task/src/test/java/sleeper/task/common/EC2InstanceDetailsIT.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3387
- EC2InstanceDetailsIT
=> Issue 3387 - Fix reading no instances in EC2InstanceDetails

java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java, java/compaction/compaction-core/src/main/java/sleeper/compaction/task/StateStoreWaitForFiles.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskAssignFilesTest.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskCommitTest.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTestBase.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/task/StateStoreWaitForFilesTest.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/StateStoreWaitForFilesTestHelper.java, java/compaction/compaction-job-execution/pom.xml, java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java, java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java, java/core/src/main/java/sleeper/core/statestore/UncheckedStateStoreException.java, java/core/src/test/java/sleeper/core/util/ExponentialBackoffWithJitterTestHelper.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3396
- Updated StateStoreWaitForFilesTest, CompactionTaskAssignFilesTest, CompactionTaskCommitTest
=> Issue 3396 - Handle failures waiting for compaction input files to be assigned

java/clients/src/main/java/sleeper/clients/teardown/TearDownInstance.java, java/core/src/main/java/sleeper/core/properties/local/LoadLocalProperties.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3408
=> Issue 3408 - Don't validate instance properties during teardown

java/clients/pom.xml, java/clients/src/main/java/sleeper/clients/deploy/RestartTasks.java, java/clients/src/main/java/sleeper/clients/teardown/ShutdownSystemProcesses.java, java/clients/src/main/java/sleeper/clients/teardown/TearDownClients.java, java/clients/src/main/java/sleeper/clients/teardown/TerminateEMRClusters.java, java/clients/src/test/java/sleeper/clients/teardown/ShutdownSystemProcessesIT.java, java/clients/src/test/java/sleeper/clients/testutil/ClientWiremockTestHelper.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTestBase.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/task/StateStoreWaitForFilesTest.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/StateStoreWaitForFilesTestHelper.java, java/core/src/main/java/sleeper/core/util/ExponentialBackoffWithJitter.java, java/core/src/main/java/sleeper/core/util/PollWithRetries.java, java/core/src/main/java/sleeper/core/util/RateLimitUtils.java, java/core/src/main/java/sleeper/core/util/ThreadSleep.java, java/core/src/main/java/sleeper/core/util/Waiter.java, java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogs.java, java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java, java/core/src/test/java/sleeper/core/util/ExponentialBackoffWithJitterTest.java, java/core/src/test/java/sleeper/core/util/ExponentialBackoffWithJitterTestHelper.java, java/core/src/test/java/sleeper/core/util/ThreadSleepTestHelper.java, java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreDataFileTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3279
=> Issue 3279 - Upgrade ECS SDK in clients module

java/clients/src/test/resources/reports/compaction/job/standard/all/jobWithMultipleRuns.txt, java/clients/src/test/resources/reports/compaction/job/standard/all/jobsWithLargeAndDecimalStatistics.txt, java/clients/src/test/resources/reports/compaction/job/standard/all/mixedJobs.txt, java/clients/src/test/resources/reports/compaction/job/standard/range/mixedJobs.txt, java/clients/src/test/resources/reports/compaction/job/standard/unfinished/mixedUnfinishedJobs.txt, java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusStatisticsTest.java, java/core/src/main/java/sleeper/core/util/DurationStatistics.java, java/core/src/test/java/sleeper/core/util/DurationStatisticsTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3347
- Updated DurationStatisticsTest, compaction job report test data
=> Issue 3347 - Add percentiles to compaction job statistics

java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EksBulkImportST.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrPersistentBulkImportST.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3478
- Updated EmrPersistentBulkImportST, EksBulkImportST
=> Issue 3478 - System test instances for EKS and persistent EMR bulk import

java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestParameters.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EksBulkImportST.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3486
- Updated EksBulkImportST
=> Issue 3486 - Disable EksBulkImportST if log retention is set

.github/workflows/dependency-check.yaml
PR"
- Resolves https://github.com/gchq/sleeper/issues/3524
- Workflow ran against PR
=> Issue 3524 - Temporarily disable dependency check plugin

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/ParallelCompactionsST.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3529
- Updated ParallelCompactionsST
=> Issue 3529 - Increase timeout for data generation in ParallelCompactionsST

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3528
- Updated StateStoreCommitterThroughputST
=> Issue 3528 - Remove upper limit on committer throughput assertions

java/cdk/src/main/java/sleeper/cdk/util/Utils.java, java/core/src/main/java/sleeper/core/statestore/AllReferencesToAllFiles.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/AwsSnapshotsDriver.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperTablesForTest.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceContext.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestTableFiles.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestTables.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/snapshot/SnapshotsDriver.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/snapshot/WaitForSnapshot.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/SystemTestStateStore.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreSnapshotsST.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3527
- StateStoreSnapshotsST
- Ran in AWS
=> Issue 3527 - Fix snapshot creation

.github/workflows/dependency-check.yaml, java/pom.xml
PR"
- Resolves https://github.com/gchq/sleeper/issues/3525
- Running in GitHub Actions
=> Issue 3525 - Re-enable dependency check workflow

java/cdk-environment/src/main/java/sleeper/environment/cdk/buildec2/BuildEC2Parameters.java, java/cdk-environment/src/main/java/sleeper/environment/cdk/config/AppParameters.java, java/cdk-environment/src/main/resources/nightlyTestSettings.json, java/cdk-environment/src/test/java/sleeper/environment/cdk/buildec2/BuildEC2ParametersTest.java, java/cdk-environment/src/test/java/sleeper/environment/cdk/buildec2/LoadUserDataUtilTest.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceConfiguration.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestParameters.java, scripts/cli/builder/Dockerfile, scripts/test/nightly/README.md, scripts/test/nightly/nightlyTestSettings.json, scripts/test/nightly/runTests.sh, scripts/test/nightly/updateAndRunTests.sh
PR"
- Resolves https://github.com/gchq/sleeper/issues/3571
- Tested bash code manually
- Updated BuildEC2ParametersTest, LoadUserDataUtilTest
=> Issue 3571 - Avoid conflicting nightly test names

example/full/instance.properties, java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskAssignFilesTest.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTestBase.java, java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java, scripts/templates/instanceproperties.template
PR"
- Resolves https://github.com/gchq/sleeper/issues/3554
- Updated CompactionTaskAssignFilesTest
=> Issue 3554 - Make compaction task file assignment wait optional

java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperty.java, java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/LocalStackTestInstance.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceConfiguration.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestParameters.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/gc/GarbageCollectionTest.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/MultipleTablesTest.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/SetupInstanceTest.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/SleeperInstanceTablesTest.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/partitioning/PartitionSplittingTest.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/sourcedata/SystemTestSourceFilesTest.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemoryTestInstance.java, java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3601
=> Issue 3601 - Make nightly test instance IDs short enough

java/common/common-task/src/main/java/sleeper/task/common/RunECSTasks.java, java/common/common-task/src/test/java/sleeper/task/common/RunECSTasksIT.java, java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperty.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3550
- Updated RunECSTasksIT
=> Issue 3550 - Allow no writers in deployAll system test

java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3619
- Updated CompactionTaskTest
=> Issue 3619 - Stop returning compactions for non-existent table to the queue

java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/SystemTestStateStore.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommits.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommitsTest.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterST.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3662
- Updated SystemTestStateStoreFakeCommitsTest, StateStoreCommitterST, StateStoreCommitterThroughputST
=> Issue 3662 - Raise polling timeout waiting for state store committer logs

.github/workflows/rust-lint.yaml, rust/compaction/tests/compaction_helpers.rs, rust/compaction/tests/compaction_test.rs, rust/rust_sketch/src/quantiles.rs
Closes 3750
My PR updates several tests with Clippy warning suppressions, or adopting Clippy warnings.
=> 3750 update Rust code to incorporate Clippy warnings for code style

java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/dispatch/CompactionJobBatchExpiredException.java, java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatchRequest.java, java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatcher.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatchRequestSerDeTest.shouldConvertRequestToFromJson.approved.json, java/compaction/compaction-job-creation-lambda/pom.xml, java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CompactionJobDispatchLambda.java, java/compaction/compaction-job-creation-lambda/src/test/java/sleeper/compaction/job/creation/lambda/CompactionJobDispatchLambdaIT.java, java/compaction/compaction-job-creation-lambda/src/test/java/sleeper/compaction/job/creation/lambda/CompactionJobsDispatchLambdaIT.java, java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsIT.java, java/core/src/main/java/sleeper/core/properties/instance/CdkDefinedInstanceProperty.java, java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3689
- CompactionJobDispatchLambdaIT
=> Issue 3689 - Lambda code for compaction job dispatch

example/full/instance.properties, example/full/table.properties, java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/creation/CreateCompactionJobs.java, java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/creation/CreateCompactionJobsTest.java, java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java, java/core/src/main/java/sleeper/core/properties/table/TableProperty.java, scripts/templates/instanceproperties.template
PR"
- Resolves https://github.com/gchq/sleeper/issues/3790
- Execution of existing unit tests suites (primarily CompactionJobLimitationsForInvocation.shouldCreateJobsLimitedDownToCreationLimitWhenTheCompactionJobsExceedTheValue as direct calls property)
=> Issue 3790: Adjustment of Compaction Instance Property to a Table Property

rust/compaction/src/datafusion.rs
PR"
- Resolves https://github.com/gchq/sleeper/issues/3808
- Sleeper functionality unchanged.
=> Issue 3808 - Disable page indexing on Parquet reading in DataFusion

example/full/instance.properties, java/common/common-task/src/main/java/sleeper/task/common/CompactionTaskHostScaler.java, java/common/common-task/src/test/java/sleeper/task/common/RunCompactionTasksTest.java, java/core/src/main/java/sleeper/core/properties/SleeperPropertyValues.java, java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java, java/core/src/main/java/sleeper/core/properties/validation/SleeperPropertyValueUtils.java, scripts/templates/instanceproperties.template
PR"
- Resolves https://github.com/gchq/sleeper/issues/3776
- Updated RunCompactionTasksTest
=> Issue 3776 - Configure memory overhead when scaling compaction EC2 instances

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceST.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3855
=> Issue 3855 - Raise timeout waiting for bulk import in performance test

java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java, java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreSnapshotsTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3859
- Updated TransactionLogStateStoreSnapshotsTest
=> Issue 3859 - Always load snapshot when no transactions have been read yet

.vscode/settings.json, java/core/src/main/java/sleeper/core/deploy/SqsQueues.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsResetInstanceOnFirstConnect.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperInstanceDriver.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsDrainSqsQueue.java, java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriverDrainCompactionsIT.java, java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/AwsResetInstanceOnFirstConnectIT.java, java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/AwsSleeperTablesDriverIT.java, java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/AwsSendCompactionJobsTestHelper.java, java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/LocalStackSleeperInstanceDriver.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperInstance.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SleeperInstanceDriver.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemorySleeperInstanceDriver.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3867
- AwsResetInstanceOnFirstConnectIT
=> Issue 3867 - Clear Sleeper instance on first connect in system tests

scripts/test/nightly/runTests.sh
PR"
- Resolves https://github.com/gchq/sleeper/issues/3884
- Just script change
=> Issue 3884 - Disable nightly DynamoDB system tests

java/cdk/src/main/java/sleeper/cdk/stack/core/TransactionLogTransactionStack.java, java/core/src/main/java/sleeper/core/properties/instance/TableStateProperty.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3913
=> Issue 3913 - Set queue visibility timeout for transaction deletion lambda

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/metrics/AwsTableMetricsDriver.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceConfiguration.java, java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestTables.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesST.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/TableMetricsST.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/3729
- Updated MultipleTablesST, TableMetricsST
=> Issue 3729 - Enable table metrics schedule rule in system tests

rust/compaction/src/datafusion.rs, rust/compaction/src/datafusion/metrics.rs
As an example, the DF compactor now produces output like below example for each file:
```
File file:///example/test.parquet { metadata_load_time = 6.491821ms, statistics_eval_time = 89.246µs, page_index_eval_time = 2ns, bytes_scanned = 41770148, row_groups_pruned_statistics = 13, row_groups_matched_statistics = 5, row_groups_pruned_bloom_filter = 0, row_groups_matched_bloom_filter = 0, page_index_rows_pruned = 0, page_index_rows_matched = 0, }
```
PR"
- Resolves https://github.com/gchq/sleeper/issues/4116
- No tests for extra logging.
=> 4116 enhance metric reporting on parquet files during compaction

example/full/instance.properties, java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java, java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java, java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java, java/statestore-committer-core/src/test/java/sleeper/statestore/committer/StateStoreCommitterThroughputIT.java, java/statestore-lambda/src/main/java/sleeper/statestore/lambda/committer/StateStoreCommitterLambda.java, java/statestore-lambda/src/test/java/sleeper/statestore/lambda/committer/StateStoreCommitterLambdaTest.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryStateStoreCommitter.java, scripts/templates/instanceproperties.template
PR"
- Resolves https://github.com/gchq/sleeper/issues/4132
- Updated StateStoreCommitterTest 
=> Issue 4132 - Option to disable job tracker update when a compaction job is committed

java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionDataFusionPerformanceST.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/ParallelCompactionsST.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/4175
- ParallelCompactionsST
=> Issue 4175 - Reduce waits in parallel compaction system test

java/compaction/compaction-rust/pom.xml, rust/buildForMaven.sh, scripts/build/build.sh
PR"
- Resolves https://github.com/gchq/sleeper/issues/4161
- See "Build Rust Modules" GitHub Actions run for non-quiet mode
- Ran build script manually and checked output
=> Issue 4161 - Use Maven logger when invoking Rust build

java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/StateStoreTransaction.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/impl/AssignJobIdsTransaction.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/impl/InitialisePartitionsTransaction.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/impl/ReplaceFileReferencesTransaction.java, java/core/src/test/java/sleeper/core/partition/PartitionsBuilder.java, java/core/src/test/java/sleeper/core/statestore/testutils/InMemoryTransactionLogStateStoreTestBase.java, java/core/src/test/java/sleeper/core/statestore/testutils/StateStoreUpdatesWrapper.java, java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStoreTest.java, java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStoreTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/4279
=> Issue 4279 - State store update wrapper for tests

java/common/dynamodb-test/pom.xml, java/common/dynamodb-test/src/main/java/sleeper/dynamodb/test/DynamoDBTestBase.java, java/common/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBRecordBuilderIT.java, java/common/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBTableTestBase.java, java/common/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBUtilsPagingIT.java, java/common/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBUtilsPagingLimitIT.java, java/compaction/compaction-tracker/src/test/java/sleeper/compaction/tracker/job/DynamoDBCompactionJobTrackerCreatorIT.java, java/compaction/compaction-tracker/src/test/java/sleeper/compaction/tracker/task/DynamoDBCompactionTaskTrackerCreatorIT.java, java/compaction/compaction-tracker/src/test/java/sleeper/compaction/tracker/testutils/DynamoDBCompactionJobTrackerTestBase.java, java/compaction/compaction-tracker/src/test/java/sleeper/compaction/tracker/testutils/DynamoDBCompactionTaskTrackerTestBase.java, java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreCreatorIT.java, java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreIT.java, java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreTestBase.java, java/ingest/ingest-tracker/src/test/java/sleeper/ingest/tracker/job/DynamoDBIngestJobTrackerCreatorIT.java, java/ingest/ingest-tracker/src/test/java/sleeper/ingest/tracker/task/DynamoDBIngestTaskTrackerCreatorIT.java, java/ingest/ingest-tracker/src/test/java/sleeper/ingest/tracker/testutils/DynamoDBIngestJobTrackerTestBase.java, java/ingest/ingest-tracker/src/test/java/sleeper/ingest/tracker/testutils/DynamoDBIngestTaskTrackerTestBase.java, java/query/query-lambda/src/test/java/sleeper/query/lambda/QueryMessageHandlerIT.java, java/query/query-runner/src/test/java/sleeper/query/runner/tracker/DynamoDBQueryTrackerIT.java, java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotMetadataStoreIT.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/4296
=> Issue 4296 - Reuse container in DynamoDBTestBase

.vscode/settings.json, java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/runner/BulkImportJobDriver.java, java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/BulkImportJobDriverTest.java, java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/impl/AddFilesTransaction.java, java/core/src/main/java/sleeper/core/tracker/ingest/job/update/IngestJobAddedFilesEvent.java, java/core/src/main/java/sleeper/core/tracker/ingest/job/update/IngestJobFailedEvent.java, java/core/src/main/java/sleeper/core/tracker/ingest/job/update/IngestJobFinishedEvent.java, java/core/src/main/java/sleeper/core/tracker/ingest/job/update/IngestJobRunIds.java, java/core/src/main/java/sleeper/core/tracker/ingest/job/update/IngestJobStartedEvent.java, java/core/src/test/java/sleeper/core/statestore/testutils/InMemoryTransactionLogs.java, java/core/src/test/java/sleeper/core/tracker/ingest/job/IngestJobEventTestData.java, java/ingest/ingest-core/src/main/java/sleeper/ingest/core/job/IngestJob.java, java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/impl/IngestCoordinator.java, java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/impl/commit/AddFilesToStateStore.java, java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/task/IngestJobRunner.java, java/ingest/ingest-runner/src/test/java/sleeper/ingest/runner/impl/commit/AddFilesToStateStoreTest.java, java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataToDocker.java, java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataDirect.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryDirectIngestDriver.java, java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestByQueue.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/4282
- New tests in BulkImportJobDriverTest, AddFilesToStateStoreTest
- Run existing test suites
=> 4282 -  Handle sync/asynchronous commit of ingest job tracker updates

example/full/instance.properties, java/core/src/main/java/sleeper/core/properties/instance/GarbageCollectionProperty.java, java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollector.java, java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorTest.java, scripts/templates/instanceproperties.template
PR"
- Resolves https://github.com/gchq/sleeper/issues/4484
- New test within GarbageCollectionTest - shouldDeleteFilesUpToLimitWithinSingleInvocation
=> Issue 4484 - Configure maximum files to delete per GC invocation

scripts/cli/builder/Dockerfile
PR"
- Resolves https://github.com/gchq/sleeper/issues/4559
- Ran locally in VS Code with the commands below
Ran the following commands in a terminal to rebuild the builder image and set it to be used in the dev container:
```bash
cd ./scripts/cli
./dependencies/build.sh
./builder/build.sh
docker tag sleeper-builder:current ghcr.io/gchq/sleeper-builder:latest
```
Then used VS Code's "Dev Containers: Rebuild Container" command, and waited for it to rebuild the container and reinstall all the extensions.
Once this PR is merged and the build has finished against develop in GitHub Actions, the commands above will not be needed and you can just run "Dev Containers: Rebuild Container" in VS Code. It still takes some time to rebuild the container and …
=> Issue 4559 - Install Java 21 in dev container

rust/compaction/src/datafusion.rs
PR"
- Resolves https://github.com/gchq/sleeper/issues/4240
- Restoring original behaviour before bug occured.
=> Issue 4240 - Write statistics truncation property in DataFusion compaction

rust/compaction/src/datafusion.rs
PR"
- Partial fix for https://github.com/gchq/sleeper/issues/4770
- Only partial fix. Issue not resolved.
=> Issue 4770 - Remove assumptions that all objects come from same S3 bucket

java/configuration/src/main/java/sleeper/configuration/jars/S3UserJarsLoader.java, java/configuration/src/test/java/sleeper/configuration/jars/S3UserJarsLoaderIT.java, java/query/query-lambda/src/main/java/sleeper/query/lambda/SqsQueryProcessor.java, java/query/query-lambda/src/main/java/sleeper/query/lambda/SqsQueryProcessorLambda.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/5067
- Updated S3UserJarsLoaderIT
=> Issue 5067 - Stop query lambda failing when loading jar twice

rust/compaction/src/datafusion.rs, rust/compaction/src/datafusion/sketch_udf.rs
Reverts gchq/sleeper#5187
This seems to have caused compaction tasks to run out of memory during large compactions. This was found by running the system test CompactionDataFusionPerformanceST.
=> Revert "Issue 5186 - Add extra sort stage to workaround DF breaking sort order"

java/clients/src/main/java/sleeper/clients/deploy/container/UploadDockerImages.java, java/clients/src/main/java/sleeper/clients/deploy/container/UploadDockerImagesToRepository.java, java/clients/src/test/java/sleeper/clients/deploy/container/UploadDockerImagesToEcrTest.java, java/clients/src/test/java/sleeper/clients/deploy/container/UploadDockerImagesToRepositoryTest.java, scripts/deploy/deployToDockerRepository.sh
PR"
- Resolves https://github.com/gchq/sleeper/issues/5260
- Updated UploadDockerImagesTest, UploadDockerImagesFileIT, UploadDockerImagesToRepositoryTest
=> Issue 5260 - Add option to not call `docker buildx create`

.github/pull_request_template.md, docs/development/conventions.md
PR"
- Resolves https://github.com/gchq/sleeper/issues/5315
=> Issue 5315 - Add Javadoc to PR template

java/configuration/src/main/java/sleeper/configuration/utils/S3Path.java, java/configuration/src/test/java/sleeper/configuration/utils/S3ExpandDirectoriesIT.java, java/configuration/src/test/java/sleeper/configuration/utils/S3PathTest.java
PR"
- Resolves https://github.com/gchq/sleeper/issues/5368
- S3PathTest
=> 5368: Fix issue with ingest when user uses a double slash in the path

java/athena/src/test/java/sleeper/athena/record/SimpleRecordHandlerIT.java, java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/BulkImportJobDriverIT.java, java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/dataframe/FileWritingIteratorIT.java, java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/dataframe/WriteParquetFilesIT.java, java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/runner/rdd/SingleFileWritingIteratorIT.java, java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java, java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactionRunnerTestData.java, java/parquet/src/main/java/sleeper/parquet/row/ParquetRowReaderFactory.java, java/query/query-runner/src/test/java/sleeper/query/runner/output/S3ResultsOutputIT.java, java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/python/PythonQueryDriver.java
- Resolves https://github.com/gchq/sleeper/issues/5435
=> Issue 5435: ParquetReader.useColumnIndexFilter setting is not applied consistently

java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/DefaultCompactionRunnerFactory.java
- Resolves https://github.com/gchq/sleeper/issues/5522
- Existing test suite execution
=> Issue 5522: DefaultCompactionRunnerFactory doesn't allow java compactions with aggregators specified

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionDataFusionPerformanceST.java
- Resolves https://github.com/gchq/sleeper/issues/5573
- Updated CompactionDataFusionPerformanceST
=> Issue 5573 - Lower minimum performance for DataFusion compactions

java/cdk/src/main/java/sleeper/cdk/stack/core/CoreStacks.java, java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestBatcherStack.java, java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestBatcherST.java
- Resolves https://github.com/gchq/sleeper/issues/5782
- IngestBatcherST.shouldIngestFileFromTableDataBucket
=> Issue 5782 - Ingest batcher permissions for table data bucket
