gchq/sleeper

scripts/deploy/uploadDockerImages.sh
scripts/deploy/uploadJars.sh

In response to #29 
Modify the checking (in the form of an "if" now) around the "aws ecr describe-repositories" and conditional docker repository creation and hide confusing error message from the user.

Conditional check around ecr create repo CLI command

---

.github/workflows/maven-full.yaml

Issue 24 - Full Maven build in GitHub Actions

---

java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrExecutorTest.java
java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/ExecutorFactoryIT.java
java/clients/src/test/java/sleeper/clients/AdminClientIT.java
java/clients/src/test/java/sleeper/status/update/ReinitialiseTableIT.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesIT.java
java/core/src/test/java/sleeper/core/key/KeySerDeTest.java
java/ingest/src/test/java/sleeper/ingest/testutils/ResultVerifier.java
java/query/src/test/java/sleeper/query/model/QuerySerDeTest.java
java/query/src/test/java/sleeper/query/model/output/WebSocketResultsOutputIT.java
java/tables/src/test/java/sleeper/table/job/TableInitialiserIT.java

**Note that this PR is stacked on top of #120, please merge that one first**

Issue 107 - Tidy up after automated AssertJ migration

---

java/athena/src/test/java/sleeper/athena/metadata/SimpleMetadataHandlerIT.java
java/athena/src/test/java/sleeper/athena/metadata/SleeperMetadataHandlerIT.java
java/athena/src/test/java/sleeper/athena/record/SimpleRecordHandlerIT.java
java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobRunnerIT.java
java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/StructTypeFactoryTest.java
java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/SleeperTableLambdaIT.java
java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/VpcCheckLambdaTest.java
java/clients/src/test/java/sleeper/status/partitions/ExportSplitPointsTest.java
java/clients/src/test/java/sleeper/status/update/ReinitialiseTableIT.java
java/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsTest.java
java/compaction-job-creation/src/test/java/sleeper/compaction/strategy/impl/BasicCompactionStrategyTest.java
java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIT.java
java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerIT.java
java/configuration/src/test/java/sleeper/configuration/EstimateSplitPointsTest.java
java/configuration/src/test/java/sleeper/configuration/properties/SleeperPropertiesTest.java
java/core/src/test/java/sleeper/core/partition/PartitionTreeTest.java
java/core/src/test/java/sleeper/core/partition/PartitionsFromSplitPointsTest.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
java/ingest/src/test/java/sleeper/ingest/IngestRecordsFromIteratorIT.java
java/ingest/src/test/java/sleeper/ingest/job/IngestJobUtilsTest.java
java/query/src/test/java/sleeper/query/executor/QueryExecutorIT.java
java/query/src/test/java/sleeper/query/model/QuerySerDeTest.java
java/splitter/src/test/java/sleeper/splitter/SplitPartitionIT.java
java/statestore/src/test/java/sleeper/statestore/InitialiseStateStoreIT.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
java/tables/src/test/java/sleeper/table/job/TableCreatorIT.java

**Note that this PR is stacked on top of #120, please merge that one first**

Issue 107 - Tidy AssertJ list assertions after automated migration

---

java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/AddPartitionIteratorTest.java
java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/FileWritingIteratorTest.java
java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/WriteParquetFilesTest.java
java/core/src/test/java/sleeper/core/MergingIteratorTest.java
java/core/src/test/java/sleeper/core/iterator/ConcatenatingIteratorTest.java
java/core/src/test/java/sleeper/core/iterator/impl/AdditionIteratorTest.java
java/core/src/test/java/sleeper/core/iterator/impl/AgeOffIteratorTest.java
java/core/src/test/java/sleeper/core/iterator/impl/SecurityFilteringIteratorTest.java
java/parquet/src/test/java/sleeper/io/record/ParquetReaderIteratorTest.java
java/query/src/test/java/sleeper/query/executor/QueryExecutorIT.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java

**Note that this PR is stacked on top of #124, please merge that one first**

Issue 107 - Apply AssertJ iterator assertions after automated migration

---

java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterIT.java
java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/ExecutorTest.java
java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/StateMachineExecutorTest.java
java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/SleeperTableLambdaIT.java
java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/VpcCheckLambdaTest.java
java/cdk/src/test/java/sleeper/cdk/ConfigValidatorIT.java
java/clients/src/test/java/sleeper/clients/AdminClientIT.java
java/compaction-job-creation/src/test/java/sleeper/compaction/job/CompactionJobTest.java
java/configuration/src/test/java/sleeper/configuration/EstimateSplitPointsTest.java
java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTest.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesTest.java
java/core/src/test/java/sleeper/core/iterator/ConcatenatingIteratorTest.java
java/core/src/test/java/sleeper/core/partition/PartitionTest.java
java/core/src/test/java/sleeper/core/range/RangeFactoryTest.java
java/core/src/test/java/sleeper/core/range/RangeTest.java
java/core/src/test/java/sleeper/core/schema/SchemaTest.java
java/ingest/src/test/java/sleeper/ingest/impl/IngestCoordinatorBespokeUsingDirectWriteBackedByArrowIT.java
java/query/src/test/java/sleeper/query/model/QuerySerDeTest.java
java/statestore/src/test/java/sleeper/statestore/InitialiseStateStoreIT.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java

**Note that this PR is stacked on top of #120, please merge that one first**
The automated migration did not include assertions on thrown exceptions, so this was done manually.

Issue 107 - Migrate exception assertions to AssertJ

---

java/athena/src/main/java/sleeper/athena/record/SimpleRecordHandler.java
java/core/src/main/java/sleeper/core/schema/Schema.java
java/core/src/test/java/sleeper/core/schema/SchemaDuplicateFieldsTest.java
java/core/src/test/java/sleeper/core/schema/SchemaTest.java
java/query/src/main/java/sleeper/query/recordretrieval/LeafPartitionQueryExecutor.java
java/statestore/src/main/java/sleeper/statestore/s3/S3StateStore.java

**Note that this PR is stacked on top of #123, please merge that one first**
Used this IntelliJ plugin to autogenerate the builder before adding validation: https://plugins.jetbrains.com/plugin/7354-innerbuilder
Resolves #6

Issue 6 - Check that field names are unique in a schema

---

code-style/intellij-style.xml

**Note that this PR is stacked on top of #155, please merge that one first**
Resolves #151

Issue 151 - Force curly braces in intellij-style.xml

---

java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIT.java
java/statestore/src/main/java/sleeper/statestore/DelegatingStateStore.java
java/statestore/src/main/java/sleeper/statestore/FileInfoStore.java
java/statestore/src/main/java/sleeper/statestore/StateStore.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBStateStore.java
java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java
java/statestore/src/main/java/sleeper/statestore/s3/S3PartitionStore.java
java/statestore/src/main/java/sleeper/statestore/s3/S3RevisionUtils.java
java/statestore/src/main/java/sleeper/statestore/s3/S3StateStore.java

Issue 127 - Split S3StateStore into smaller classes

---

java/athena/src/main/java/sleeper/athena/record/IteratorApplyingRecordHandler.java
java/core/src/main/java/sleeper/core/schema/Schema.java

Issue 187 - Suggestions from review

---

docs/01-getting-started.md
docs/02-deployment-guide.md

Issue 40 - Clarify required versions in 01-getting-started.md

---

scripts/deploy/uploadDockerImages.sh

Issue 176 - Incorrect message in scripts that upload Docker images

---

java/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
java/compaction-job-execution/pom.xml
java/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
java/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFilesRunner.java
java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIT.java
java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesReportingTest.java
java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerIT.java
java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/testutils/CompactSortedFilesTestUtils.java

Issue 203 - Report status update when compaction job started

---

java/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobRecordsProcessed.java
java/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
java/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobSummary.java
java/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobSummaryTest.java
java/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesEmptyOutputTest.java
java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIT.java
java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIteratorTest.java
java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesReportingTest.java
java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesSplittingTest.java
java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesTest.java

Issue 206 - Report status update when compaction job completed

---

java/compaction-core/pom.xml
java/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
java/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobCreatedStatus.java
java/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobFinishedStatus.java
java/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStartedStatus.java
java/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStatus.java
java/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStatusesBuilder.java
java/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusInPeriodTest.java
java/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusTest.java
java/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusesBuilderTest.java
java/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobTestDataHelper.java
java/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobTestUtils.java

Issue 214 - Interface to query compaction job status

---

java/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobRecordsProcessed.java
java/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobSummary.java
java/compaction-status-store/src/test/java/sleeper/compaction/status/job/StoreCompactionJobUpdatesIT.java

Issue 239 - Test compaction job status for multiple runs

---

.github/workflows/check-status.yaml
.github/workflows/chunk.yaml
.github/workflows/maven-full.yaml
NOTICES
java/pom.xml

Resolves #189
Also removed a duplicate dependency declaration for AssertJ which must have slipped in in some merge.

Issue 189 - Cache all Maven dependencies in GitHub Actions

---

java/clients/src/test/java/sleeper/status/report/compactiontask/CompactionTaskStatusReportTest.java
java/compaction-core/src/main/java/sleeper/compaction/task/CompactionTaskStatus.java
java/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskStatusInPeriodTest.java
java/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskStatusTest.java
java/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFilesRunner.java
java/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerIT.java
java/compaction-status-store/src/test/java/sleeper/compaction/status/task/QueryCompactionTasksByPeriodIT.java
java/compaction-status-store/src/test/java/sleeper/compaction/status/task/QueryCompactionTasksInProgressIT.java
java/compaction-status-store/src/test/java/sleeper/compaction/status/testutils/DynamoDBCompactionTaskStatusStoreTestBase.java

Issue 253 - Report compaction task finished before DynamoDB client is shut down

---

java/clients/src/main/java/sleeper/status/report/CompactionJobStatusReport.java
java/clients/src/main/java/sleeper/status/report/compactionjob/CompactionJobStatusReportArguments.java
java/clients/src/main/java/sleeper/status/report/compactionjob/CompactionJobStatusReporter.java
java/clients/src/test/java/sleeper/status/report/compactionjob/CompactionJobStatusReportArgumentsTest.java

Issue 257 - Fix null pointer exception when defaulting job report query type

---

docs/01-getting-started.md

Issue 259 - Use quick Maven profile for CDK environment deploy docs

---

java/clients/src/main/java/sleeper/status/report/compactionjob/CompactionJobStatusCollector.java
java/clients/src/main/java/sleeper/status/report/compactiontask/CompactionTaskQuery.java
java/clients/src/test/java/sleeper/status/report/compactiontask/CompactionTaskStatusReportTest.java
java/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
java/compaction-core/src/main/java/sleeper/compaction/task/CompactionTaskStartedStatus.java
java/compaction-core/src/main/java/sleeper/compaction/task/CompactionTaskStatus.java
java/compaction-core/src/main/java/sleeper/compaction/task/CompactionTaskStatusStore.java
java/compaction-core/src/main/java/sleeper/compaction/task/CompactionTaskStatusesBuilder.java
java/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskStatusesBuilderTest.java
java/compaction-status-store/src/main/java/sleeper/compaction/status/job/DynamoDBCompactionJobStatusStore.java
java/compaction-status-store/src/main/java/sleeper/compaction/status/task/DynamoDBCompactionTaskStatusFormat.java
java/compaction-status-store/src/main/java/sleeper/compaction/status/task/DynamoDBCompactionTaskStatusStore.java
java/compaction-status-store/src/test/java/sleeper/compaction/status/job/QueryAllCompactionJobsIT.java
java/compaction-status-store/src/test/java/sleeper/compaction/status/task/QueryAllCompactionTasksIT.java
java/compaction-status-store/src/test/java/sleeper/compaction/status/task/QueryCompactionTasksByPeriodIT.java
java/compaction-status-store/src/test/java/sleeper/compaction/status/testutils/DynamoDBCompactionJobStatusStoreTestBase.java
java/compaction-status-store/src/test/java/sleeper/compaction/status/testutils/DynamoDBCompactionTaskStatusStoreTestBase.java

Issue 270 - Query for all compaction tasks & jobs rather than using a big range

---

java/compaction-status-store/src/main/java/sleeper/compaction/status/task/DynamoDBCompactionTaskStatusFormat.java
java/compaction-status-store/src/test/java/sleeper/compaction/status/task/StoreCompactionTaskIT.java
java/compaction-status-store/src/test/java/sleeper/compaction/status/testutils/DynamoDBCompactionTaskStatusStoreTestBase.java

Issue 271 - Exception generated when querying Compaction Task

---

java/clients/src/main/java/sleeper/status/report/CompactionJobStatusReport.java
java/clients/src/test/java/sleeper/status/report/compactionjob/StatusReporterRangeQueryTest.java

Issue 275 - Convert date input to UTC in CompactionJobStatusReport

---

java/clients/src/main/java/sleeper/status/report/compactionjob/StandardCompactionJobStatusReporter.java
java/clients/src/test/resources/reports/compactionjobstatus/standard/all/jobWithMultipleRuns.txt
java/clients/src/test/resources/reports/compactionjobstatus/standard/all/mixedJobs.txt
java/clients/src/test/resources/reports/compactionjobstatus/standard/range/mixedJobs.txt
java/compaction-core/src/main/java/sleeper/compaction/job/status/AverageCompactionRate.java
java/compaction-core/src/test/java/sleeper/compaction/job/AverageCompactionRateTest.java
java/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobTestDataHelper.java

Issue 278 - Add average compaction rate to job status report

---

java/clients/src/main/java/sleeper/status/report/compactionjob/CompactionJobStatusCollector.java
java/clients/src/test/java/sleeper/status/report/compactionjob/CompactionJobStatusCollectorTest.java
java/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
java/compaction-status-store/src/main/java/sleeper/compaction/status/job/DynamoDBCompactionJobStatusStore.java
java/compaction-status-store/src/test/java/sleeper/compaction/status/job/DynamoDBCompactionJobStatusStoreTimeToLiveIT.java
java/compaction-status-store/src/test/java/sleeper/compaction/status/job/QueryCompactionJobStatusByIdIT.java
java/compaction-status-store/src/test/java/sleeper/compaction/status/testutils/DynamoDBCompactionJobStatusStoreTestBase.java

Issue 280 - Handle job not found in CompactionJobStatusReporter

---

python/src/sleeper/sleeper.py

Fixed a typo in sleeper.py

---

scripts/test/tearDown.sh

Issue 314 - Record time in system test teardown

---

java/cdk/src/main/java/sleeper/cdk/Utils.java
java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
java/system-test/src/main/java/sleeper/systemtest/cdk/SystemTestStack.java

Issue 333 - Set log group names for Fargate containers

---

java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrExecutor.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/PersistentEmrExecutor.java

Resolves https://github.com/gchq/sleeper/issues/284

EMR step name now includes bulk import job id

---

example/full/instance.properties
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrExecutor.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
java/configuration/src/main/java/sleeper/configuration/Utils.java
java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java

Resolves https://github.com/gchq/sleeper/issues/353

353 allow configuration of ebs for bulk import

---

.github/workflows/chunk.yaml

Run "Check rate limits" step even if build failed

---

java/ingest/src/main/java/sleeper/ingest/IngestRecordsUsingPropertiesSpecifiedMethod.java
java/ingest/src/main/java/sleeper/ingest/impl/IngestCoordinator.java
java/ingest/src/main/java/sleeper/ingest/impl/StandardIngestCoordinator.java
java/ingest/src/main/java/sleeper/ingest/impl/recordbatch/RecordBatchFactory.java
java/ingest/src/main/java/sleeper/ingest/impl/recordbatch/arraylist/ArrayListRecordBatchFactory.java
java/ingest/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowRecordBatchAcceptingRecordsFactory.java
java/ingest/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowRecordBatchFactory.java
java/ingest/src/test/java/sleeper/ingest/impl/IngestCoordinatorBespokeUsingDirectWriteBackedByArrowIT.java
java/ingest/src/test/java/sleeper/ingest/impl/IngestCoordinatorCommonIT.java

Issue 376 - RecordBatch factory for IngestCoordinator

---

example/full/instance.properties
scripts/templates/instanceproperties.template
scripts/test/system-test-instance.properties

Issue 393 - Add missing properties to properties files and templates

---

example/full/instance.properties
java/compaction-status-store/src/main/java/sleeper/compaction/status/task/DynamoDBCompactionTaskStatusStore.java
java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
scripts/templates/instanceproperties.template
scripts/test/system-test-instance.properties

Issue 394 - Split compaction TTL into job and task TTL

---

java/ingest/src/main/java/sleeper/ingest/job/IngestJob.java
java/ingest/src/test/java/sleeper/ingest/job/IngestJobTest.java

Issue 399 - Randomly generate an ID for IngestJob if no ID is set

---

code-style/checkstyle-idea/checkstyle-suppressions.xml
code-style/checkstyle-idea/checkstyle.xml

Issue 419 - Create checkstyle files for Checkstyle-IDEA plugin

---

java/cdk-environment/src/main/resources/user_data

Issue 409 - CDK environment build doesn't include packages for ARM64

---

java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowRecordBatchBase.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowRecordBatchFactory.java

Improved logging in ArrowRecordBatchBase and ArrowRecordBatchFactory

---

java/build/src/main/java/sleeper/build/chunks/GetChunkConfig.java
java/build/src/main/java/sleeper/build/chunks/ProjectChunk.java
java/build/src/main/java/sleeper/build/chunks/ProjectChunksYaml.java
java/build/src/test/java/sleeper/build/chunks/GetChunkConfigTest.java
java/build/src/test/java/sleeper/build/chunks/TestChunks.java
java/build/src/test/java/sleeper/build/status/CheckGitHubStatusConfigTest.java
java/build/src/test/resources/examples/config/chunks.yaml

Issue 460 - Allow chunks.yaml properties which will only be used in workflow

---

java/build/src/main/java/sleeper/build/chunks/ProjectChunks.java
java/build/src/main/java/sleeper/build/chunks/ProjectStructure.java
java/build/src/main/java/sleeper/build/github/actions/GitHubActionsChunkWorkflow.java
java/build/src/main/java/sleeper/build/github/actions/OnPushPathsDiff.java
java/build/src/test/java/sleeper/build/github/actions/OnPushPathsDiffExtraEntriesTest.java
java/build/src/test/java/sleeper/build/github/actions/OnPushPathsDiffTest.java
java/build/src/test/java/sleeper/build/github/actions/OnPushPathsDiffTestHelper.java
java/build/src/test/java/sleeper/build/testutil/TestProjectStructure.java

Issue 465 - Fail workflow validation if extra Maven dependencies declared

---

java/compaction/compaction-job-execution/pom.xml

Issue 466 - Remove ingest-runner dependency from compaction-job-execution

---

example/full/instance.properties
java/configuration/src/main/java/sleeper/configuration/Utils.java
java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/IngestFactory.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/AsyncS3PartitionFileWriterFactory.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTask.java
scripts/templates/instanceproperties.template
scripts/test/system-test-instance.properties

Issue 73 - Make properties on S3AsyncClient configurable in ingest

---

scripts/test/system-test-instance.properties

Reverted default ingest mode in system tests to direct

---

code-style/intellij-copyright-profile.xml
example/full/instance.properties
java/build/src/main/java/sleeper/build/chunks/ProjectChunks.java
java/build/src/main/java/sleeper/build/chunks/ProjectStructure.java
java/build/src/main/java/sleeper/build/github/actions/GitHubActionsChunkWorkflow.java
java/build/src/main/java/sleeper/build/github/actions/OnPushPathsDiff.java
java/build/src/test/java/sleeper/build/github/actions/OnPushPathsDiffExtraEntriesTest.java
java/build/src/test/java/sleeper/build/github/actions/OnPushPathsDiffTest.java
java/build/src/test/java/sleeper/build/github/actions/OnPushPathsDiffTestHelper.java
java/build/src/test/java/sleeper/build/testutil/TestProjectStructure.java
java/compaction/compaction-job-execution/pom.xml
java/configuration/src/main/java/sleeper/configuration/Utils.java
java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
java/core/src/main/java/sleeper/core/partition/PartitionTree.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/IngestFactory.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/AsyncS3PartitionFileWriterFactory.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTask.java
java/pom.xml
scripts/test/system-test-instance.properties

Issue 486 - Update copyright to use project period over current year

---

java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
java/distribution/src/main/assembly/zip.xml
java/ingest/ingest-runner/pom.xml
java/ingest/ingest-starter/pom.xml
java/ingest/ingest-starter/src/main/java/sleeper/ingest/starter/RunTasks.java
java/ingest/ingest-starter/src/main/java/sleeper/ingest/starter/RunTasksLambda.java
java/ingest/pom.xml

Issue 490 - Deploy minimal dependencies in ingest lambda

---

java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/configuration/ConfigurationUtils.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrExecutor.java

Resolves #498 
Manual tests of successful execution of bulk import jobs using persistent EMR and non-persistent EMR have been run..

Use Java 11 in EMR clusters

---

java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/SleeperTableLambdaIT.java
java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTest.java
java/configuration/src/test/java/sleeper/configuration/properties/SleeperPropertiesTest.java
java/splitter/src/test/java/sleeper/splitter/FindPartitionsToSplitIT.java
java/tables/src/test/java/sleeper/table/job/TableInitialiserIT.java

Issue 491 - Remove use of deprecated constructors for boxed primitives

---

NOTICES

Issue 496 - Update Maven version numbers in NOTICES

---

scripts/deploy/tearDown.sh

Issue 516 - Fix reference to CDK jar in deploy/tearDown.sh

---

scripts/test/deployAll/buildDeployTest.sh

Issue 518 - Fix script reference in scripts/test/deployAll/buildDeployTest.sh

---

code-style/checkstyle-idea/checkstyle.xml
code-style/checkstyle.xml

Issue #514 - Update IllegalImports to use JUnit5 imports

---

java/configuration/src/main/java/sleeper/configuration/properties/SystemDefinedInstancePropertyImpl.java
java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstancePropertyImpl.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyImpl.java
java/system-test/src/main/java/sleeper/systemtest/SystemTestPropertyImpl.java

Issue 553 - Add toString to Sleeper property implementations

---

.github/workflows/docker-deployment.yaml
.github/workflows/docker-local.yaml

Issue 562 - Fix pattern to ignore release versions in Docker image cleanup

---

java/clients/src/main/java/sleeper/status/update/ReinitialiseTable.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusFormat.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/task/DynamoDBCompactionTaskStatusFormat.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/task/DynamoDBCompactionTaskStatusStore.java
java/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBUtils.java
java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBRecordBuilderTest.java
java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBTableTestBase.java
java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBUtilsPagingIT.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusFormat.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/task/DynamoDBIngestTaskStatusFormat.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/task/DynamoDBIngestTaskStatusStore.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBPartitionStore.java

Issue 548 - Paginate DynamoDB Scan results in Compaction and Ingest stores

---

docs/01-getting-started.md
docs/02-deployment-guide.md
docs/09-dev-guide.md
docs/10-design.md
docs/12-performance-test.md

Issue 558 - Update system test documentation

---

docs/02-deployment-guide.md
java/cdk/src/main/java/sleeper/cdk/ConfigValidator.java
java/cdk/src/main/java/sleeper/cdk/NewInstanceValidator.java
java/cdk/src/main/java/sleeper/cdk/Utils.java
java/cdk/src/test/java/sleeper/cdk/ConfigValidatorIT.java
java/cdk/src/test/java/sleeper/cdk/ConfigValidatorTest.java
java/cdk/src/test/java/sleeper/cdk/NewInstanceValidatorIT.java
java/cdk/src/test/java/sleeper/cdk/ValidatorTestHelper.java
scripts/deploy/deploy.sh
scripts/deploy/tearDown.sh
scripts/test/deploy.sh
scripts/test/tearDown.sh

Issue 289 - Split validation for new instance and configuration in CDK

---

java/clients/src/main/java/sleeper/util/ClientUtils.java
java/clients/src/test/java/sleeper/clients/admin/InstancePropertyReportTest.java
java/clients/src/test/java/sleeper/clients/admin/TablePropertyReportTest.java
java/clients/src/test/java/sleeper/utils/ClientUtilsTest.java
java/configuration/src/main/java/sleeper/configuration/properties/SystemDefinedInstanceProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
java/system-test/src/main/java/sleeper/systemtest/SystemTestProperty.java

Issue 564 - Automatically line wrap property descriptions in admin client reports

---

java/clients/src/main/java/sleeper/status/report/partitions/PartitionStatus.java
java/clients/src/test/java/sleeper/status/report/partitions/PartitionStatusReportTestHelper.java
java/clients/src/test/java/sleeper/status/report/partitions/PartitionsStatusReportIT.java
java/clients/src/test/java/sleeper/status/report/partitions/PartitionsStatusReportTest.java
java/clients/src/test/java/sleeper/status/report/partitions/PartitionsStatusTest.java
java/clients/src/test/resources/reports/partitions/rootWithNestedChildrenSplitOnDifferentFields.txt
java/core/src/main/java/sleeper/core/partition/PartitionsFromSplitPoints.java
java/core/src/main/java/sleeper/core/range/Region.java
java/core/src/test/java/sleeper/core/partition/PartitionFactory.java
java/core/src/test/java/sleeper/core/partition/PartitionFactoryTest.java
java/core/src/test/java/sleeper/core/partition/PartitionsBuilder.java
java/core/src/test/java/sleeper/core/partition/PartitionsBuilderTest.java

Issue 590 - Fix split field display on partitions report

---

code-style/checkstyle.xml
java/cdk/src/test/java/sleeper/cdk/UtilsNormaliseSizeTest.java
java/clients/src/main/java/sleeper/clients/AdminClient.java
java/clients/src/main/java/sleeper/clients/admin/AdminConfigStore.java
java/clients/src/main/java/sleeper/status/update/DownloadConfig.java
java/clients/src/main/java/sleeper/util/ClientUtils.java
java/clients/src/main/resources/log4j.properties
java/clients/src/test/java/sleeper/clients/admin/AdminClientIT.java
java/clients/src/test/java/sleeper/clients/admin/AdminConfigStoreIT.java
java/clients/src/test/java/sleeper/clients/admin/deploy/GeneratePropertiesIT.java
java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientITBase.java
java/clients/src/test/java/sleeper/utils/ClientUtilsTest.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/InstanceDetails.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/SafeTerminationLambda.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/Scaler.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/SafeTerminationTest.java
java/configuration/src/main/java/sleeper/configuration/Requirements.java
java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
java/configuration/src/main/java/sleeper/configuration/properties/local/SaveLocalProperties.java
java/configuration/src/test/java/sleeper/configuration/properties/local/SaveLocalPropertiesIT.java
java/configuration/src/test/java/sleeper/configuration/properties/local/SaveLocalPropertiesTest.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/AwsExternalResource.java
java/system-test/src/main/java/sleeper/systemtest/compaction/InvokeCompactionJobCreation.java
java/system-test/src/main/java/sleeper/systemtest/compaction/InvokeCompactionTaskCreation.java
java/system-test/src/main/java/sleeper/systemtest/ingest/InvokeIngestTaskCreation.java
java/system-test/src/main/resources/log4j.properties
scripts/utility/adminClient.sh

Issue 292 - Deploy with CDK when properties change

---

java/clients/pom.xml
java/clients/src/main/java/sleeper/clients/admin/deploy/DeployNewInstance.java
java/clients/src/main/java/sleeper/clients/admin/deploy/GenerateInstanceProperties.java
java/clients/src/main/java/sleeper/clients/admin/deploy/JarsDiff.java
java/clients/src/main/java/sleeper/clients/admin/deploy/PreDeployInstance.java
java/clients/src/main/java/sleeper/clients/admin/deploy/SyncJars.java
java/clients/src/test/java/sleeper/clients/admin/deploy/GeneratePropertiesIT.java
java/clients/src/test/java/sleeper/clients/admin/deploy/SyncJarsIT.java
java/clients/src/test/java/sleeper/clients/admin/deploy/SystemTestInstance.java

Issue 605 - Access control settings for jars bucket

---

java/clients/src/test/java/sleeper/clients/admin/UpdatePropertyTest.java
java/configuration/src/main/java/sleeper/configuration/Utils.java
java/configuration/src/test/java/sleeper/configuration/UtilsTest.java

Issue 594 - Suppress exceptions thrown by property validationPredicates

---

java/clients/pom.xml
java/clients/src/test/java/sleeper/status/partitions/ExportSplitPointsIT.java
java/common-job/src/test/java/sleeper/job/common/action/ChangeMessageVisibilityTimeoutActionIT.java
java/core/src/test/java/sleeper/core/CommonTestConstants.java

Issue 596 - Upgrade LocalStack & DynamoDB in Testcontainers tests

---

docs/02-deployment-guide.md
example/basic/instance.properties
example/full/instance.properties
scripts/dev/updateVersionNumber.sh
scripts/templates/instanceproperties.template
scripts/test/compactionPerformance/system-test-instance.properties
scripts/test/deployAll/system-test-instance.properties

Issue 630 - Remove sleeper.version property from examples & templates

---

.github/workflows/docker-cli-branch.yaml
.github/workflows/docker-cli.yaml
scripts/build/build.sh
scripts/cli/environment/buildMaven.sh
scripts/cli/runInDocker.sh

Issue 635 - Command to update Sleeper CLI

---

java/cdk-environment/src/main/java/sleeper/environment/cdk/buildec2/BuildEC2Stack.java

Issue 290 - Use correct scope when performing Vpc lookup

---

.github/workflows/docker-cli-branch.yaml
scripts/cli/install.sh
scripts/cli/runInDocker.sh

Issue 645 - Handle script changes in CLI upgrade

---

docs/02-deployment-guide.md

Issue 580 - Update documentation for addTable and deployExisting scripts

---

docs/01-getting-started.md
docs/02-deployment-guide.md
docs/06-status.md
docs/07-data-retrieval.md
docs/09-dev-guide.md
docs/11-common-problems-and-their-solutions.md

Issue 643 - Update docs to use Sleeper CLI

---

scripts/utility/downloadConfig.sh

Issue 651 - Stop download script clearing directory

---

java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/rdd/SingleFileWritingIterator.java
java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/rdd/SingleFileWritingIteratorTest.java

Issue 649 - Test output of SingleFileWritingIterator

---

java/clients/src/main/java/sleeper/clients/admin/InstancePropertyReport.java
java/clients/src/main/java/sleeper/clients/admin/TablePropertyReport.java
java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
java/clients/src/main/java/sleeper/clients/deploy/GenerateTableProperties.java
java/clients/src/main/java/sleeper/console/ConsoleOutput.java
java/clients/src/test/java/sleeper/clients/admin/AdminClientIT.java
java/clients/src/test/java/sleeper/clients/deploy/CdkDeployInstanceTest.java
java/clients/src/test/java/sleeper/clients/deploy/GeneratePropertiesTest.java
java/configuration/pom.xml
java/configuration/src/main/java/sleeper/configuration/properties/InstanceProperties.java
java/configuration/src/main/java/sleeper/configuration/properties/InstanceProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/PropertiesUtils.java
java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
java/configuration/src/main/java/sleeper/configuration/properties/SleeperPropertyIndex.java
java/configuration/src/main/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinter.java
java/configuration/src/main/java/sleeper/configuration/properties/local/LoadLocalProperties.java
java/configuration/src/main/java/sleeper/configuration/properties/local/SaveLocalProperties.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperties.java
java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTest.java
java/configuration/src/test/java/sleeper/configuration/properties/SleeperPropertiesTest.java
java/configuration/src/test/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinterTest.java
java/configuration/src/test/java/sleeper/configuration/properties/format/ToStringPrintStream.java
java/configuration/src/test/java/sleeper/configuration/properties/local/LoadLocalPropertiesTablesTest.java
java/configuration/src/test/java/sleeper/configuration/properties/local/SaveLocalPropertiesTest.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesSchemaTest.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesTest.java
java/pom.xml

Issue 623 - Use properties report format in local config

---

java/build/src/main/java/sleeper/build/github/api/containers/DeleteGHCRVersions.java
java/build/src/test/java/sleeper/build/github/api/containers/DeleteGHCRVersionsTest.java

Issue 665 - Log failures deleting image versions

---

java/athena/src/test/java/sleeper/athena/TestUtils.java
java/clients/src/main/java/sleeper/status/partitions/ExportPartitions.java
java/clients/src/main/java/sleeper/status/update/ReinitialiseTable.java
java/clients/src/main/java/sleeper/status/update/ReinitialiseTableFromExportedPartitions.java
java/clients/src/main/java/sleeper/status/update/ReinitialiseTableFromSplitPoints.java
java/clients/src/test/java/sleeper/status/partitions/ExportSplitPointsIT.java
java/clients/src/test/java/sleeper/status/update/ReinitialiseTableIT.java
java/core/src/main/java/sleeper/core/partition/PartitionsFromSplitPoints.java
java/query/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
java/statestore/src/main/java/sleeper/statestore/InitialiseStateStore.java
java/statestore/src/main/java/sleeper/statestore/InitialiseStateStoreFromExportedPartitions.java
java/statestore/src/main/java/sleeper/statestore/InitialiseStateStoreFromSplitPoints.java
java/statestore/src/test/java/sleeper/statestore/InitialiseStateStoreIT.java
java/tables/src/main/java/sleeper/table/job/TableInitialiser.java
scripts/utility/reinitialiseTable.sh

Resolves #603 and #660.
New classes have been tested extensively on a real deployment.

603 export partition information to file

---

java/configuration/src/main/java/sleeper/configuration/properties/SystemDefinedInstanceProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinter.java
java/configuration/src/test/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinterTest.java

Issue 689 - Display notes for which properties are system-defined

---

java/configuration/src/main/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinter.java
java/configuration/src/test/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinterTest.java

Issue 688 - Filter by property group in properties pretty printer

---

java/clients/src/main/java/sleeper/clients/admin/PropertiesDiff.java
java/clients/src/main/java/sleeper/clients/admin/PropertyDiff.java
java/clients/src/main/java/sleeper/clients/admin/UpdatePropertiesRequest.java
java/clients/src/test/java/sleeper/clients/admin/AdminClientIT.java
java/clients/src/test/java/sleeper/clients/admin/AdminMainScreenTest.java
java/clients/src/test/java/sleeper/clients/admin/FilesStatusReportScreenTest.java
java/clients/src/test/java/sleeper/clients/admin/InstanceConfigurationTest.java
java/clients/src/test/java/sleeper/clients/admin/PartitionsStatusReportScreenTest.java
java/clients/src/test/java/sleeper/clients/admin/TableNamesReportTest.java
java/clients/src/test/java/sleeper/clients/admin/TableSelectHelperIT.java
java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientITBase.java
java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientMockStoreBase.java
java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientTestBase.java
java/clients/src/test/java/sleeper/clients/admin/testutils/RunAdminClient.java
java/clients/src/test/java/sleeper/console/TestConsoleInput.java
java/clients/src/test/java/sleeper/console/menu/ChooseOneTest.java
java/clients/src/test/java/sleeper/console/menu/ChooseOneTestBase.java
java/clients/src/test/java/sleeper/status/report/query/JobQueryTestBase.java
java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstancePropertyImpl.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyImpl.java

Issue 581 - Refuse editing uneditable properties

---

java/clients/src/main/java/sleeper/status/report/ingest/job/IngestJobStatusReportArguments.java

Issue 702 - Add usage message for Range query type in IngestJobStatusReport

---

java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStatus.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusFromRecordsTest.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusTest.java
java/core/src/main/java/sleeper/core/record/process/status/JobStatusUpdates.java

Issue 697 - Report jobs which started before the created update was stored

---

java/clients/src/main/java/sleeper/clients/admin/AdminMainScreen.java
java/clients/src/main/java/sleeper/clients/admin/InstanceConfigurationScreen.java
java/clients/src/main/java/sleeper/clients/admin/PropertyGroupSelectHelper.java
java/clients/src/main/java/sleeper/clients/admin/PropertyGroupWithCategory.java
java/clients/src/main/java/sleeper/clients/admin/UpdatePropertiesWithNano.java
java/clients/src/main/java/sleeper/console/menu/ChooseOne.java
java/clients/src/main/java/sleeper/console/menu/Chosen.java
java/clients/src/test/java/sleeper/clients/admin/InstanceConfigurationTest.java
java/clients/src/test/java/sleeper/clients/admin/UpdatePropertiesWithNanoTest.java
java/clients/src/test/java/sleeper/clients/admin/UpdatePropertiesWithNanoTestHelper.java
java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientITBase.java
java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientMockStoreBase.java
java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientTestBase.java
java/clients/src/test/java/sleeper/clients/admin/testutils/AdminConfigStoreTestHarness.java
java/clients/src/test/java/sleeper/clients/admin/testutils/ExpectedAdminConsoleValues.java
java/clients/src/test/java/sleeper/clients/admin/testutils/RunAdminClient.java
java/clients/src/test/java/sleeper/console/menu/ChooseOneTest.java
java/clients/src/test/java/sleeper/console/menu/ChooseUntilChoiceFoundTest.java
java/clients/src/test/java/sleeper/console/menu/ChooseUntilSomethingEnteredTest.java
java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
java/configuration/src/main/java/sleeper/configuration/properties/SleeperPropertyIndex.java

Issue 621 - View/edit properties by group in admin client

---

java/core/src/test/java/sleeper/core/partition/PartitionsBuilder.java
java/splitter/src/main/java/sleeper/splitter/FindPartitionToSplitResult.java
java/splitter/src/main/java/sleeper/splitter/FindPartitionsToSplit.java
java/system-test/pom.xml
java/system-test/src/main/java/sleeper/systemtest/compaction/SplitPartitionsUntilNoMoreSplits.java
java/system-test/src/main/java/sleeper/systemtest/compaction/WaitForCurrentSplitAddingMissingJobs.java
java/system-test/src/main/java/sleeper/systemtest/compaction/WaitForPartitionSplitting.java
java/system-test/src/main/java/sleeper/systemtest/compaction/WaitForPartitionSplittingQueue.java
java/system-test/src/test/java/sleeper/systemtest/compaction/WaitForPartitionSplittingTest.java

Issue 698 - Wait for partition splitting to finish by checking state store

---

java/clients/src/main/java/sleeper/clients/teardown/ShutdownSystemProcesses.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/RunTasks.java
java/core/src/main/java/sleeper/core/util/RateLimitUtils.java
java/core/src/test/java/sleeper/core/util/RateLimitUtilsTest.java
java/ingest/ingest-starter/src/main/java/sleeper/ingest/starter/RunTasks.java
java/system-test/src/main/java/sleeper/systemtest/ingest/RunWriteRandomDataTaskOnECS.java

Issue 731 - Run multiple ingest/compaction tasks in one call

---

java/cdk/src/main/java/sleeper/cdk/Utils.java
java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
java/cdk/src/main/java/sleeper/cdk/stack/TableStack.java
java/clients/src/main/java/sleeper/clients/cdk/CdkCommand.java
java/clients/src/main/java/sleeper/clients/cdk/CdkDeploy.java
java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
java/clients/src/test/java/sleeper/clients/cdk/InvokeCdkForInstanceTest.java
java/system-test/src/main/java/sleeper/systemtest/cdk/DeployNewTestInstance.java
scripts/deploy/deployNew.sh
scripts/test/compactionPerformance/deployTest.sh
scripts/test/deploy.sh
scripts/test/deployAll/deployTest.sh

Issue 716 - Add CDK flag to pause system at deploy time

---

java/system-test/src/main/java/sleeper/systemtest/compaction/InvokeCompactionJobCreation.java

Issue 741 - Fix compilation in InvokeCompactionJobCreation

---

java/clients/src/main/java/sleeper/status/update/DownloadConfig.java

Issue 738 - Add log line to DownloadConfig class

---

java/clients/src/main/java/sleeper/clients/admin/AdminClientPropertiesStore.java
java/clients/src/main/java/sleeper/clients/admin/AdminCommonPrompts.java
java/clients/src/main/java/sleeper/clients/admin/CompactionStatusReportScreen.java
java/clients/src/main/java/sleeper/clients/admin/FilesStatusReportScreen.java
java/clients/src/main/java/sleeper/clients/admin/IngestStatusReportScreen.java
java/clients/src/main/java/sleeper/clients/admin/InstanceConfigurationScreen.java
java/clients/src/main/java/sleeper/clients/admin/PartitionsStatusReportScreen.java
java/clients/src/main/java/sleeper/clients/admin/TableSelectHelper.java
java/clients/src/test/java/sleeper/clients/admin/AdminClientPropertiesStoreIT.java
java/clients/src/test/java/sleeper/clients/admin/AdminCommonPromptsTest.java
java/clients/src/test/java/sleeper/clients/admin/FilesStatusReportScreenTest.java
java/clients/src/test/java/sleeper/clients/admin/InstanceConfigurationTest.java
java/clients/src/test/java/sleeper/clients/admin/PartitionsStatusReportScreenTest.java
java/clients/src/test/java/sleeper/clients/admin/TableSelectHelperIT.java
java/clients/src/test/java/sleeper/clients/admin/TableSelectHelperTest.java
java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientMockStoreBase.java

Issue 718 - Avoid reloading properties in admin client

---

java/bulk-import/bulk-import-common/pom.xml
java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/job/BulkImportJob.java
java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/job/BulkImportJobSerDe.java
java/bulk-import/bulk-import-common/src/test/java/sleeper/bulkimport/job/BulkImportJobSerDeTest.java
java/bulk-import/bulk-import-common/src/test/java/sleeper/bulkimport/job/BulkImportJobTest.java

Issue 744 - Adapt IngestJobStatusStore to accept BulkImportJobs

---

example/basic/tags.properties
example/full/tags.properties
java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
scripts/templates/tags.template

Issue 750 - Set AWS tag for instance ID on deploy

---

java/cdk-environment/src/main/java/sleeper/environment/cdk/buildec2/BuildEC2Stack.java
scripts/utility/downloadConfig.sh

Resolves #754 
Also fixed a problem where downloadConfig.sh didn't create the generated directory if it didn't exist.

Issue 754 - Pre-authenticate build EC2

---

java/clients/pom.xml
java/clients/src/main/java/sleeper/status/update/CleanUpLogGroups.java
java/clients/src/test/java/sleeper/ClientWiremockTestHelper.java
java/clients/src/test/java/sleeper/status/update/CleanUpLogGroupsIT.java
java/core/src/main/java/sleeper/core/util/RateLimitUtils.java

Issue 752 - Clean up old log groups

---

java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
java/clients/src/main/java/sleeper/clients/deploy/GenerateTableProperties.java
java/system-test/src/main/java/sleeper/systemtest/cdk/DeployNewTestInstance.java
scripts/deploy/deployNew.sh
scripts/test/deploy.sh
scripts/test/deployAll/deployTest.sh

Issue 765 - Add splitPointsFile parameter to deploy scripts

---

java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
java/clients/src/main/java/sleeper/clients/AdminClient.java
java/clients/src/main/java/sleeper/clients/admin/IngestStatusReportScreen.java
java/clients/src/main/java/sleeper/clients/status/report/IngestJobStatusReport.java
java/clients/src/main/java/sleeper/clients/status/report/ingest/job/IngestJobStatusReporter.java
java/clients/src/main/java/sleeper/clients/status/report/ingest/job/JsonIngestJobStatusReporter.java
java/clients/src/main/java/sleeper/clients/status/report/ingest/job/PersistentEMRStepCount.java
java/clients/src/main/java/sleeper/clients/status/report/ingest/job/StandardIngestJobStatusReporter.java
java/clients/src/main/java/sleeper/clients/teardown/TerminateEMRClusters.java
java/clients/src/main/java/sleeper/clients/util/EmrUtils.java
java/clients/src/test/java/sleeper/clients/admin/testutils/RunAdminClient.java
java/clients/src/test/java/sleeper/clients/status/report/ingest/job/IngestJobStatusReporterTestHelper.java
java/clients/src/test/java/sleeper/clients/status/report/ingest/job/JsonIngestJobStatusReporterAllQueryTest.java
java/clients/src/test/java/sleeper/clients/status/report/ingest/job/PersistentEMRStepCountIT.java
java/clients/src/test/java/sleeper/clients/status/report/ingest/job/StandardIngestJobStatusReporterAllQueryTest.java
java/clients/src/test/java/sleeper/clients/teardown/ShutdownSystemProcessesIT.java
java/clients/src/test/java/sleeper/clients/testutil/WiremockEMRTestHelper.java
java/clients/src/test/resources/reports/ingest/job/json/noJobsWithEmrStepsUnfinished.json
java/clients/src/test/resources/reports/ingest/job/standard/all/noJobsWithEmrStepsUnfinished.txt
java/configuration/src/main/java/sleeper/configuration/properties/SystemDefinedInstanceProperty.java
java/system-test/src/main/java/sleeper/systemtest/bulkimport/SendBulkImportJobs.java
java/system-test/src/main/java/sleeper/systemtest/bulkimport/WaitForEMRClusters.java

Issue 779 - Report pending PersistentEMR steps in ingest reports

---

docs/05-ingest.md

Issue 796 - Fix command in EKS debugging documentation

---

CHANGELOG.md

Issue 799 - Update changelog for 0.16.0

---

.devcontainer/devcontainer.json

Issue 812 - Dev Container settings for VS Code & AWS CLI

---

java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/task/DynamoDBCompactionTaskStatusFormat.java
java/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBAttributes.java
java/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBRecordBuilder.java
java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBAttributesTest.java
java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBRecordBuilderIT.java
java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBTableTestBase.java
java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBUtilsPagingIT.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/task/DynamoDBIngestTaskStatusFormat.java
java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/task/StoreIngestTaskIT.java
java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/testutils/DynamoDBIngestTaskStatusStoreTestBase.java

Issue 816 - Handle NaN in DynamoDB

---

java/configuration/src/main/java/sleeper/configuration/Utils.java
java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyGroup.java
java/configuration/src/main/java/sleeper/configuration/properties/validation/BatchIngestMode.java

Issue 829 - Ingest batcher property definitions

---

java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/RunTasks.java
java/ingest/ingest-starter/src/main/java/sleeper/ingest/starter/RunTasks.java
java/system-test/src/main/java/sleeper/systemtest/util/WaitForQueueEstimate.java

Issue 834 - Log queue names in system tests

---

.github/config/chunks.yaml
.github/workflows/chunk-ingest-common.yaml
java/ingest/ingest-batch-core/pom.xml
java/ingest/ingest-batch-core/src/main/java/sleeper/ingest/batcher/FileIngestRequest.java
java/ingest/ingest-batch-core/src/main/java/sleeper/ingest/batcher/IngestBatcherStateStore.java
java/ingest/ingest-batch-core/src/main/java/sleeper/ingest/batcher/TrackedFile.java
java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/IngestBatcherStateStoreInMemory.java
java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/IngestBatcherStateStoreInMemoryTest.java
java/ingest/ingest-batch-core/src/test/java/sleeper/ingest/batcher/IngestBatcherStateStoreKeyFields.java
java/ingest/pom.xml

Issue 833 - Ingest batching tracker logic

---

NOTICES
java/pom.xml

Issue 818 - Bump parquet-hadoop to 1.13.0

---

scripts/test/nightly/runTests.sh
scripts/test/nightly/updateAndRunTests.sh

Resolves #857 
Waiting for test to finish then will mark as ready

Issue 857 - Extract git update script from nightly test script

---

java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesProvider.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesIT.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesProviderIT.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesS3TestBase.java
java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambda.java

Issue 862 - Check table exists in TablePropertiesProvider

---

.github/workflows/chunk-cdk.yaml
java/ingest/ingest-batcher-core/src/main/java/sleeper/ingest/batcher/IngestBatcher.java
java/ingest/ingest-batcher-job-creator/src/main/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambda.java
java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/FileIngestRequestSerDe.java
java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambda.java
java/system-test/pom.xml
java/system-test/src/main/java/sleeper/systemtest/ingest/WaitForIngestTasks.java
java/system-test/src/main/java/sleeper/systemtest/ingest/batcher/InvokeIngestBatcher.java
java/system-test/src/main/java/sleeper/systemtest/ingest/batcher/SendFilesToIngestBatcher.java
java/system-test/src/main/java/sleeper/systemtest/ingest/batcher/SystemTestForIngestBatcher.java
scripts/test/ingestBatcher/buildDeployTest.sh
scripts/test/ingestBatcher/deployTest.sh
scripts/test/ingestBatcher/system-test-instance.properties
scripts/test/nightly/runTests.sh

Issue 851 - System test for ingest batcher

---

example/full/instance.properties
example/full/table.properties
java/clients/src/main/java/sleeper/clients/util/ComparePropertiesTemplates.java
java/clients/src/test/java/sleeper/clients/admin/InstanceConfigurationTest.java
java/clients/src/test/java/sleeper/clients/status/partitions/ExportSplitPointsIT.java
java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
java/configuration/src/main/java/sleeper/configuration/Utils.java
java/configuration/src/main/java/sleeper/configuration/properties/InstancePropertyGroup.java
java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstancePropertyImpl.java
java/configuration/src/main/java/sleeper/configuration/properties/format/GeneratePropertiesTemplates.java
java/configuration/src/main/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinter.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyGroup.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyImpl.java
java/configuration/src/test/java/sleeper/configuration/properties/format/GeneratePropertiesTemplatesTest.java
java/configuration/src/test/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinterTest.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBStateStore.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBStateStoreCreator.java
java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java
java/statestore/src/main/java/sleeper/statestore/s3/S3StateStore.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
scripts/dev/generatePropertiesTemplates.sh

Resolves #873
Reordered some properties in the templates and definitions to make them match up. That should make the diff easier to read.
Will follow up with another PR to actually run the generation, which will show the full changes to the resulting files.

Issue 873 - Automate properties templates

---

.github/workflows/dependency-check-changes.yaml
.github/workflows/dependency-check-nightly.yaml
.github/workflows/dependency-check.yaml
.github/workflows/maven-full.yaml
code-style/dependency-check-suppressions.xml
java/pom.xml

Resolves #837
Haven't set a threshold for failing the build yet as there are outstanding CVEs that we haven't suppressed yet. It still seems best to merge this in. We can address them separately.

Issue 837 - OWASP dependency checks

---

java/common-job/src/main/java/sleeper/job/common/ECSFailureException.java
java/common-job/src/main/java/sleeper/job/common/RunECSTasks.java
java/common-job/src/test/java/sleeper/job/common/RunECSTasksIT.java
java/system-test/src/main/java/sleeper/systemtest/ingest/RunWriteRandomDataTaskOnECS.java

Issue 853 - Use `RunECSTasks` in `RunWriteRandomDataTaskOnECS`

---

java/clients/src/test/java/sleeper/clients/admin/InstanceConfigurationTest.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertyImpl.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesTest.java

Issue 874 - Set default value from default property in TableProperty

---

java/query/src/main/java/sleeper/query/executor/QueryExecutor.java

Resolves https://github.com/gchq/sleeper/issues/886

Issue 886 Update the QueryExecutor exception message

---

scripts/test/nightly/runTests.sh

Issue 877 - Run reports after nightly tests

---

CHANGELOG.md

Issue 887 - Update changelog for 0.17

---

java/system-test/src/main/java/sleeper/systemtest/ingest/batcher/SystemTestForIngestBatcher.java
scripts/test/nightly/runTests.sh

Issue 901 - Delete source bucket after ingest batcher system test

---

example/full/instance.properties
example/full/table.properties
java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
java/parquet/src/main/java/sleeper/io/parquet/record/ParquetRecordWriterFactory.java
java/query/src/main/java/sleeper/query/model/output/S3ResultsOutput.java
scripts/dev/generatePropertiesTemplates.sh
scripts/templates/instanceproperties.template

Issue 81 - Configure statistics truncation

---

java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java

Issue 922 - Use CompletableFuture in S3StateStoreIT.shouldAddFilesUnderContention

---

docs/05-ingest.md
example/full/instance.properties
example/full/table.properties
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/BulkImportPlatformSpec.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrExecutor.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceConfiguration.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceFleet.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceFleets.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceGroups.java
java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrExecutorTest.java
java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
scripts/templates/instanceproperties.template

Issue 805 - Instance fleets for non-persistent EMR bulk import

---

example/full/instance.properties
java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/configuration/BulkImportPlatformSpec.java
java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/configuration/EmrInstanceTypeConfig.java
java/bulk-import/bulk-import-common/src/test/java/sleeper/bulkimport/configuration/EmrInstanceTypeConfigTest.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrExecutor.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceConfiguration.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceFleets.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceGroups.java
java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrExecutorTest.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
java/configuration/src/main/java/sleeper/configuration/properties/UserDefinedInstanceProperty.java
scripts/templates/instanceproperties.template

Issue 920 - Instance fleets for persistent EMR bulk import

---

java/system-test/src/main/java/sleeper/systemtest/compaction/SplitPartitionsUntilNoMoreSplits.java
java/system-test/src/main/java/sleeper/systemtest/compaction/WaitForCurrentSplitAddingMissingJobs.java
java/system-test/src/main/java/sleeper/systemtest/ingest/batcher/SystemTestForIngestBatcher.java
java/system-test/src/main/java/sleeper/systemtest/util/InvokeSystemTestLambda.java

Issue 925 - Increase Lambda timeout for system tests

---

scripts/test/bulkImportPerformance/tags.properties
scripts/test/compactionPerformance/tags.properties
scripts/test/ingestBatcher/tags.properties
scripts/test/partitionSplitting/tags.properties

Issue 850 - Tag system tests for cost explorer

---

java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
java/system-test/src/main/java/sleeper/systemtest/bulkimport/SendBulkImportJobs.java
java/system-test/src/main/java/sleeper/systemtest/cdk/SystemTestApp.java
java/system-test/src/main/java/sleeper/systemtest/cdk/SystemTestIngestBucketStack.java
java/system-test/src/main/java/sleeper/systemtest/cdk/SystemTestStack.java
java/system-test/src/main/java/sleeper/systemtest/ingest/WriteRandomDataFiles.java
java/system-test/src/main/java/sleeper/systemtest/ingest/WriteRandomDataGenerateOnlyJob.java
java/system-test/src/main/java/sleeper/systemtest/ingest/WriteRandomDataViaQueueJob.java

Issue 940 - Create and use ingest source bucket in relevant system tests

---

java/system-test/pom.xml
java/system-test/src/main/java/sleeper/systemtest/util/InvokeSystemTestLambda.java

Issue 944 - Raise socket read timeout for Lambda API HTTP client

---

java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java

Issue 938 - Extract tests from GarbageCollectorIT

---

java/clients/src/main/java/sleeper/clients/teardown/RemoveJarsBucket.java
java/clients/src/main/java/sleeper/clients/teardown/WaitForS3BucketToEmpty.java
java/clients/src/test/java/sleeper/clients/teardown/RemoveJarsBucketIT.java
java/clients/src/test/java/sleeper/clients/teardown/WaitForS3BucketToEmptyIT.java

Issue 951 - Wait for jars bucket to empty before deleting during tearDown

---

docs/01-getting-started.md
java/cdk-environment/pom.xml
java/cdk-environment/src/main/java/sleeper/environment/cdk/GetStackOutputs.java
java/cdk-environment/src/main/java/sleeper/environment/cdk/outputs/StackOutputs.java
java/cdk-environment/src/main/java/sleeper/environment/cdk/util/CdkFailedException.java
java/cdk-environment/src/main/java/sleeper/environment/cdk/util/ListEnvironmentStacks.java
java/cdk-environment/src/test/java/sleeper/environment/cdk/outputs/StackOutputsIT.java
java/cdk-environment/src/test/java/sleeper/environment/cdk/outputs/StackOutputsTest.java
java/cdk-environment/src/test/java/sleeper/environment/cdk/testutil/EnvironmentWiremockTestHelper.java
java/cdk-environment/src/test/java/sleeper/environment/cdk/util/ListEnvironmentStacksIT.java
scripts/cli/environment/scripts/subcommands/add.sh

Issue 965 - Connect to deployed environment without redeploy

---

java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java

Issue 975 - Raise queue visibility timeout for bulk import starter Lambda

---

java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/BulkImportStarterLambda.java
java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/BulkImportExecutorIT.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/IngestJobStatusStoreFactory.java
java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/testutils/DynamoDBIngestJobStatusStoreTestBase.java
java/system-test/src/main/java/sleeper/systemtest/ingest/batcher/InvokeIngestBatcher.java

Always use IngestJobStatusStoreFactory to build DynamoDBIngestJobStatusStore

---

java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportJobDriver.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/BulkImportExecutor.java

Resolves #894 
Filepaths for storing jobs in S3 changed

Submitting two bulk import jobs with same id overwrites the old one #894

---

java/system-test/src/main/java/sleeper/systemtest/compaction/InvokeCompactionTaskCreation.java
java/system-test/src/main/java/sleeper/systemtest/compaction/InvokeCompactionTaskCreationUntilAllJobsStarted.java
scripts/test/common/testCompaction.sh

Issue 984 - Wait for all jobs to start in compaction performance test

---

.github/pull_request_template.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/1000
- We can see whether the link is made automatically based on this PR

Issue 1000 - Use "Resolves" in PR description to link to relevant issue

---

java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1004
- It only changes the minimum arguments, and I've tested the deploy & tearDown scripts work afterwards.

Issue 1004 - Fix minimum arguments in DeployNewInstance

---

scripts/Dockerfile
scripts/cli/builder/Dockerfile
scripts/cli/environment/Dockerfile

PR"
- Resolves https://github.com/gchq/sleeper/issues/970
- Tested with docker locally, lines now wrap as expected

Issue 970 - Escape non-readable characters in PS1 variable

---

NOTICES

PR"
- Resolves https://github.com/gchq/sleeper/issues/982
- Just updated NOTICES

Issue 982 - Update NOTICES

---

.github/scripts/planCliBuild.sh
.github/workflows/docker-cli-branch.yaml
.github/workflows/docker-cli-image.yaml
.github/workflows/docker-cli.yaml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1011
- The workflow worked in GitHub Actions, and will run regularly

Issue 1011 - Split CLI build workflow

---

java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1021
- Ran a bulkImportPerformance system test in AWS

Issue 1021 - Manage version of Okio

---

.github/ISSUE_TEMPLATE/bug.md
.github/pull_request_template.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/1039
- Template update

Issue 1039 - Fix spelling mistake in bug template

---

.github/workflows/chunk.yaml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1053
- Workflow change

Issue 1053 - Don't publish reports from a fork

---

java/clients/src/main/java/sleeper/clients/deploy/PopulateTableProperties.java
java/core/src/main/java/sleeper/core/util/PollWithRetries.java
java/ingest/ingest-batcher-core/src/main/java/sleeper/ingest/batcher/IngestBatcher.java
java/ingest/ingest-batcher-core/src/main/java/sleeper/ingest/batcher/IngestBatcherStore.java
java/ingest/ingest-batcher-core/src/test/java/sleeper/ingest/batcher/testutil/IngestBatcherStoreInMemory.java
java/ingest/ingest-batcher-core/src/test/java/sleeper/ingest/batcher/testutil/IngestBatcherStoreInMemoryTest.java
java/ingest/ingest-batcher-store/src/main/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStore.java
java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreIT.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/IngestBatcherDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/IngestByQueueDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/IngestSourceFilesContext.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/ResetProperties.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestParameters.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestClients.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestIngest.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestIngestBatcher.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SystemTestSourceFiles.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestBatcherIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestBatcherSystemIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/852
- IngestBatcherIT

Issue 852 - Set up ingest batcher system test in JUnit

---

java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/BulkImportStarterLambda.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateJobsLambda.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFilesRunner.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerLocalStackIT.java
java/configuration/src/main/java/sleeper/configuration/properties/PropertiesReloader.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesProvider.java
java/configuration/src/test/java/sleeper/configuration/properties/PropertiesReloaderIT.java
java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambda.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTask.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobRunner.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
java/query/src/main/java/sleeper/query/lambda/SqsQueryProcessorLambda.java
java/splitter/src/main/java/sleeper/splitter/SplitPartitionLambda.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1063

Issue 1063 - Property to force reload lambdas

---

java/clients/src/main/java/sleeper/clients/teardown/WaitForStackToDelete.java
java/clients/src/test/java/sleeper/clients/teardown/WaitForStackToDeleteIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1073
- WaitForStackToDeleteIT

Issue 1073 - Throw exception if delete failed in WaitForStackToDelete

---

docs/05-ingest.md
example/full/instance.properties
example/full/table.properties
java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/configuration/BulkImportPlatformSpec.java
java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/configuration/ConfigurationUtils.java
java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/configuration/EmrInstanceTypeConfig.java
java/bulk-import/bulk-import-common/src/test/java/sleeper/bulkimport/configuration/EmrInstanceTypeConfigTest.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceFleets.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/StateMachinePlatformExecutor.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
java/configuration/src/main/java/sleeper/configuration/Utils.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/NonPersistentEMRProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/PersistentEMRProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/validation/EmrInstanceArchitecture.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/1084
- EmrInstanceTypeConfigTest

Issue 1084 - Add properties for specifying EMR instance architecture

---

code-style/dependency-check-suppressions.xml
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1093
- Just dependency upgrades, will be covered by existing tests

Issue 1093 - Resolve vulnerabilities in Avro & OkHttp

---

java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1055

1055 partitions builder in reinitialise table it

---

java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/rdd/SleeperPartitionerTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1054

1054-PartitionsBuilder-in-SleeperPartitionerTest

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/TestResult.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/nightly/NightlyTestOutputFileSystemIT.java
scripts/test/nightly/runTests.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1111
- Nightly test script change only

Issue 1111 - Report Maven test exit code

---

docs/01-getting-started.md
docs/02-deployment-guide.md
docs/11-common-problems-and-their-solutions.md
java/clients/src/main/java/sleeper/clients/deploy/SyncJars.java
scripts/deploy/syncJars.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1119

Issue 1119 - Resolve documentation omissions

---

java/ingest/ingest-batcher-store/src/main/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStore.java
java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreIT.java
java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreTestBase.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/929
- n/a

Issue 929 - Improve reliability of DynamoDB batcher store tests

---

java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverIT.java
java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/dataframe/WriteParquetFilesIT.java
java/cdk/src/test/java/sleeper/cdk/UtilsTestHelper.java
java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
java/configuration/src/test/java/sleeper/configuration/properties/SleeperPropertiesTest.java
java/configuration/src/test/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinterTest.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestRecordsTestDataHelper.java
java/query/src/test/java/sleeper/query/executor/QueryExecutorIT.java
java/trino/src/test/java/sleeper/trino/testutils/PopulatedSleeperExternalResource.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1088
- SleeperPropertiesTest.ConvertEmptyString

Issue 1088 - Make empty string equivalent to unset value

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/InstanceDidNotDeployException.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1118
- System tests - ran manually with an invalid property which caused it to fail in the CDK, then didn't retry

Issue 1118 - Stop retrying deploying system test instance

---

scripts/test/nightly/crontab.example
scripts/test/nightly/updateAndRunTests.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1170
- Nightly test script changes

Issue 1170 - Update crontab example to upgrade CLI before running nightly tests

---

.github/pull_request_template.md
CONTRIBUTING.md
docs/09-dev-guide.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/1097
- Documentation update
- Updated `CONTRIBUTING.md`

Issue 1097 - Document updating NOTICES.md

---

NOTICES
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1183
- Just a dependency upgrade

Issue 1183 - Upgrade Apache Ivy

---

docs/05-ingest.md

- Resolves https://github.com/gchq/sleeper/issues/1126

Added documentation for EMR Serverless

---

java/ingest/ingest-batcher-store/src/main/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStore.java
java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreIT.java
java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/DynamoDBIngestBatcherStoreTestBase.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1167
- Updates DynamoDBIngestBatcherStoreIT

Issue 1167 - Control job assignment batch size for tests meeting and exceeding it

---

code-style/dependency-check-suppressions.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1205
- Dependency check suppression

Issue 1205 - Suppress vulnerability for Netty

---

java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStoreCreator.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/task/DynamoDBCompactionTaskStatusStoreCreator.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStoreCreator.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/task/DynamoDBIngestTaskStatusStoreCreator.java
java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStoreCreatorIT.java
java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/task/DynamoDBIngestTaskStatusStoreCreatorIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1141
- My PR adds the tearDown method to DynamoDBIngestJobStatusStoreCreator and DynamoDBIngestTaskStatusStoreCreator to include tearDown
- This PR also adds implementation into DynamoDBIngestJobStatusStoreCreatorIT and DynamoDBIngestTaskStatusStoreCreatorIT

Updated Ingest Job/Task status store to include tearDown

---

.github/config/chunks.yaml
.github/workflows/chunk-compaction.yaml
java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
java/compaction/compaction-core/pom.xml
java/compaction/compaction-job-execution/pom.xml
java/compaction/compaction-status-store/pom.xml
java/compaction/compaction-task-creation/pom.xml
java/compaction/compaction-task-creation/src/main/java/sleeper/compaction/taskcreation/InstanceDetails.java
java/compaction/compaction-task-creation/src/main/java/sleeper/compaction/taskcreation/RunTasks.java
java/compaction/compaction-task-creation/src/main/java/sleeper/compaction/taskcreation/RunTasksLambda.java
java/compaction/compaction-task-creation/src/main/java/sleeper/compaction/taskcreation/SafeTerminationLambda.java
java/compaction/compaction-task-creation/src/main/java/sleeper/compaction/taskcreation/Scaler.java
java/compaction/compaction-task-creation/src/test/java/sleeper/compaction/taskcreation/SafeTerminationTest.java
java/compaction/pom.xml
java/distribution/src/main/assembly/zip.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1213
- Just moving code around

Issue 1213 - Split out compaction-task-creation module

---

java/ingest/ingest-batcher-core/src/main/java/sleeper/ingest/batcher/IngestBatcher.java
java/ingest/ingest-batcher-job-creator/src/main/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambda.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1215
- Adding more logging, no tests needed

Issue 1215 - Improve ingest batcher logging

---

java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestBatcherStack.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
java/cdk/src/main/java/sleeper/cdk/stack/QueryStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrBulkImportStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrServerlessBulkImportStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/SystemDefinedInstanceProperty.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1214
- Adding new properties for future use

Issue 1214 - Create properties for queue ARNs

---

java/clients/src/main/java/sleeper/clients/util/cdk/InvokeCdkForInstance.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestDeploymentContext.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1232

Issue 1232 - Create generated directory when deploying SystemTestDeploymentContext

---

java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestBatcherStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrServerlessBulkImportStack.java
java/configuration/src/main/java/sleeper/configuration/properties/validation/BatchIngestMode.java
java/ingest/ingest-batcher-core/src/main/java/sleeper/ingest/batcher/IngestBatcher.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestBatcherIT.java

- [c] My PR addresses the following issues and references them in the PR title. For example, "Issue 1234 - My Sleeper
PR"
- Resolves https://github.com/gchq/sleeper/issues/1224
- [c] My PR adds the following tests __OR__ does not need testing for this extremely good reason:
- IngestBatcherIT
- [c] In case of new functionality, my PR adds documentation that describes how to use it, or I have linked to a
- [c] If I have added, removed, or updated any external dependencies used in the project, I have updated the

Issue 1224 - Add support for EMR Serverless to ingest batcher

---

.github/workflows/maven-full.yaml
java/distribution/pom.xml
scripts/build/build.sh

- Resolves https://github.com/gchq/sleeper/issues/1234
Run cd java && mvn clean install -Pquick -T 1C

Add dependencies to distribution module

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/ReportingContext.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/reports/SystemTestReporting.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/reports/SystemTestReports.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestBatcherIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonApiIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/ReportingExtension.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/ReportingExtensionTest.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/TestContextFactory.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1240
- ReportingExtensionTest

Issue 1240 - Tidy system test reports output

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/ReportingContext.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/reports/SystemTestReports.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/ReportingExtension.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1253
- Covered by nightly system tests

Issue 1253 - Call ReportingContext.startRecording in SleeperSystemTest.reset

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/CompactionReportsDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/IngestReportsDriver.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/reports/SystemTestReporting.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/reports/SystemTestReports.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1256
- Fixes existing tests

Issue 1256 - Fix system test reporting

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/CompactionDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/WaitForJobsDriver.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1261

Issue 1261 - Check compaction task types in driver

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/NightlyTestOutput.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/NightlyTestSummaryTable.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/NightlyTestUploader.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/nightly/NightlyTestOutputFileSystemIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1263

Issue 1263 - Add logging to NightlyTestOutput.uploadToS3

---

scripts/test/nightly/crontab.example

PR"
- Resolves https://github.com/gchq/sleeper/issues/1270
- Will run nightly

Issue 1270 - Run `docker system prune` in crontab.example

---

scripts/cli/runInDocker.sh
scripts/test/nightly/runTests.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1271
- Runs nightly

Issue 1271 - Fix nightly test script

---

java/clients/src/main/java/sleeper/clients/status/report/CompactionJobStatusReport.java
java/clients/src/main/java/sleeper/clients/status/report/IngestJobStatusReport.java
java/clients/src/main/java/sleeper/clients/status/report/job/query/AllJobsQuery.java
java/clients/src/main/java/sleeper/clients/status/report/job/query/DetailedJobsQuery.java
java/clients/src/main/java/sleeper/clients/status/report/job/query/JobQuery.java
java/clients/src/main/java/sleeper/clients/status/report/job/query/RangeJobsQuery.java
java/clients/src/main/java/sleeper/clients/status/report/job/query/RejectedJobsQuery.java
java/clients/src/main/java/sleeper/clients/status/report/job/query/UnfinishedJobsQuery.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/CompactionReportsDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/IngestReportsDriver.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1277
- Adding getters to interface that return constants in implementations

Issue 1277 - Pass query type from query selected in prompt to job status reports

---

scripts/test/nightly/crontab.example
scripts/test/nightly/runTests.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1272
- Nightly test script changes

Issue 1272 - Update performance tests to run every other day

---

java/clients/src/main/java/sleeper/clients/QueryClient.java
java/configuration/src/main/java/sleeper/configuration/utils/AwsV1ClientHelper.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/AsyncS3PartitionFileWriterFactory.java
java/parquet/src/main/java/sleeper/utils/HadoopConfigurationProvider.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataToDocker.java

…t for LocalStack
PR"
- Resolves https://github.com/gchq/sleeper/issues/1286
- Tested deploy, ingest, query, and tearDown manually

Issue 1286 - Allow deploying to LocalStack without local AWS credentials configured

---

java/clients/src/main/java/sleeper/clients/util/ShowPageIndexes.java
java/clients/src/test/java/sleeper/clients/util/ShowPageIndexesIT.java
java/clients/src/test/resources/util/showPageIndexes/multiplePages.txt
java/clients/src/test/resources/util/showPageIndexes/multipleRowGroups.txt
java/clients/src/test/resources/util/showPageIndexes/multipleRowKeyFields.txt
java/clients/src/test/resources/util/showPageIndexes/oneRowKeyField.txt
java/clients/src/test/resources/util/showPageIndexes/rowKeySortKeyAndValueFields.txt
java/parquet/pom.xml
scripts/utility/showPageIndexes.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1265
- ShowPageIndexesIT

Issue 1265 - Utility script to run ShowPageIndexes

---

NOTICES
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1305

Issue 1305 - Upgrade Testcontainers, manage version of commons-compress

---

scripts/test/nightly/crontab.example
scripts/test/nightly/runTests.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1295

Issue 1295 - Set nightly test name based on test type

---

NOTICES
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1315

Issue 1315 - Update Jetty

---

java/clients/src/main/java/sleeper/clients/admin/AdminClientPropertiesStore.java
java/clients/src/main/java/sleeper/clients/teardown/RemoveECRRepositories.java
java/clients/src/main/java/sleeper/clients/teardown/TearDownInstance.java
java/clients/src/test/java/sleeper/clients/admin/AdminClientPropertiesStoreIT.java
java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientITBase.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/TearDownMavenSystemTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1318
- AdminClientPropertiesStoreIT.CreateGeneratedDirectoryWhenMissing

Issue 1318 - Handle missing generated directory

---

java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportJobDriver.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/task/DynamoDBCompactionTaskStatusStore.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/task/DynamoDBIngestTaskStatusStore.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1292

Issue 1292 - Improve logging in reporting status stores

---

docs/01-getting-started.md
docs/10-deploy-to-localstack.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/1268
- Documentation changes

Issue 1268 - Mention LocalStack in Getting Started guide

---

java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/WriteToMemoryIngestJobStatusStore.java
java/system-test/system-test-drivers/pom.xml
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/WaitForJobsDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/WaitForJobsStatus.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/util/WaitForJobsStatusTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1321

Issue 1321 - Output count by status in system test WaitForJobsDriver

---

java/clients/src/main/java/sleeper/clients/AdminClient.java
java/clients/src/main/java/sleeper/clients/admin/AdminClientPropertiesStore.java
java/clients/src/main/java/sleeper/clients/admin/AdminClientStatusStoreFactory.java
java/clients/src/main/java/sleeper/clients/admin/AdminMainScreen.java
java/clients/src/main/java/sleeper/clients/admin/IngestBatcherReportScreen.java
java/clients/src/main/java/sleeper/clients/status/report/ingest/batcher/StandardIngestBatcherReporter.java
java/clients/src/test/java/sleeper/clients/admin/CompactionStatusReportScreenTest.java
java/clients/src/test/java/sleeper/clients/admin/IngestBatcherReportScreenTest.java
java/clients/src/test/java/sleeper/clients/admin/IngestStatusReportScreenTest.java
java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientMockStoreBase.java
java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientStatusStoreHolder.java
java/clients/src/test/java/sleeper/clients/admin/testutils/ExpectedAdminConsoleValues.java
java/clients/src/test/java/sleeper/clients/admin/testutils/RunAdminClient.java
java/clients/src/test/resources/reports/ingest/batcher/standard/all/largeAndDecimalFileSizes.txt
java/clients/src/test/resources/reports/ingest/batcher/standard/all/noFiles.txt
java/clients/src/test/resources/reports/ingest/batcher/standard/all/onePendingAndTwoBatchedFiles.txt
java/clients/src/test/resources/reports/ingest/batcher/standard/pending/multiplePendingFiles.txt
java/clients/src/test/resources/reports/ingest/batcher/standard/pending/noFiles.txt
java/ingest/ingest-batcher-core/src/main/java/sleeper/ingest/batcher/IngestBatcherStore.java
java/ingest/ingest-batcher-store/src/main/java/sleeper/ingest/batcher/store/IngestBatcherStoreFactory.java
java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/IngestBatcherStoreFactoryIT.java
java/ingest/ingest-batcher-store/src/test/java/sleeper/ingest/batcher/store/IngestBatcherStoreFactoryTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1282
- IngestBatcherReportScreenTest

Issue 1282 - Run ingest batcher report from admin client

---

java/clients/src/main/java/sleeper/clients/QueryClient.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1313
- Logging change

Issue 1313 - Report time correctly in QueryClient

---

python/src/sleeper/sleeper.py

PR"
- Resolves https://github.com/gchq/sleeper/issues/1325
- Tested manually and with PythonApiIT

Issue 1325 - Allocate unique ids by default in python API

---

NOTICES
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1371

Issue 1371 - Upgrade snappy-java

---

NOTICES
code-style/dependency-check-suppressions.xml
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1396
- Updating/suppressing dependencies

Issue 1396 - Resolve dependency check failures

---

java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
java/clients/src/test/resources/reports/filestatus/json/leafAndMiddleFile.json
java/clients/src/test/resources/reports/filestatus/json/oneActiveFilePerLeaf.json
java/clients/src/test/resources/reports/filestatus/standard/leafAndMiddleFile.txt
java/clients/src/test/resources/reports/filestatus/standard/oneActiveFilePerLeaf.txt
java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/strategy/impl/BasicCompactionStrategyTest.java
java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/strategy/impl/SizeRatioCompactionStrategyTest.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerLocalStackIT.java
java/core/src/main/java/sleeper/core/statestore/FileInfo.java
java/core/src/main/java/sleeper/core/statestore/FileInfoSerDe.java
java/core/src/test/java/sleeper/core/statestore/FileInfoFactory.java
java/core/src/test/java/sleeper/core/statestore/FileInfoSerDeTest.java
java/core/src/test/java/sleeper/core/statestore/FileInfoTestData.java
java/core/src/test/java/sleeper/core/statestore/inmemory/StateStoreTestBuilder.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/AsyncS3PartitionFileWriter.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/DirectPartitionFileWriter.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/PartitionFileWriterUtils.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsDynamoDBIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsFromIteratorDynamoDBIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsFromIteratorIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsIT.java
java/splitter/src/test/java/sleeper/splitter/SplitPartitionJobDefinitionSerDeTest.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoFormat.java
java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
java/trino/src/main/java/sleeper/trino/handle/SleeperPartitioningHandle.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1378

Issue 1378 - Remove min and max row key from FileInfo

---

java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateJobs.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/strategy/DelegatingCompactionStrategy.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/BasicLeafStrategy.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/CompactionUtils.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/SizeRatioLeafStrategy.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1333
- Only log lines have changed

Added logging of table name to compaction job creation classes

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/NightlyTestOutput.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/TestResult.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/nightly/NightlyTestOutputFileSystemIT.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/nightly/NightlyTestOutputS3IT.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/nightly/NightlyTestOutputTestHelper.java
scripts/test/nightly/runTests.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1409
- NightlyTestOutputFileSystemIT.ReadSiteFiles

Issue 1409 - Create maven site zip for multiple tests

---

java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrowIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrowRecordWriterAcceptingRecordListIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/TestFilesAndRecords.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1374
- Updating assertions in existing tests

Issue 1374 - Speed up assertions in ingest runner tests

---

java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/dataframe/WriteParquetFilesIT.java
java/cdk/src/test/java/sleeper/cdk/UtilsTestHelper.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/CompactionStatusStoreTestUtils.java
java/configuration/src/main/java/sleeper/configuration/Utils.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
java/configuration/src/test/java/sleeper/configuration/UtilsTest.java
java/configuration/src/test/java/sleeper/configuration/jars/ObjectFactoryIT.java
java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/testutils/IngestStatusStoreTestUtils.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestParameters.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/fixtures/SystemTestInstanceTest.java
scripts/test/nightly/runTests.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1426
- Utils.ValidateStrings

Issue 1426 - Validate instance ID is at most 20 characters

---

example/full/instance.properties
java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/IngestFactory.java
java/parquet/src/main/java/sleeper/utils/HadoopConfigurationProvider.java
java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java
java/statestore/src/main/java/sleeper/statestore/s3/S3PartitionStore.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataFiles.java
java/trino/src/main/java/sleeper/trino/remotesleeperconnection/HadoopConfigurationProviderForDeployedS3Instance.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/5

Issue 5 - Set S3 upload block size

---

code-style/dependency-check-suppressions.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1441
- Just a dependency check suppression

Issue 1441 - Suppress CVE for Zookeeper 3.6.3

---

java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJob.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJobValidationUtils.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobQueueConsumer.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobMessageHandlerTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1433
- IngestJobMessageHandlerTest.shouldReportValidationFailureIfFileIsNull

Issue 1433 - Add validation for ingest job having non-null files

---

code-style/dependency-check-suppressions.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1452
- Suppression only

Issue 1452 - Suppress dependency check failures

---

docs/05-ingest.md
example/basic/instance.properties
example/full/instance.properties
java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrStudioStack.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/890
- MyUnitTest

Adding CDK stack for EMR Studio

---

java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
java/cdk/src/main/java/sleeper/cdk/stack/ConfigBucketStack.java
java/cdk/src/main/java/sleeper/cdk/stack/CoreStacks.java
java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBStateStoreStack.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestBatcherStack.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestPermissionsStack.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestSourceBucketsStack.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
java/cdk/src/main/java/sleeper/cdk/stack/ManagedPoliciesStack.java
java/cdk/src/main/java/sleeper/cdk/stack/S3StateStoreStack.java
java/cdk/src/main/java/sleeper/cdk/stack/TableDataStack.java
java/cdk/src/main/java/sleeper/cdk/stack/TableIndexStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrServerlessBulkImportStack.java
java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestClusterStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1459

Issue 1459 - Use a managed policy for external systems to perform ingest

---

java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBStateStoreStack.java
java/cdk/src/main/java/sleeper/cdk/stack/S3StateStoreStack.java
java/clients/src/main/java/sleeper/clients/docker/DeployDockerInstance.java
java/clients/src/main/java/sleeper/clients/docker/TearDownDockerInstance.java
java/clients/src/main/java/sleeper/clients/docker/stack/TableDockerStack.java
java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoFormat.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBPartitionFormat.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBPartitionStore.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBStateStore.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBStateStoreCreator.java
java/statestore/src/main/java/sleeper/statestore/s3/S3RevisionUtils.java
java/statestore/src/main/java/sleeper/statestore/s3/S3StateStore.java
java/statestore/src/main/java/sleeper/statestore/s3/S3StateStoreCreator.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileInfoFormatTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1456

Issue 1456 - Reference table by ID in state stores

---

java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesStore.java
java/configuration/src/main/java/sleeper/configuration/table/index/DynamoDBTableIndex.java
java/configuration/src/test/java/sleeper/configuration/properties/table/S3TablePropertiesStoreIT.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesProviderTest.java
java/configuration/src/test/java/sleeper/configuration/table/index/DynamoDBTableIndexIT.java
java/core/src/main/java/sleeper/core/table/TableIndex.java
java/core/src/main/java/sleeper/core/table/TableNotFoundException.java
java/core/src/test/java/sleeper/core/table/InMemoryTableIndex.java
java/core/src/test/java/sleeper/core/table/InMemoryTableIndexTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1474
- InMemoryTableIndexTest changes
- DynamoDBTableIndexIT changes
- S3TablePropertiesStoreIT changes

Issue 1474 - Improve updating/deleting table index entries

---

code-style/dependency-check-suppressions.xml
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1481

Issue 1481 - Upgrade CDK dependencies

---

java/splitter/src/main/java/sleeper/splitter/FindPartitionsToSplit.java
java/splitter/src/main/java/sleeper/splitter/SplitPartitionJobCreator.java
java/splitter/src/main/java/sleeper/splitter/SplitPartitionJobDefinition.java
java/splitter/src/main/java/sleeper/splitter/SplitPartitionJobDefinitionSerDe.java
java/splitter/src/main/java/sleeper/splitter/SplitPartitionLambda.java
java/splitter/src/test/java/sleeper/splitter/FindPartitionsToSplitIT.java
java/splitter/src/test/java/sleeper/splitter/SplitPartitionJobDefinitionSerDeTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1461

Issue 1461 - Use table ID in partition splitting

---

java/athena/src/main/java/sleeper/athena/metadata/SleeperMetadataHandler.java
java/clients/src/main/java/sleeper/clients/QueryCommandLineClient.java
java/clients/src/test/java/sleeper/clients/status/update/AddTableIT.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateJobs.java
java/configuration/src/main/java/sleeper/configuration/properties/table/S3TableProperties.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperties.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesProvider.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesStore.java
java/configuration/src/main/java/sleeper/configuration/table/index/DynamoDBTableIdFormat.java
java/configuration/src/main/java/sleeper/configuration/table/index/DynamoDBTableIndex.java
java/configuration/src/test/java/sleeper/configuration/properties/table/InMemoryTableProperties.java
java/configuration/src/test/java/sleeper/configuration/properties/table/S3TablePropertiesStoreIT.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesProviderIT.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesProviderTest.java
java/configuration/src/test/java/sleeper/configuration/table/index/DynamoDBTableIndexIT.java
java/core/src/main/java/sleeper/core/table/TableAlreadyExistsException.java
java/core/src/main/java/sleeper/core/table/TableIdentity.java
java/core/src/main/java/sleeper/core/table/TableIndex.java
java/core/src/test/java/sleeper/core/table/InMemoryTableIndex.java
java/core/src/test/java/sleeper/core/table/InMemoryTableIndexTest.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollector.java
java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambda.java
java/ingest/ingest-batcher-submitter/src/test/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambdaIT.java
java/statestore/src/test/java/sleeper/statestore/FixedStateStoreProvider.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1479

Issue 1479 - Stop proxying table index methods in TablePropertiesProvider

---

java/clients/src/main/java/sleeper/clients/admin/CompactionStatusReportScreen.java
java/clients/src/main/java/sleeper/clients/admin/IngestStatusReportScreen.java
java/clients/src/main/java/sleeper/clients/status/report/CompactionJobStatusReport.java
java/clients/src/main/java/sleeper/clients/status/report/IngestJobStatusReport.java
java/clients/src/main/java/sleeper/clients/status/report/job/query/AllJobsQuery.java
java/clients/src/main/java/sleeper/clients/status/report/job/query/JobQuery.java
java/clients/src/main/java/sleeper/clients/status/report/job/query/JobQueryPrompt.java
java/clients/src/main/java/sleeper/clients/status/report/job/query/RangeJobsQuery.java
java/clients/src/main/java/sleeper/clients/status/report/job/query/UnfinishedJobsQuery.java
java/clients/src/test/java/sleeper/clients/status/report/job/query/JobQueryTestBase.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/CompactionJobStatusStoreInMemory.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/CompactionJobStatusStoreInMemoryTest.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStoreCreatorIT.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionJobStatusStoreTestBase.java
java/splitter/src/main/java/sleeper/splitter/FindPartitionsToSplit.java
java/splitter/src/main/java/sleeper/splitter/SplitPartitionJobCreator.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1484

Issue 1484 - Fix merge of TableIdentity rename

---

java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/dataframe/FileWritingIterator.java
java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/rdd/SingleFileWritingIterator.java
java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/dataframe/FileWritingIteratorIT.java
java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/rdd/SingleFileWritingIteratorIT.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/AsyncS3PartitionFileWriterFactory.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/DirectPartitionFileWriterFactory.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorCommonIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestCoordinatorFactory.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestCoordinatorTestParameters.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1477

Issue 1477 - Use table ID in ingest & bulk import output files

---

java/clients/src/main/java/sleeper/clients/teardown/TerminateEMRServerlessApplications.java
java/clients/src/test/java/sleeper/clients/teardown/ShutdownSystemProcessesIT.java
java/clients/src/test/java/sleeper/clients/testutil/WiremockEmrServerlessTestHelper.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1498
- Updates ShutdownSystemProcessesIT

Issue 1498 - Fix EMR Serverless tear down

---

code-style/intellij-inspection-profile.xml
docs/11-dev-guide.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/1496
- Just IDE settings

Issue 1496 - Add IntelliJ inspection profile settings

---

java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBIngestStatusStoreResources.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatusStore.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusFormat.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStoreCreator.java
java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/QueryInvalidIngestJobsIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1500
- Updated QueryInvalidIngestJobsIT

Issue 1500 - Index ingest status stores by table

---

java/ingest/ingest-core/src/main/java/sleeper/ingest/job/IngestJobMessageHandler.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobFinishedEvent.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStartedEvent.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobValidatedEvent.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusFormat.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1501

Issue 1501 - Remove table name from ingest status store

---

docs/01-getting-started.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/1508

Issue 1508 - Restructure getting started guide

---

java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
java/cdk/src/main/java/sleeper/cdk/stack/CoreStacks.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestSourceBucketsStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1512
- CDK changes

Issue 1512 - Avoid creating nested stack when ingest source buckets not defined

---

scripts/test/nightly/runTests.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1515
- Fixes nightly system tests

Issue 1515 - Fix DynamoDB state store package name in nightly tests

---

java/clients/src/main/java/sleeper/clients/deploy/DeployInstanceConfigurationFromTemplates.java
java/clients/src/test/java/sleeper/clients/deploy/DeployInstanceConfigurationIT.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperties.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1521
- Updated DeployInstanceConfigurationIT

Issue 1521 - Fix deployment using table properties template

---

java/clients/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1524
- Tested manually in AWS

Issue 1524 - Use ServicesResourceTransformer for clients module fat jar

---

java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFilesRunner.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobQueueConsumer.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1519

Issue 1519 - Stop ingest/compaction job keepalive on exception

---

scripts/cli/install.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1527
- Just install script

Issue 1527 - Fix install script temp path

---

scripts/cli/install.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1527
- Scripts

Issue 1527 - Fix install script temp directory

---

java/system-test/system-test-drivers/pom.xml
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceTablesDriver.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/SleeperInstanceTablesDriverIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1534
- SleeperInstanceTablesDriverIT

Issue 1534 - Fix deleting all tables when there are none in system tests

---

scripts/cli/environment/scripts/subcommands/connect.sh
scripts/cli/install.sh
scripts/cli/runInDocker.sh
scripts/utility/downloadConfig.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1538
- Only scripts, tested manually

Issue 1538 - Use a random temporary directory for scripts

---

java/clients/src/main/java/sleeper/clients/QueryClient.java
java/clients/src/main/java/sleeper/clients/QueryCommandLineClient.java
java/clients/src/test/java/sleeper/clients/QueryClientIT.java
java/clients/src/test/java/sleeper/clients/QueryClientTestConstants.java
java/query/src/test/java/sleeper/query/executor/QueryExecutorIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1403
- QueryClientIT

Issue 1403 - Use correct minimum by default in QueryCommandLineClient

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceTablesDriver.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1547
- Too difficult to reproduce the case where DynamoDB does not apply the deletion immediately

Issue 1547 - Wait for table index to empty in SleeperInstanceTablesDriver.deleteAll

---

.github/workflows/docker-cli-main.yaml
scripts/test/nightly/crontab.example
scripts/test/nightly/updateAndRunTests.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1565
- Updating scripts to run nightly system tests

Issue 1565 - Point nightly test scripts and CLI workflow at develop branch

---

scripts/test/nightly/updateAndRunTests.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1565
- Just a scripts fix

Issue 1565 - Fix checkout of develop branch for nightly tests

---

java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJob.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobFactory.java
java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/CompactionJobTest.java
java/compaction/compaction-job-execution/pom.xml
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFilesRunner.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesSplittingIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/testutils/CompactSortedFilesTestBase.java
java/configuration/src/main/java/sleeper/configuration/TableUtils.java
java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
java/core/src/main/java/sleeper/core/statestore/FileInfoStore.java
java/core/src/test/java/sleeper/core/partition/PartitionsBuilder.java
java/core/src/test/java/sleeper/core/statestore/FileInfoFactory.java
java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileInfoStore.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/AssertQuantiles.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestRecordsTestDataHelper.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1563
- Updated CompactSortedFilesSplittingIT

Issue 1563 - Copy files in splitting compactions for tests

---

java/query/src/main/java/sleeper/query/model/QuerySerDe.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/SQSQueryDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/SchemaLoaderFromInstanceContext.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1567
- Improved code for system tests

Issue 1567 - Improve logging and table properties loading for queries over many tables

---

java/core/src/test/java/sleeper/core/statestore/FileInfoFactory.java
java/query/src/main/java/sleeper/query/executor/QueryExecutor.java
java/query/src/main/java/sleeper/query/lambda/SqsQueryProcessor.java
java/query/src/main/java/sleeper/query/recordretrieval/LeafPartitionQueryExecutor.java
java/query/src/main/java/sleeper/query/recordretrieval/LeafPartitionRecordRetriever.java
java/query/src/main/java/sleeper/query/recordretrieval/LeafPartitionRecordRetrieverImpl.java
java/query/src/test/java/sleeper/query/executor/QueryExecutorTest.java
java/query/src/test/java/sleeper/query/recordretrieval/InMemoryLeafPartitionRecordRetriever.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1569
- Updated QueryExecutorTest

Issue 1569 - Unit test QueryExecutor

---

NOTICES
code-style/dependency-check-suppressions.xml
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1595

Issue 1595 - Fix dependency check issues w/bcprov & logback-classic

---

NOTICES
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1621

Issue 1621 - Upgrade Logback

---

java/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBUtils.java
java/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/LoadedItemsWithLimit.java
java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBUtilsPagingIT.java
java/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBUtilsPagingLimitIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1623
- DynamoDBUtilsPagingLimitIT

Issue 1623 - Utility for DynamoDB paging with a limit

---

java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1605
- Updating log line

Issue 1605 - Fix log line to use StateStore interface instead of implementation

---

scripts/test/nightly/runTests.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1639
- Updating scripts

Issue 1639 - Fix script failures when running nightly functional test suite

---

java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/strategy/DelegatingCompactionStrategy.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/BasicCompactionStrategy.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/strategy/impl/BasicLeafStrategy.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1601
- Updating documentation

Issue 1601 - Fix JavaDoc in BasicCompactionStrategy and related classes

---

java/core/src/main/java/sleeper/core/statestore/StateStoreException.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBPartitionStore.java
java/statestore/src/main/java/sleeper/statestore/s3/S3RevisionUtils.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1645

Issue 1645 - Catch state store exceptions more consistently

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/IngestSourceFilesDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceContext.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestInstanceConfiguration.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/SleeperSystemTest.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/sourcedata/SystemTestCluster.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestNoSourceBucketIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/fixtures/SystemTestInstanceTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1649
- IngestNoSourceBucketIT

Issue 1649 - System test for deploying without ingest source bucket set

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SleeperInstanceTablesDriver.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1656

Issue 1656 - Clear file reference counts table in system tests

---

java/core/src/main/java/sleeper/core/statestore/FileInfoSerDe.java
java/core/src/test/java/sleeper/core/statestore/FileInfoSerDeTest.java
java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfo.java
java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java
java/statestore/src/test/java/sleeper/statestore/s3/S3FileInfoStoreIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1606

Issue 1606 - Store reference counts in S3 state store

---

java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
java/core/src/main/java/sleeper/core/statestore/FileInfoStore.java
java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileInfoStore.java
java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileInfoStoreTest.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollector.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStore.java
java/statestore/src/main/java/sleeper/statestore/s3/S3FileInfoStore.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileInfoStoreIT.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
java/statestore/src/test/java/sleeper/statestore/s3/S3FileInfoStoreIT.java
java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1644
- shouldFailToDeleteActiveFileWhenAlsoDeletingReadyForGCFile in all FileInfoStore test classes

Issue 1644 - Bulk delete garbage collected files

---

java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollector.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1661
- GarbageCollectorIT
- GarbageCollectorS3IT

Issue 1661 - Handle IOExceptions and improve logging in GarbageCollector

---

java/clients/src/test/java/sleeper/clients/status/report/filestatus/FilesStatusReportTest.java
java/clients/src/test/java/sleeper/clients/status/report/filestatus/StandardFileStatusReporterRecordCountTest.java
java/clients/src/test/resources/reports/filestatus/json/splitFile.json
java/clients/src/test/resources/reports/filestatus/standard/splitFile.txt
java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateJobsTest.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesEmptyOutputIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesIteratorIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesLocalStackIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesReportingIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesRunnerLocalStackIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesSplittingIT.java
java/core/src/main/java/sleeper/core/statestore/SplitFileInfo.java
java/core/src/test/java/sleeper/core/statestore/FileInfoTest.java
java/core/src/test/java/sleeper/core/statestore/inmemory/StateStoreTestBuilder.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1659

Issue 1659 - Create references to source files when splitting

---

java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/SparkFileInfoRow.java
java/clients/src/test/java/sleeper/clients/status/report/filestatus/FilesStatusReportTest.java
java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/strategy/impl/BasicCompactionStrategyTest.java
java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/strategy/impl/SizeRatioCompactionStrategyTest.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
java/core/src/main/java/sleeper/core/statestore/FileInfo.java
java/core/src/main/java/sleeper/core/statestore/SplitFileInfo.java
java/core/src/test/java/sleeper/core/statestore/FileInfoFactory.java
java/core/src/test/java/sleeper/core/statestore/FileInfoTest.java
java/core/src/test/java/sleeper/core/statestore/FileInfoTestData.java
java/core/src/test/java/sleeper/core/statestore/inmemory/StateStoreTestBuilder.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/PartitionFileWriterUtils.java
java/splitter/src/test/java/sleeper/splitter/SplitPartitionJobDefinitionSerDeTest.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileInfoFormat.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileInfoFormatTest.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1667

Issue 1667 - Set new flags explicitly for file references

---

code-style/dependency-check-suppressions.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1686
- No code changes

Issue 1686 - Suppress vulnerability for Amazon Ion

---

java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionOutputFileNameFactory.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionOutputFileNameFactoryTest.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/CompactSortedFilesSplittingIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/jobexecution/testutils/CompactSortedFilesTestBase.java
java/core/src/main/java/sleeper/core/statestore/SplitFileReference.java
java/core/src/test/java/sleeper/core/statestore/FileReferenceTest.java
java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1665
- Removed tests for removed code

Issue 1665 - Remove code to split a file reference by copying the file

---

java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1688
- Just updates existing tests

Issue 1688 - Realign file store tests

---

java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/sourcedata/SystemTestCluster.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceIT.java

Currently running performance test
PR"
- Resolves https://github.com/gchq/sleeper/issues/1715
- Updating system tests

Issue 1715 - Use correct WaitForJobsDriver implementation in EmrBulkImportPerformanceIT

---

java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1725
- Only added logging

Issue 1725 - Added logging of time taken to updateS3Files method in S3FileReferenceStore

---

java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/jobexecution/CompactSortedFiles.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1674
- Add log message

Issue 1674 - Log filter ranges during compaction

---

java/clients/src/main/java/sleeper/clients/status/report/compaction/job/JsonCompactionJobStatusReporter.java
java/clients/src/main/java/sleeper/clients/status/report/compaction/task/JsonCompactionTaskStatusReporter.java
java/clients/src/main/java/sleeper/clients/status/report/filestatus/JsonFileStatusReporter.java
java/clients/src/main/java/sleeper/clients/status/report/filestatus/StandardFileStatusReporter.java
java/clients/src/main/java/sleeper/clients/status/report/ingest/batcher/JsonIngestBatcherReporter.java
java/clients/src/main/java/sleeper/clients/status/report/ingest/job/JsonIngestJobStatusReporter.java
java/clients/src/main/java/sleeper/clients/status/report/ingest/task/JsonIngestTaskStatusReporter.java
java/clients/src/main/java/sleeper/clients/status/report/query/JsonQueryTrackerReporter.java
java/clients/src/main/java/sleeper/clients/util/ClientsGsonConfig.java
java/core/src/main/java/sleeper/core/statestore/AllReferencesToAFile.java
java/core/src/main/java/sleeper/core/statestore/FileReference.java
java/core/src/main/java/sleeper/core/statestore/FileReferenceSerDe.java
java/core/src/main/java/sleeper/core/util/GsonConfig.java
java/core/src/test/java/sleeper/core/statestore/FileReferenceTest.java
java/core/src/test/java/sleeper/core/statestore/FilesReportTestHelper.java
java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStore.java
java/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBAttributes.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/ECSIngestTaskIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceFormat.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java
java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBStateStoreIT.java
java/statestore/src/test/java/sleeper/statestore/s3/S3StateStoreIT.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/json/TaskStatusJson.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/json/TasksJson.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/json/TasksSummaryJson.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/nightly/NightlyTestSummaryTable.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/WaitForJobsStatus.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1731

Issue 1731 - Align update time fields in FileReference and AllReferencesToAFile

---

NOTICES
java/cdk/src/main/java/sleeper/cdk/Utils.java
java/cdk/src/main/java/sleeper/cdk/stack/AthenaStack.java
java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestBatcherStack.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
java/cdk/src/main/java/sleeper/cdk/stack/PropertiesStack.java
java/cdk/src/main/java/sleeper/cdk/stack/QueryStack.java
java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
java/cdk/src/main/java/sleeper/cdk/stack/VpcStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
java/pom.xml
java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestPropertiesStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1723
- Updating CDK configuration

Issue 1723 - Replace deprecated log retention configuration

---

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1748
- Fixed CompactionIT

Issue 1748 - Fix compilation in CompactionIT

---

java/core/src/main/java/sleeper/core/util/LoggedDuration.java
java/statestore/src/main/java/sleeper/statestore/s3/S3StateStoreDataFile.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1758

Issue 1758 - Use LoggedDuration in S3StateStoreDataFile

---

java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestApp.java
java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestClusterStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1762
- Ran deployAll system test in AWS

Issue 1762 - Grant access to system test bucket in deployAll system test cluster

---

example/full/instance.properties
example/full/table.properties
java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
java/ingest/ingest-batcher-job-creator/src/test/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambdaIT.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/1764

Issue 1764 - Change default ingest batcher mode to EMR serverless

---

example/full/instance.properties
example/full/table.properties
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/strategy/DelegatingCompactionStrategy.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/1738

Issue 1738 - Update default compaction size

---

java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
java/configuration/src/test/java/sleeper/configuration/properties/SleeperPropertiesTest.java
java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestBucketStack.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataFiles.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1766
- Updated SleeperPropertiesTest

Issue 1766 - Add ingest source bucket to existing list in deployAll system tests

---

java/clients/src/main/java/sleeper/clients/docker/DeployDockerInstance.java
java/parquet/src/main/java/sleeper/io/parquet/utils/HadoopConfigurationProvider.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1775
- Tests already use the correct configuration

Issue 1775 - Use correct Hadoop configuration when deploying to LocalStack

---

java/system-test/system-test-configuration/src/test/java/sleeper/systemtest/configuration/SystemTestPropertiesTest.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomData.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataFiles.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataViaQueue.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1778

Issue 1778 - Fix generating data in system test cluster

---

java/core/src/main/java/sleeper/core/util/PollWithRetries.java
java/core/src/test/java/sleeper/core/util/PollWithRetriesTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1788

Issue 1788 - Use LoggedDuration in PollWithRetries

---

CHANGELOG.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/1773
- Documentation changes

Issue 1773 - Update changelog

---

java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/dsl/ingest/SystemTestIngestToStateStore.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1791
- Updated CompactionIT system test
- Ran in AWS

Issue 1791 - System test to split file from root partition

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/DeployNewTestInstance.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/SystemTestDeploymentContext.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1808

Issue 1808 - Upload system test image in SystemTestDeploymentContext

---

java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateJobs.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1516

Issue 1516 - Move CompactionJobStatusStore.jobCreated call before sending to SQS

---

java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateJobs.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1516
- Just a comment

Issue 1516 - Comment on CompactionJobStatusStore.jobCreated call

---

java/cdk/pom.xml
java/compaction/compaction-job-creation/pom.xml
java/parquet/pom.xml
java/query/query-runner/pom.xml
java/splitter/splitter-lambda/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1825

Issue 1825 - Remove SQS dependency from parquet module

---

NOTICES
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1837

Issue 1837 - Upgrade nimbus-jose-jwt

---

java/clients/src/main/java/sleeper/clients/admin/properties/AdminClientPropertiesStore.java
java/clients/src/test/java/sleeper/clients/admin/AdminClientIT.java
java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceIT.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesProvider.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesStore.java
java/configuration/src/test/java/sleeper/configuration/properties/PropertiesReloaderIT.java
java/configuration/src/test/java/sleeper/configuration/properties/table/S3TablePropertiesStoreIT.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesProviderIT.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesProviderTest.java
java/query/query-core/src/main/java/sleeper/query/model/QuerySerDe.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/GenerateRandomDataFiles.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataToDocker.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/metrics/AwsTableMetricsDriver.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1839
- Update existing tests

Issue 1839 - Make TablePropertiesStore throw exceptions in load methods

---

example/full/instance.properties
example/full/table.properties
java/athena/src/test/java/sleeper/athena/TestUtils.java
java/athena/src/test/java/sleeper/athena/metadata/AbstractMetadataHandlerIT.java
java/athena/src/test/java/sleeper/athena/metadata/IteratorApplyingMetadataHandlerIT.java
java/athena/src/test/java/sleeper/athena/record/AbstractRecordHandlerIT.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsFromIteratorIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/IngestRecordsIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorFileWritingStrategyIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrayListIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestCoordinatorFactory.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestCoordinatorTestHelper.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/ResultVerifier.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/TestIngestType.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/1822
- Added tests alongside existing ones for new file writing strategy

Issue 1822 - Update default ingest file writing strategy

---

java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBStateStoreStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1847

Issue 1847 - Grant access to file reference count table when reading active files

---

example/full/instance.properties
example/full/table.properties
java/athena/src/test/java/sleeper/athena/TestUtils.java
java/clients/src/test/java/sleeper/clients/QueryClientIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesRunnerLocalStackIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactSortedFilesTestBase.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/IngestProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
java/configuration/src/test/java/sleeper/configuration/properties/format/SleeperPropertiesPrettyPrinterTest.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/IngestFactory.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobQueueConsumerTestBase.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/IngestRecordsTestDataHelper.java
java/query/query-lambda/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
java/query/query-runner/src/test/java/sleeper/query/runner/recordretrieval/QueryExecutorIT.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngestType.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SleeperInstanceContext.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemoryTestInstance.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/1845

Issue 1845 - Add table properties for ingest record batch and file writer types

---

java/clients/src/main/java/sleeper/clients/status/update/DeleteTable.java
java/clients/src/main/java/sleeper/clients/status/update/ReinitialiseTable.java
java/clients/src/main/java/sleeper/clients/util/BucketUtils.java
java/clients/src/test/java/sleeper/clients/status/update/DeleteTableIT.java
java/clients/src/test/java/sleeper/clients/status/update/ReinitialiseTableIT.java
scripts/deploy/deleteTable.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1826
- DeleteTableIT

Issue 1826 - Add ability to delete a table

---

java/configuration/src/main/java/sleeper/configuration/deploy/DeployInstanceConfiguration.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SleeperSystemTest.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceContext.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/SleeperInstanceTablesTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/SystemTestParametersTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemoryTestInstance.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/SystemTestParametersTestHelper.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemorySleeperTablesDriver.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/fixtures/SystemTestInstanceTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1855
- Updated SleeperInstanceTablesTest

Issue 1855 - Derive system test table names

---

java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryQueryByQueueDriver.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1866

Issue 1866 - Synchronize sets in InMemoryQueryByQueueDriver

---

java/core/src/main/java/sleeper/core/statestore/AssignJobIdRequest.java
java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
java/core/src/main/java/sleeper/core/statestore/FileReferenceStore.java
java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStore.java
java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1859
- Updated InMemoryFileReferenceStoreTest to use new method signature

Issue 1859 - State store interface to assign job IDs to files for a batch of multiple jobs

---

NOTICES
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1873

Issue 1873 - Update commons-compress

---

java/clients/src/main/java/sleeper/clients/status/report/filestatus/FileStatusCollector.java
java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
java/core/src/main/java/sleeper/core/statestore/FileReferenceStore.java
java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStore.java
java/core/src/test/java/sleeper/core/statestore/inmemory/InMemoryFileReferenceStoreTest.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java
java/metrics/src/main/java/sleeper/metrics/TableMetrics.java
java/statestore/src/main/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStore.java
java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreDynamoSpecificIT.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1882

Issue 1882 - Rename method to get all files from state store

---

code-style/eclipse-style.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1884
- Just IDE settings

Issue 1884 - Update eclipse-style.xml

---

code-style/eclipse-codetemplates.xml
code-style/eclipse-templates.xml
docs/11-dev-guide.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/1886
- Just IDE configuration

Issue 1886 - Add Eclipse templates

---

java/system-test/system-test-dsl/pom.xml
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngest.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngestBatcher.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceContext.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/IngestSourceFilesContext.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/SystemTestSourceFiles.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/extension/SleeperSystemTestExtension.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/SystemTestIngestBatcherTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestBatcherDriver.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestByQueue.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1888
- SystemTestIngestBatcherTest

Issue 1888 - Fix filenames in ingest batcher system test

---

java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/IngestSourceFilesContext.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/MultipleTablesTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/sourcedata/SystemTestSourceFilesTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryDirectIngestDriver.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestByQueue.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1890
- Added MultipleTablesTest

Issue 1890 - Fix multiple tables system test finding source files

---

java/clients/src/main/java/sleeper/clients/status/update/CreateJobsClient.java
java/clients/src/test/java/sleeper/clients/status/update/AddTableIT.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesProvider.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesStore.java
java/configuration/src/test/java/sleeper/configuration/properties/table/InMemoryTablePropertiesStoreTest.java
java/configuration/src/test/java/sleeper/configuration/properties/table/S3TablePropertiesStoreIT.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesITBase.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesProviderIT.java
java/configuration/src/test/java/sleeper/configuration/properties/table/TablePropertiesProviderTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1877
- Removed some tests which are no longer valid in TablePropertiesProviderTest

Issue 1877- Take table ID as a string in properties provider & store

---

.vscode/settings.json

PR"
- Resolves https://github.com/gchq/sleeper/issues/1897
- IDE config

Issue 1897 - Set on-save actions for VS Code

---

.vscode/settings.json

PR"
- Resolves https://github.com/gchq/sleeper/issues/1902
- Just IDE config

Issue 1902 - Set Checkstyle version for VS Code

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/AwsIngestBatcherDriver.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1908
- Covered by system test IngestBatcherIT
- Will run in AWS against top of stack:
- https://github.com/gchq/sleeper/pull/1913

Issue 1908 - Fix batcher system test driver

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/python/PythonBulkImportDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/python/PythonIngestDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/IngestSourceFilesContext.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1910
- Covered by PythonIngestIT and PythonBulkImportIT
- Will run in AWS against top of stack:
- https://github.com/gchq/sleeper/pull/1913

Issue 1910 - Fix source file paths in Python drivers

---

java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/util/WaitForJobs.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/GarbageCollectionIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1912
- Updated GarbageCollectionIT
- Will run in AWS

Issue 1912 - Fix garbage collection system test

---

.vscode/templates.code-snippets

PR"
- Resolves https://github.com/gchq/sleeper/issues/1904
- Updating IDE config

Issue 1904 - Add VSCode code-snippets file

---

code-style/eclipse-style.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1923
- Just IDE config

Issue 1923 - Disable formatting line comments in IDE config

---

.vscode/templates.code-snippets

PR"
- Resolves https://github.com/gchq/sleeper/issues/1927
- IDE config

Issue 1927 - Add code snippets for JUnit tests

---

java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestDeploymentContext.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/extension/SleeperSystemTestExtension.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestExtension.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/testutil/AwsSleeperSystemTestExtension.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1926

Issue 1926 - Persist system test deployment context between test classes

---

docs/04-tables.md
docs/12-design.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/1899
- Updating documentation

Issue 1899 - Document table online/offline features

---

code-style/eclipse-style.xml
java/splitter/splitter-core/src/test/java/sleeper/splitter/SplitPartitionIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1941
- Just formatting & IDE configuration

Issue 1941 - Fix Eclipse/VS Code formatting configuration for array literals

---

example/full/instance.properties
java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/GarbageCollectionProperty.java
java/core/src/main/java/sleeper/core/table/InvokeForTableRequest.java
java/core/src/test/java/sleeper/core/table/InvokeForTableRequestTest.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollectorTriggerLambda.java
java/metrics/src/main/java/sleeper/metrics/TableMetricsTriggerLambda.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/1934
- Updated InvokeForTableRequestTest

Issue 1934 - Configure whether to invoke GC and table metrics for offline tables

---

java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemorySleeperTablesDriver.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1948

Issue 1948 - Synchronize InMemorySleeperTablesDriver.addTable

---

java/splitter/splitter-core/src/main/java/sleeper/splitter/SplitMultiDimensionalPartitionImpl.java
java/splitter/splitter-core/src/main/java/sleeper/splitter/SplitPartition.java
java/splitter/splitter-core/src/test/java/sleeper/splitter/SplitPartitionIT.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/partitioning/AwsPartitionSplittingDriver.java
java/system-test/system-test-dsl/pom.xml
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/partitioning/SystemTestPartitioning.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/partitioning/PartitionSplittingTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryDirectIngestDriver.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestByQueue.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryPartitionFileWriter.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryPartitionSplittingDriver.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemorySketchesStore.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1940
- PartitionSplittingTest

Issue 1940 - Add in memory test for partition splitting system test DSL

---

example/full/instance.properties
java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
java/clients/src/main/java/sleeper/clients/status/report/DeadLettersStatusReport.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/PartitionSplittingProperty.java
java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTest.java
java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/SqsSplitPartitionJobSender.java
java/splitter/splitter-lambda/src/test/java/sleeper/splitter/lambda/FindPartitionsToSplitIT.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/partitioning/AwsPartitionSplittingDriver.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PartitionSplittingIT.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/1945
- Renaming properties

Issue 1945 - Make partition splitting properties consistent

---

example/full/instance.properties
example/full/table.properties
java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
java/clients/src/main/java/sleeper/clients/status/update/CreateCompactionJobsClient.java
java/clients/src/main/java/sleeper/clients/status/update/CreateJobsClient.java
java/clients/src/main/java/sleeper/clients/status/update/TriggerGarbageCollectionClient.java
java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CreateCompactionJobsLambda.java
java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CreateCompactionJobsSQSLambda.java
java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CreateCompactionJobsTriggerLambda.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateCompactionJobs.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateCompactionJobsFailedException.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/FailedCreateCompactionJobsException.java
java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsIT.java
java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsTest.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
scripts/deploy/localstack/createCompactionJobs.sh
scripts/templates/instanceproperties.template
scripts/utility/compactAllFiles.sh
scripts/utility/compactFiles.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/1953
- Updated CreateCompactionJobsTest
- Updated CreateCompactionJobsIT

Issue 1953 - Queue-based lambda for compaction jobs

---

java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactSortedFiles.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactSortedFilesRunner.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionTask.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesEmptyOutputIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesIteratorIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesLocalStackIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesReportingIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesRunnerLocalStackIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactionTaskTest.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactSortedFilesTestBase.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1952

Issue 1952- Simplify CompactSortedFilesRunner

---

java/compaction/compaction-job-execution/docker/run.sh
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1967

Issue 1967 - Fix compaction task runner class name in Docker image

---

java/core/src/main/java/sleeper/core/record/process/RecordsProcessed.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1970
- Change only affects logging

Issue 1970 - Fix incorrect class name in RecordsProcessed toString method

---

java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/task/IngestTask.java
java/ingest/ingest-runner/docker/run.sh
java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTaskRunner.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobQueueConsumer.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/ECSIngestTaskRunnerIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1901
- Mostly renaming, covered by existing tests

Issue 1901 - Align IngestTask and CompactionTask

---

NOTICES
code-style/dependency-check-suppressions.xml
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/1975

Issue 1975 - Add dependency check suppression for xnio-api

---

java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactSortedFiles.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionTask.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/SqsCompactionQueueHandler.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesEmptyOutputIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesIteratorIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesLocalStackIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesReportingIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactionTaskTest.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1978
- Updated CompactionTaskTest

Issue 1978 - Fix compaction task termination

---

NOTICES

PR"
- Resolves https://github.com/gchq/sleeper/issues/1987
- Just updated NOTICES

Issue 1987 - Update NOTICES after Dependabot changes

---

docs/14-release-process.md
docs/16-roadmap.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/1921
- Only documentation

Issue 1921 - Update roadmap and release process

---

java/core/src/main/java/sleeper/core/partition/PartitionsFromSplitPoints.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2017
- Changes to logging

Issue 2017 - Improve debug logging in PartitionsFromSplitPoints

---

java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/PropertiesWriterLambdaIT.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/InstanceProperties.java
java/configuration/src/main/java/sleeper/configuration/properties/table/S3TableProperties.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2025
- Configuration files are viewable in S3 nicely

Issue 2025 - Rename properties files in config bucket

---

python/src/sleeper/sleeper.py

PR"
- Resolves https://github.com/gchq/sleeper/issues/2062
- Ran in AWS

Issue 2062 - Update location of instance properties in config bucket for Python

---

code-style/checkstyle-idea/checkstyle-suppressions.xml
code-style/checkstyle-suppressions.xml
java/ingest/ingest-batcher-job-creator/src/main/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambda.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/task/IngestTask.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/IngestFactory.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/IngestRecords.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/IngestRecordsFromIterator.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/IngestCoordinator.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/IngesterIntoPartitions.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/ParquetConfiguration.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/RecordIteratorWithSleeperIteratorApplied.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/AsyncS3PartitionFileWriter.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/DirectPartitionFileWriter.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/PartitionFileWriter.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/PartitionFileWriterUtils.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arraylist/ArrayListRecordBatch.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowIngestSupport.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowRecordBatch.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowRecordWriterAcceptingRecords.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowToRecordConversionUtils.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/RecordIteratorOrderedFromVectorSchemaRoot.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTaskRunner.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2070
- Just Javadoc

Issue 2070 - Ingest Javadoc summary fragments

---

NOTICES
code-style/dependency-check-suppressions.xml
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/2099

Issue 2099 - Suppress new Zookeeper vulnerability

---

.github/workflows/dependency-check.yaml

PR"
- Resolves https://github.com/gchq/sleeper/issues/2135
- Workflow change

Issue 2135 - Disable dependency checks

---

java/ingest/ingest-starter/pom.xml
java/ingest/ingest-starter/src/main/java/sleeper/ingest/starter/RunIngestTasksLambda.java

Reverts gchq/sleeper#2117
See issue:
- https://github.com/gchq/sleeper/issues/2133https://github.com/gchq/sleeper/issues/2133

Revert "Issue 2112 - Update spotbugs plugin version in ingest-starter module"

---

java/compaction/compaction-core/pom.xml
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJob.java

Reverts gchq/sleeper#2110
See issue:
- https://github.com/gchq/sleeper/issues/2133https://github.com/gchq/sleeper/issues/2133

Revert "Issue 2109 - Update spotbugs plugin version in compaction-core module "

---

java/statestore/pom.xml
java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
java/statestore/src/main/java/sleeper/statestore/s3/S3PartitionStore.java

Reverts gchq/sleeper#2108
See issue:
- https://github.com/gchq/sleeper/issues/2133https://github.com/gchq/sleeper/issues/2133

Revert "Issue 2107 - Update spotbugs plugin version in statestore module"

---

java/athena/src/main/java/sleeper/athena/record/SimpleRecordHandler.java
java/athena/src/test/java/sleeper/athena/FilterTranslatorIT.java
java/athena/src/test/java/sleeper/athena/record/SimpleRecordHandlerIT.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactSortedFiles.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactSortedFilesTestData.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arraylist/ArrayListRecordBatch.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobRunner.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/testutils/ResultVerifier.java
java/parquet/pom.xml
java/parquet/src/main/java/sleeper/io/parquet/record/ParquetReaderIterator.java
java/parquet/src/main/java/sleeper/io/parquet/record/RecordConverter.java
java/parquet/src/main/java/sleeper/io/parquet/record/SleeperRecordMaterializer.java
java/parquet/src/test/java/sleeper/io/parquet/record/ParquetReaderIteratorIT.java
java/query/query-lambda/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
java/query/query-runner/src/main/java/sleeper/query/runner/recordretrieval/RetrieveTask.java
java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
java/statestore/src/main/java/sleeper/statestore/s3/S3PartitionStore.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/ReadRecordsFromS3.java

Reverts gchq/sleeper#2104
See issue:
- https://github.com/gchq/sleeper/issues/2133https://github.com/gchq/sleeper/issues/2133

Revert "Issue 2103 - Update spotbugs plugin version in parquet module"

---

java/clients/src/main/java/sleeper/clients/QueryClient.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TablePropertiesProvider.java
java/query/query-runner/src/main/java/sleeper/query/runner/recordretrieval/QueryExecutor.java
java/statestore/src/main/java/sleeper/statestore/StateStoreProvider.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1863
- Just Javadoc

Issue 1863 - Add notes on thread safety in Javadoc

---

NOTICES
docs/14-release-process.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/1999
- Just NOTICES file

Issue 1999 - Update NOTICES after Dependabot changes

---

java/common-task/src/main/java/sleeper/task/common/RunCompactionTasks.java
java/common-task/src/test/java/sleeper/task/common/RunCompactionTasksTest.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2170
- Updated RunCompactionTasksTest

Issue 2170 - Fix compaction task starter logic

---

java/core/src/main/java/sleeper/core/statestore/transactionlog/StateStoreFiles.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/AssignJobIdsTransaction.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/ClearFilesTransaction.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/DeleteFilesTransaction.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/ReplaceFileReferencesTransaction.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/SplitFileReferencesTransaction.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/SplitPartitionTransaction.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStoreTest.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStoreTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2120
- TransactionLogXStoreTest
- TransactionLogXStoreIT

Issue 2120 - Transaction log state store operations

---

java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
java/statestore/src/main/java/sleeper/statestore/StateStoreFactory.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStore.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogStateStoreCreator.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogFileReferenceStoreIT.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogPartitionStoreIT.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreMultipleTablesIT.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreOneTableTestBase.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreTestBase.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2171
- TransactionLogFileReferenceStoreIT
- TransactionLogPartitionStoreIT
- TransactionLogStateStoreMultipleTablesIT

Issue 2171 - State store transaction log DynamoDB implementation

---

.github/workflows/dependency-check.yaml

PR"
- Resolves https://github.com/gchq/sleeper/issues/2137
- Just enabling dependency checks

Issue 2137 - Enable dependency check workflow

---

java/clients/src/main/java/sleeper/clients/QueryWebSocketClient.java
java/clients/src/test/java/sleeper/clients/QueryWebSocketClientTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2212

Issue 2212 - Fix running consecutive web socket queries

---

docs/01-getting-started.md
docs/13-system-tests.md
scripts/test/nightly/README.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/2255

Issue 2255 - Clarify nightly system tests docs

---

java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
java/common-task/src/main/java/sleeper/task/common/EC2Scaler.java
java/common-task/src/main/java/sleeper/task/common/RunCompactionTasks.java
java/configuration/src/main/java/sleeper/configuration/Requirements.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/CompactionDriver.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/SystemTestCompaction.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionOnEC2IT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionOnFargateIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1932
- CompactionOnEC2IT

Issue 1932 - System test for compactions on EC2

---

java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
java/cdk/src/main/java/sleeper/cdk/Utils.java
java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestBatcherStack.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
java/cdk/src/main/java/sleeper/cdk/stack/QueryQueueStack.java
java/cdk/src/main/java/sleeper/cdk/stack/QueryStack.java
java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrBulkImportStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrServerlessBulkImportStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/1955
- CDK deployment changes

Issue 1955 - Add SNS alarms for all dead letter queues

---

java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogEntry.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStore.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStore.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStoreTest.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStoreIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2250
- Updated InMemoryTransactionLogStoreTest
- Added tests in DynamoDBTransactionLogStoreIT

Issue 2250 - Track state store transaction number

---

java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
java/cdk/src/main/java/sleeper/cdk/stack/StateStoreStacks.java
java/cdk/src/main/java/sleeper/cdk/stack/TransactionLogStateStoreStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2121
- System tests passed in AWS

Issue 2121 - Deploy transaction log state store in CDK

---

NOTICES
code-style/dependency-check-suppressions.xml
java/build/pom.xml
java/pom.xml
java/trino/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/2283

Issue 2283 - Resolve dependency check failure for JGraphT

---

code-style/dependency-check-suppressions.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/2291

Issue 2291 - Update suppression for bcprov-jdk15on

---

.github/workflows/check-status.yaml
.github/workflows/chunk.yaml
.github/workflows/dependency-check.yaml
.github/workflows/maven-full.yaml

PR"
- Resolves https://github.com/gchq/sleeper/issues/2294
- GitHub Actions workflow changes

Issue 2294 - Daily cache for dependency check

---

java/cdk-environment/src/main/java/sleeper/environment/cdk/networking/NetworkingStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2284

Issue 2284 - Only deploy one NAT

---

.github/workflows/dependency-check.yaml

PR"
- Resolves https://github.com/gchq/sleeper/issues/2300
- Just workflow config

Issue 2300 - Always save cache in dependency check workflow

---

NOTICES
code-style/dependency-check-suppressions.xml
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/2301

Issue 2301 - Manage version of joda-time

---

java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/reporting/JobsFinishedStatistics.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2312
- Updates existing tests

Issue 2312 - Set expected range in performance tests

---

java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStateStoreTestBase.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStore.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2316

Issue 2316 - Add logs for transaction log state store

---

java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
java/core/src/main/java/sleeper/core/statestore/SplitFileReferences.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/AssignJobIdsTransaction.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2329

Issue 2329 - Avoid saving empty transactions

---

example/full/instance.properties
java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
java/clients/src/main/java/sleeper/clients/status/update/CreateCompactionJobsClient.java
java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CreateCompactionJobsLambda.java
java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CreateCompactionJobsTriggerLambda.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateCompactionJobs.java
java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsIT.java
java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsTest.java
java/configuration/src/main/java/sleeper/configuration/Utils.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/compaction/AwsCompactionDriver.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/2322
- Will run system tests in AWS

Issue 2322 - FIFO queues for table batching

---

java/system-test/system-test-dsl/pom.xml
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperInstance.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/InstanceAdminDriversWithRefresh.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceContext.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/InstanceAdminDriversWithRefreshTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2362
- Added InstanceAdminDriversWithRefreshTest

Issue 2362 - Regularly refresh instance admin drivers

---

example/full/instance.properties
java/cdk/src/main/java/sleeper/cdk/Utils.java
java/cdk/src/main/java/sleeper/cdk/stack/CoreStacks.java
java/cdk/src/main/java/sleeper/cdk/stack/ManagedPoliciesStack.java
java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/PartitionSplittingProperty.java
java/splitter/splitter-core/src/main/java/sleeper/splitter/FindPartitionsToSplit.java
java/splitter/splitter-core/src/test/java/sleeper/splitter/FindPartitionsToSplitTest.java
java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/FindPartitionsToSplitLambda.java
java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/FindPartitionsToSplitTriggerLambda.java
java/splitter/splitter-lambda/src/test/java/sleeper/splitter/lambda/FindPartitionsToSplitIT.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryPartitionSplittingDriver.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/2371

Issue 2371 - FIFO queue to find partitions to split

---

example/full/instance.properties
java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
java/metrics/src/main/java/sleeper/metrics/TableMetricsLambda.java
java/metrics/src/main/java/sleeper/metrics/TableMetricsTriggerLambda.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/2372

Issue 2372 - FIFO queue to publish table metrics

---

java/core/src/main/java/sleeper/core/schema/SchemaSerDe.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2317
- Just removing unused methods

Issue 2317 - Remove Base64 methods from SchemaSerDe

---

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/approvals/MultipleTablesIT.shouldCompactAndGCMultipleTables.approved.txt
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/approvals/MultipleTablesIT.shouldSplitPartitionsOfMultipleTables.approved.txt

PR"
- Resolves https://github.com/gchq/sleeper/issues/2386
- Just test assertions for MultipleTablesIT

Issue 2386 - Fix assertions for MultipleTablesIT

---

java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperty.java
java/system-test/system-test-configuration/src/test/java/sleeper/systemtest/configuration/SystemTestPropertiesTest.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/GenerateRandomDataFiles.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomData.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataToDocker.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomData.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceIT.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceIT.java
scripts/test/deployAll/system-test-instance.properties

PR"
- Resolves https://github.com/gchq/sleeper/issues/2389

Issue 2389 - Configure system test writers to run multiple ingests

---

java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
java/cdk/src/main/java/sleeper/cdk/stack/ConfigBucketStack.java
java/cdk/src/main/java/sleeper/cdk/stack/CoreStacks.java
java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBCompactionStatusStoreResources.java
java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBIngestStatusStoreResources.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestBatcherStack.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
java/cdk/src/main/java/sleeper/cdk/stack/InstanceAdminRoleStack.java
java/cdk/src/main/java/sleeper/cdk/stack/ManagedPoliciesStack.java
java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
java/cdk/src/main/java/sleeper/cdk/stack/QueryQueueStack.java
java/cdk/src/main/java/sleeper/cdk/stack/QueryStack.java
java/cdk/src/main/java/sleeper/cdk/stack/StateStoreStacks.java
java/cdk/src/main/java/sleeper/cdk/stack/TableDataStack.java
java/cdk/src/main/java/sleeper/cdk/stack/TableIndexStack.java
java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
java/cdk/src/main/java/sleeper/cdk/stack/WebSocketQueryStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/BulkImportBucketStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2393

Issue 2393 - Stop creating empty managed policies

---

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/EmrBulkImportPerformanceIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2415
- EmrBulkImportPerformanceIT

Issue 2415 - Increase maximum bulk import performance

---

java/cdk/src/main/java/sleeper/cdk/stack/ConfigBucketStack.java
java/cdk/src/main/java/sleeper/cdk/stack/CoreStacks.java
java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBIngestStatusStoreResources.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestBatcherStack.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
java/cdk/src/main/java/sleeper/cdk/stack/ManagedPoliciesStack.java
java/cdk/src/main/java/sleeper/cdk/stack/StateStoreStacks.java
java/cdk/src/main/java/sleeper/cdk/stack/TableDataStack.java
java/cdk/src/main/java/sleeper/cdk/stack/TableIndexStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/BulkImportBucketStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2413

Issue 2413 - Split ingest policy into direct and by queue

---

java/common/common-invoke-tables/src/main/java/sleeper/invoke/tables/InvokeForTables.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2424
- Logging change

Issue 2424 - Improve logging in table batching lambdas

---

java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/dataframe/FileWritingIteratorIT.java
java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/rdd/SingleFileWritingIteratorIT.java
java/clients/src/test/java/sleeper/clients/status/update/DeleteTableIT.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionOutputFileNameFactoryTest.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/strategy/impl/BasicCompactionStrategyTest.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/strategy/impl/SizeRatioCompactionStrategyTest.java
java/configuration/src/main/java/sleeper/configuration/TableUtils.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/partitionfilewriter/AsyncS3PartitionFileWriter.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorCommonIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorFileWritingStrategyIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrayListIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrowIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrowRecordWriterAcceptingRecordListIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2435

Issue 2435 - Move partition data folders into new folder in data bucket

---

java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
java/cdk/src/main/java/sleeper/cdk/stack/TransactionLogSnapshotCreationStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2432
- CDK changes

Issue 2432 - Disable concurrent execution of trigger lambdas

---

code-style/dependency-check-suppressions.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/2475
- Dependency check suppression update

Issue 2475 - Update dependency check suppression for bcprov-jdk15on

---

java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperTablesForTest.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceContext.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/partitioning/SystemTestPartitioning.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/partitioning/WaitForPartitionSplitting.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/MultipleTablesTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/MultipleTablesTest.shouldCompactAndGCMultipleTables.approved.txt
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/MultipleTablesTest.shouldSplitPartitionsOfMultipleTables.approved.txt
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/partitioning/WaitForPartitionSplittingTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2508
- Updated MultipleTablesTest, WaitForPartitionSplittingTest

Issue 2508 - Reproduce & fix parallelism in MultipleTablesTest

---

example/full/table.properties
java/athena/src/test/java/sleeper/athena/TestUtils.java
java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverIT.java
java/clients/src/main/java/sleeper/clients/docker/stack/TableDockerStack.java
java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceIT.java
java/clients/src/test/java/sleeper/clients/status/report/partitions/PartitionsStatusReportIT.java
java/clients/src/test/java/sleeper/clients/status/update/AddTableIT.java
java/clients/src/test/java/sleeper/clients/status/update/DeleteTableIT.java
java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsIT.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactSortedFiles.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactSortedFilesLocalStackIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorCommonIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorFileWritingStrategyIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/impl/IngestCoordinatorUsingDirectWriteBackedByArrayListIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobQueueConsumerTestBase.java
java/query/query-lambda/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
java/query/query-lambda/src/test/java/sleeper/query/lambda/WarmQueryExecutorLambdaIT.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogStateStoreCreator.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreTestBase.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperTablesDriver.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/AwsSleeperTablesDriverIT.java
java/trino/src/test/java/sleeper/trino/testutils/PopulatedSleeperExternalResource.java
scripts/templates/tableproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/2491

Issue 2491 - Make transaction log state store the default implementation

---

java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBStateStoreStack.java
java/cdk/src/main/java/sleeper/cdk/stack/S3StateStoreStack.java
java/cdk/src/main/java/sleeper/cdk/stack/StateStoreGrants.java
java/cdk/src/main/java/sleeper/cdk/stack/StateStoreStacks.java
java/cdk/src/main/java/sleeper/cdk/stack/TransactionLogStateStoreStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2521

Issue 2521 - Refactor state store grants

---

java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/FindPartitionsToSplitLambda.java
java/statestore-lambda/src/main/java/sleeper/statestore/TransactionLogSnapshotCreationLambda.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2504

Issue 2504 - Return batch item failures in snapshot creation & find splits

---

java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStore.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStoreTest.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2526

Issue 2526 - Handle unexpected failure adding transaction

---

scripts/test/maven/runTests.sh

Add a missing comma which stops the script from running.
PR"
- Resolves https://github.com/gchq/sleeper/issues/2542
- MyUnitTest

Added missing " to runTests.sh

---

java/clients/src/main/java/sleeper/clients/status/report/QueryTrackerReport.java
java/clients/src/main/java/sleeper/clients/status/report/query/TrackerQueryPrompt.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2549
- Changes to class only called by command line script

Issue 2549 - Fix unnecessary prompting in QueryTrackerReport

---

java/trino/src/main/java/sleeper/trino/remotesleeperconnection/HadoopConfigurationProviderForDeployedS3Instance.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2567

Issue 2567 - Add S3A file system implementation to Trino Hadoop configuration

---

java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotMetadataStoreIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2572
- Renaming class

Issue 2572 - Rename DynamoDBTransactionLogSnapshotStoreIT

---

example/full/instance.properties
java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/2431

Issue 2431 - Make max receive count for compaction jobs configurable

---

java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrBulkImportStack.java

Add missing AddTags permission to allow deployment of EMR on EC2 bulk import jobs 

---

java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2286

Issue 2286 - Rename remaining queues for consistency

---

java/statestore/src/main/java/sleeper/statestore/ArrowFormatUtils.java
java/statestore/src/main/java/sleeper/statestore/StateStoreFilesArrowFormat.java
java/statestore/src/main/java/sleeper/statestore/StateStorePartitionsArrowFormat.java
java/statestore/src/test/java/sleeper/statestore/StateStorePartitionsArrowFormatTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2601
- StateStorePartitionsArrowFormatTest

Issue 2601 - State store partitions Arrow format

---

NOTICES
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/2613

Issue 2613 - Manage version of Aircompressor

---

java/clients/src/test/java/sleeper/clients/status/report/compaction/job/CompactionJobStatusReporterTestBase.java
java/clients/src/test/resources/reports/compaction/job/json/mixedJobs.json
java/clients/src/test/resources/reports/compaction/job/standard/all/mixedJobs.txt
java/clients/src/test/resources/reports/compaction/job/standard/detailed/mixedJobs.txt
java/clients/src/test/resources/reports/compaction/job/standard/range/mixedJobs.txt
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusTestData.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStore.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStoreTest.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionTask.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactionTaskCommitTest.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/CompactionTaskTestBase.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusFormat.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobUpdatesIT.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionJobStatusStoreTestBase.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2411
- Updated tests for status store
- InMemoryCompactionJobStatusStoreTest
- StoreCompactionJobUpdatesIT
- Updated CompactionTaskCommitTest to report failure from task
- Added failed job to reporting test data

Issue 2411 - Compaction failed status update

---

java/clients/src/main/java/sleeper/clients/status/report/job/StandardProcessRunReporter.java
java/clients/src/test/java/sleeper/clients/status/report/ingest/job/IngestJobStatusReporterTestData.java
java/clients/src/test/resources/reports/compaction/job/standard/detailed/mixedJobs.txt
java/clients/src/test/resources/reports/ingest/job/json/mixedJobs.json
java/clients/src/test/resources/reports/ingest/job/standard/detailed/mixedJobs.txt

PR"
- Resolves https://github.com/gchq/sleeper/issues/2622
- Updated existing test assertions

Issue 2622 - Show reasons a job run failed

---

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2705
- Updated CompactionPerformanceIT

Issue 2705 - Reduce expected Fargate compaction performance

---

java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitter.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/commit/IngestAddFilesCommitRequest.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/commit/IngestAddFilesCommitRequestSerDe.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/commit/IngestAddFilesCommitRequestSerDeTest.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/commit/IngestAddFilesCommitRequestSerDeTest.shouldSerialiseIngestJobCommitRequestWithNoJob.approved.txt
java/statestore-commit-lambda/src/main/java/sleeper/committer/lambda/StateStoreCommitterLambda.java
java/statestore-commit/pom.xml
java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitRequest.java
java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitter.java
java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitRequestDeserialiserTest.java
java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitterTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2692
- StateStoreCommitterTest

Issue 2692 - Support ingest commits in state store commit lambda

---

java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/task/DynamoDBCompactionTaskStatusStore.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/task/DynamoDBIngestTaskStatusStore.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2639
- Adding logging

Issue 2639 - Log status store update times

---

java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportJobDriver.java
java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2694
- Updated BulkImportDriverTest

Issue 2694 - Report bulk import failure in driver

---

java/build/src/main/java/sleeper/build/chunks/ProjectChunks.java
java/build/src/main/java/sleeper/build/chunks/ProjectChunksValidationException.java
java/build/src/main/java/sleeper/build/chunks/ValidateProjectChunks.java
java/build/src/main/java/sleeper/build/github/actions/WorkflowTriggerPathsDiff.java
java/build/src/test/java/sleeper/build/chunks/ProjectChunksValidateModulesInChunksTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2659
- Reporting on these validation failures is not currently tested, while the actual validation is already tested

Issue 2659 - Change message for validate chunks error

---

java/core/src/test/java/sleeper/core/statestore/AllReferencesToAFileTestHelper.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobAddedFilesEvent.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobAddedFilesStatus.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStartedEvent.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatusStore.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/InMemoryIngestJobStatusStore.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/InMemoryIngestJobStatusStoreTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2729
- Updated InMemoryIngestJobStatusStoreTest

Issue 2729 - Model ingest add files status update

---

java/clients/src/main/java/sleeper/clients/status/report/compaction/job/JsonCompactionJobStatusReporter.java
java/clients/src/main/java/sleeper/clients/status/report/ingest/job/JsonIngestJobStatusReporter.java
java/clients/src/main/java/sleeper/clients/status/report/ingest/job/StandardIngestJobStatusReporter.java
java/clients/src/main/java/sleeper/clients/status/report/job/JsonProcessRunReporter.java
java/clients/src/test/resources/reports/compaction/job/json/jobWithMultipleRuns.json
java/clients/src/test/resources/reports/compaction/job/json/jobsWithLargeAndDecimalStatistics.json
java/clients/src/test/resources/reports/compaction/job/json/mixedJobs.json
java/clients/src/test/resources/reports/compaction/job/json/mixedUnfinishedJobs.json
java/clients/src/test/resources/reports/ingest/job/json/bulkImport/acceptedJob.json
java/clients/src/test/resources/reports/ingest/job/json/bulkImport/acceptedJobWhichStarted.json
java/clients/src/test/resources/reports/ingest/job/json/bulkImport/rejectedJob.json
java/clients/src/test/resources/reports/ingest/job/json/jobWithMultipleRuns.json
java/clients/src/test/resources/reports/ingest/job/json/jobsWithLargeAndDecimalStatistics.json
java/clients/src/test/resources/reports/ingest/job/json/mixedJobs.json
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobFinishedEvent.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobFinishedStatus.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatus.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatusType.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobUpdateType.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/InMemoryIngestJobStatusStore.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/InMemoryIngestJobStatusStoreTest.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusInPeriodTest.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusTest.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusTestHelper.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusFormat.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/util/WaitForJobsStatusTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2731
- Updated InMemoryIngestJobStatusStoreTest
- Updated IngestJobStatusTest

Issue 2731 - Model ingest status to commit when all files are added

---

java/common/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBAttributes.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusInPeriodTest.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusTest.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusTestHelper.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusFormat.java
java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java
java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/StoreIngestJobRunIdIT.java
java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/job/StoreIngestJobUpdatesIT.java
java/ingest/ingest-status-store/src/test/java/sleeper/ingest/status/store/testutils/DynamoDBIngestJobStatusStoreTestBase.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2723
- Update StoreIngestJobUpdatesIT, StoreIngestJobRunIdIT

Issue 2723 - Store ingest add files status updates in DynamoDB

---

java/ingest/ingest-core/src/main/java/sleeper/ingest/task/IngestTask.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/task/IngestTaskTest.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/ECSIngestTaskRunner.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2724
- Updated IngestTaskTest

Issue 2724 - Set job run ID in IngestTask

---

example/full/instance.properties
java/configuration/src/main/java/sleeper/configuration/properties/instance/AthenaProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/GarbageCollectionProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/IngestProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/PartitionSplittingProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/QueryProperty.java
java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperty.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/2485

Issue 2485 - Note units in memory properties

---

docs/01-getting-started.md
docs/13-system-tests.md
java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/DeployNewTestInstance.java
scripts/deploy/buildAndDeploy.sh
scripts/deploy/deployNew.sh
scripts/test/deploy.sh
scripts/test/deployAll/buildDeployTest.sh
scripts/test/deployAll/deployTest.sh
scripts/test/maven/buildDeploy.sh
scripts/test/maven/buildDeployTest.sh
scripts/test/maven/deploy.sh
scripts/test/maven/deployTest.sh
scripts/test/maven/performanceTest.sh
scripts/test/maven/runTests.sh
scripts/test/nightly/runTests.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/2430
- Script usage message changes

Issue 2430 - Change subnet usage message to csv-list-of-subnets

---

example/full/instance.properties
example/full/table.properties
java/bulk-import/bulk-import-runner/pom.xml
java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportJobDriver.java
java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverIT.java
java/bulk-import/bulk-import-runner/src/test/java/sleeper/bulkimport/job/runner/BulkImportJobDriverTest.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusTestHelper.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/2647
- Updated BulkImportJobDriverTest, BulkImportJobDriverIT

Issue 2647 - Async commit in bulk import

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperTablesDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/DirectQueryDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/SQSQueryDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/sourcedata/AwsIngestSourceFilesDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/ReadRecordsFromS3.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2425

Issue 2425 - Handle Hadoop configuration in system test clients

---

scripts/utility/compactAllFiles.sh
scripts/utility/compactFiles.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/2759
- Script changes, tested in AWS

Issue 2759 - Set missing access flags in compact files scripts

---

java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotMetadataStore.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogSnapshotDeleter.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogTransactionDeleter.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogSnapshotMetadataStoreIT.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogTransactionDeleterTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2755
- Updated DynamoDBTransactionLogSnapshotMetadataStoreIT

Issue 2755 - Find latest snapshots with min age

---

java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
java/cdk/src/main/java/sleeper/cdk/stack/CompactionStatusStoreResources.java
java/cdk/src/main/java/sleeper/cdk/stack/CompactionStatusStoreStack.java
java/cdk/src/main/java/sleeper/cdk/stack/CoreStacks.java
java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBCompactionStatusStoreResources.java
java/cdk/src/main/java/sleeper/cdk/stack/DynamoDBIngestStatusStoreResources.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestStack.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestStatusStoreResources.java
java/cdk/src/main/java/sleeper/cdk/stack/IngestStatusStoreStack.java
java/cdk/src/main/java/sleeper/cdk/stack/ManagedPoliciesStack.java
java/cdk/src/main/java/sleeper/cdk/stack/StateStoreCommitterStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrBulkImportStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EmrServerlessBulkImportStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/PersistentEmrBulkImportStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2769
- Ran quick system test suite in AWS

Issue 2769 - Fix permissions for async state store commits

---

example/full/instance.properties
example/full/table.properties
java/clients/src/main/java/sleeper/clients/status/report/compaction/job/JsonCompactionJobStatusReporter.java
java/clients/src/main/java/sleeper/clients/status/report/compaction/job/StandardCompactionJobStatusReporter.java
java/clients/src/main/java/sleeper/clients/status/report/ingest/job/StandardIngestJobStatusReporter.java
java/clients/src/test/resources/reports/compaction/job/json/jobWithMultipleRuns.json
java/clients/src/test/resources/reports/compaction/job/json/jobsWithLargeAndDecimalStatistics.json
java/clients/src/test/resources/reports/compaction/job/json/mixedJobs.json
java/clients/src/test/resources/reports/compaction/job/json/mixedUnfinishedJobs.json
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStatus.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStatusType.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobUpdateType.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusFurthestStatusTest.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusInPeriodTest.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
java/core/src/main/java/sleeper/core/record/process/status/ProcessRuns.java
java/core/src/main/java/sleeper/core/record/process/status/TimeWindowQuery.java
java/core/src/test/java/sleeper/core/record/process/status/ProcessRunsRecordsOutOfOrderTest.java
java/core/src/test/java/sleeper/core/record/process/status/ProcessRunsTest.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatus.java
java/ingest/ingest-core/src/main/java/sleeper/ingest/job/status/IngestJobStatusType.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/InMemoryIngestJobStatusStore.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusInPeriodTest.java
java/ingest/ingest-core/src/test/java/sleeper/ingest/job/status/IngestJobStatusTest.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/util/WaitForJobsStatus.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/util/WaitForJobsStatusTest.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/2714
- Updated WaitForJobsStatusTest to use new status types in system tests
- Ran quick system test suite and parallel compactions test

Issue 2714 - Async commit by default for ingest

---

.github/workflows/dependency-check.yaml

PR"
- Resolves https://github.com/gchq/sleeper/issues/2781
- Just disabling a workflow

Issue 2781 - Temporarily disable dependency checks

---

java/clients/src/test/java/sleeper/clients/admin/CompactionStatusReportScreenTest.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitter.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobFailedEvent.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobFinishedEvent.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStartedEvent.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/job/commit/CompactionJobCommitterTestBase.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStore.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStoreTest.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/CompactionTask.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusFormat.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByIdIT.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByPeriodIT.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusByTaskIdIT.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/QueryCompactionJobStatusUnfinishedIT.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobExpiryIT.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobUpdatesIT.java
java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitterTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/util/WaitForJobsStatusTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2777
- Updated all usages of the status updates

Issue 2777 - Introduce compaction job status update events

---

java/configuration/src/main/java/sleeper/configuration/properties/SleeperProperties.java
java/configuration/src/test/java/sleeper/configuration/properties/SleeperPropertiesTest.java
java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestBucketStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2797
- Updated SleeperPropertiesTest

Issue 2797 - Only add system test bucket to source buckets if missing

---

shell.nix

PR"
- Resolves https://github.com/gchq/sleeper/issues/2803
- Manually ran example Python scripts in Nix

Issue 2803 - Set Python packages in shell.nix

---

java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2793
- Updated IngestJobRunnerIT

Issue 2793 - Remove duplication between ingest job and coordinator tests

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/TearDownMavenSystemTest.java
scripts/test/maven/tearDown.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/2816

Issue 2816 - Improve scaling of TearDownMavenSystemTest

---

java/cdk-environment/src/main/resources/cloud-init.sh
scripts/cli/environment/Dockerfile
scripts/cli/environment/scripts/subcommands/adduser.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/2683
- https://github.com/gchq/sleeper/issues/2819

Issue 2683 - Install Nix in cdk-environment EC2

---

java/core/src/main/java/sleeper/core/record/process/status/ProcessRun.java
java/core/src/test/java/sleeper/core/record/process/status/ProcessRunsTest.java
java/core/src/test/java/sleeper/core/record/process/status/ProcessStatusUpdateTestHelper.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2814
- Updated ProcessRunsTest

Issue 2814 - Report on compactions that fail before they start

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2809
- Testing in AWS

Issue 2809 - Build a new Hadoop configuration for each operation

---

.devcontainer/devcontainer.json
.vscode/settings.json

PR"
- Resolves https://github.com/gchq/sleeper/issues/2842
- Tested manually in VS Code

Issue 2842 - Add Checkstyle extension to dev container

---

java/clients/src/main/java/sleeper/clients/status/report/compaction/job/StandardCompactionJobStatusReporter.java
java/clients/src/test/resources/reports/compaction/job/json/mixedJobs.json
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobCommittedEvent.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobCommittedStatus.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusTestData.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskCommitTest.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStore.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStoreTest.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusFormat.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobRunIdIT.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobUpdatesIT.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionJobStatusStoreTestBase.java
java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitter.java
java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitterTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2840

Issue 2840 - Add commit time to commit status update

---

java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2849

Issue 2849 - Use CDK native functionality for lambda termination policy.

---

example/full/instance.properties
java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java
java/common/common-task/src/main/java/sleeper/task/common/RunCompactionTasks.java
java/common/common-task/src/main/java/sleeper/task/common/RunECSTasks.java
java/common/common-task/src/main/java/sleeper/task/common/RunIngestTasks.java
java/configuration/src/main/java/sleeper/configuration/Utils.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CommonProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/validation/CompactionECSLaunchType.java
java/configuration/src/test/java/sleeper/configuration/UtilsTest.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/RunWriteRandomDataTaskOnECS.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/2805
- Updated UtilsTest (new validation predicate)

Issue 2805 - Specify security groups to use for ECS tasks

---

docs/01-getting-started.md
docs/02-deployment-guide.md
docs/11-dev-guide.md
scripts/cli/runInDocker.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/2847

Issue 2847 - Clarify building from source in documentation

---

java/common/common-task/src/main/java/sleeper/task/common/RunCompactionTasks.java
java/common/common-task/src/test/java/sleeper/task/common/RunCompactionTasksTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2853

Issue 2853 - EC2 doesn't scale in when no tasks are running

---

.devcontainer/devcontainer.json

PR"
- Resolves https://github.com/gchq/sleeper/issues/2868
- Tested manually in IDE

Issue 2868 - Mount local Maven repository to dev container

---

java/clients/src/main/java/sleeper/clients/status/report/compaction/job/StandardCompactionJobStatusReporter.java
java/clients/src/main/java/sleeper/clients/status/report/job/DelayStatistics.java
java/clients/src/test/java/sleeper/clients/status/report/job/DelayStatisticsTest.java
java/clients/src/test/resources/reports/compaction/job/standard/all/jobWithMultipleRuns.txt
java/clients/src/test/resources/reports/compaction/job/standard/all/jobsWithLargeAndDecimalStatistics.txt
java/clients/src/test/resources/reports/compaction/job/standard/all/mixedJobs.txt
java/clients/src/test/resources/reports/compaction/job/standard/range/mixedJobs.txt

PR"
- Resolves https://github.com/gchq/sleeper/issues/2851
- DelayStatisticsTest

Issue 2851 - Summary for compaction commit delays in reports

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/TearDownMavenSystemTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2885

Issue 2885 - Log when TearDownMavenSystemTest is complete

---

.devcontainer/devcontainer.json

PR"
- Resolves https://github.com/gchq/sleeper/issues/2890

Issue 2890 - Mount SSH configuration to dev container

---

scripts/cli/runInDocker.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/2892

Issue 2892 - Create a temporary directory for CLI container ID

---

java/clients/src/main/java/sleeper/clients/teardown/TearDownInstance.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/TearDownMavenSystemTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2909

Issue 2909 - Stop system processes before deleting stacks in TearDownMavenSystemTest

---

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/ParallelCompactionsIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2914
- Updated ParallelCompactionsIT

Issue 2914 - Allow a task with no jobs in parallel compactions system test

---

java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataToDocker.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataDirect.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2874

Issue 2874 - Apply async commit property in WriteRandomDataDirect

---

java/ingest/ingest-runner/src/main/java/sleeper/ingest/job/IngestJobRunner.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2922

Issue 2922 - Close input iterator in IngestJobRunner

---

example/full/instance.properties
example/full/table.properties
java/configuration/src/main/java/sleeper/configuration/properties/instance/DefaultProperty.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobQueueConsumerTestBase.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/job/IngestJobRunnerIT.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemoryTestInstance.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/2953

Issue 2953 - Commit ingest job asynchronously by default

---

NOTICES
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/2959

Issue 2959 - Manage version of dnsjava

---

java/clients/src/test/resources/util/showPageIndexes/v1/multiplePages.txt
java/clients/src/test/resources/util/showPageIndexes/v1/multipleRowGroups.txt
java/clients/src/test/resources/util/showPageIndexes/v1/multipleRowKeyFields.txt
java/clients/src/test/resources/util/showPageIndexes/v1/oneRowKeyField.txt
java/clients/src/test/resources/util/showPageIndexes/v1/rowKeySortKeyAndValueFields.txt
java/clients/src/test/resources/util/showPageIndexes/v2/multiplePages.txt
java/clients/src/test/resources/util/showPageIndexes/v2/multipleRowGroups.txt
java/clients/src/test/resources/util/showPageIndexes/v2/multipleRowKeyFields.txt
java/clients/src/test/resources/util/showPageIndexes/v2/oneRowKeyField.txt
java/clients/src/test/resources/util/showPageIndexes/v2/rowKeySortKeyAndValueFields.txt
java/pom.xml

- Resolves https://github.com/gchq/sleeper/issues/2493
- Testing is adjusting datasets to align with better compression of new package version. Key file: ShowPageIndexesIT.java
Unable to edit dependbot (part of ticket requirement as don't appear to have access to section)

Update version of parquet and assoicated test data

---

java/ingest/ingest-status-store/src/main/java/sleeper/ingest/status/store/job/DynamoDBIngestJobStatusStore.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2967

Issue 2967 - Split ingest job status store update into two requests

---

java/cdk/src/main/java/sleeper/cdk/SleeperCdkApp.java
java/cdk/src/main/java/sleeper/cdk/stack/StateStoreCommitterStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2984

Issue 2984 - Grant async commit permission for direct ingest

---

.devcontainer/devcontainer.json
scripts/cli/builder/Dockerfile
scripts/cli/environment/Dockerfile
scripts/cli/runInDocker.sh
scripts/cli/runner/Dockerfile

PR"
- Resolves https://github.com/gchq/sleeper/issues/652
- Tested manually locally

Issue 652 - Preserve file ownership in CLI

---

scripts/cli/runInDocker.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/3001

Issue 3001 - Create CLI runner directory if missing

---

docs/13-system-tests.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/2925
- Documentation changes

Issue 2925 - Explain system tests are set up to run on 3 AZs

---

scripts/cli/builder/Dockerfile
scripts/cli/environment/Dockerfile
scripts/cli/runInDocker.sh
scripts/cli/runner/Dockerfile

PR"
- Resolves https://github.com/gchq/sleeper/issues/3008

Issue 3008 - Fix CLI user file ownership

---

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceST.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3017
- Just relaxing system test assertion

Issue 3017 - Allow lower performance in CompactionPerformanceST

---

scripts/build/build.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/3022

Issue 3022 - Append arguments to mvn command in build scripts

---

java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/job/runner/BulkImportJobDriver.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/commit/CompactionJobCommitterOrSendToLambda.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateCompactionJobs.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/commit/AssignJobIdToFiles.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/commit/AddFilesToStateStore.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3053
- Just logging, covered by existing tests

Issue 3053 - Log async commits

---

java/core/src/main/java/sleeper/core/util/SplitIntoBatches.java
java/core/src/test/java/sleeper/core/util/SplitIntoBatchesTest.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/AwsStateStoreCommitterDriver.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/statestore/AwsStateStoreCommitterDriverIT.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommits.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3061
- Updated SplitIntoBatchesTest
- Also covered by AwsStateStoreCommitterDriverIT

Issue 3061 - Send state store commits in parallel

---

example/full/instance.properties
example/full/table.properties
java/athena/src/test/java/sleeper/athena/metadata/IteratorApplyingMetadataHandlerIT.java
java/athena/src/test/java/sleeper/athena/metadata/SleeperMetadataHandlerIT.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/PartitionSplittingProperty.java
java/configuration/src/main/java/sleeper/configuration/properties/table/TableProperty.java
java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTestHelper.java
java/splitter/splitter-core/src/main/java/sleeper/splitter/split/FindPartitionSplitPoint.java
java/splitter/splitter-core/src/main/java/sleeper/splitter/split/SplitPartition.java
java/splitter/splitter-core/src/test/java/sleeper/splitter/split/SplitPartitionTest.java
java/splitter/splitter-lambda/pom.xml
java/splitter/splitter-lambda/src/main/java/sleeper/splitter/lambda/SplitPartitionLambda.java
java/splitter/splitter-lambda/src/test/java/sleeper/splitter/lambda/SplitPartitionLambdaIT.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryPartitionSplittingDriver.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/2927
- Updated SplitPartitionTest
- Added SplitPartitionLambdaIT

Issue 2927 - Asynchronously commit partition splitting

---

java/cdk/src/main/java/sleeper/cdk/stack/CoreStacks.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3102

Issue 3102 - Grant sending state store commits

---

java/cdk/src/main/java/sleeper/cdk/stack/ManagedPoliciesStack.java
java/cdk/src/main/java/sleeper/cdk/stack/StateStoreCommitterStack.java
java/clients/src/main/java/sleeper/clients/status/report/statestore/StateStoreCommitterRequestsPerSecond.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CdkDefinedInstanceProperty.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/AwsStateStoreCommitterDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/StateStoreCommitterLogEntries.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/statestore/StateStoreCommitterLogEntriesTest.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/StateStoreCommitMessageFactory.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/StateStoreCommitterDriver.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/StateStoreCommitterLogs.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/SystemTestStateStore.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommits.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/WaitForStateStoreCommitLogs.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommitsTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommitsThroughputTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryStateStoreCommitter.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3060
- StateStoreCommitterThroughputST (passed in AWS)
- SystemTestStateStoreFakeCommitsThroughputTest
- Updated StateStoreCommitterLogEntriesTest

Issue 3060 - Measure throughput in state store committer

---

example/full/instance.properties
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/CompactionProperty.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/2977
- Just changing default value for an instance property

Issue 2977 - Increase default visibility timeout for a failed compaction

---

java/statestore-commit/src/main/java/sleeper/commit/StateStoreCommitter.java
java/statestore-commit/src/test/java/sleeper/commit/StateStoreCommitterTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3069
- Updated StateStoreCommitterTest

Issue 3069 - Update status store for every failure committing a compaction

---

.gitignore
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/fixtures/SystemTestInstanceTest.java
scripts/test/nightly/runTests.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/3122

Issue 3122 - Avoid duplicate test output in nightly test Maven site

---

java/cdk/src/main/java/sleeper/cdk/stack/ManagedPoliciesStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3116
- Will run nightly test suite in AWS

Issue 3116 - Combine policies for instance admin role

---

NOTICES
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3137

Issue 3137 - Manage version of XZ

---

java/common/dynamodb-tools/src/main/java/sleeper/dynamodb/tools/DynamoDBUtils.java
java/common/dynamodb-tools/src/test/java/sleeper/dynamodb/tools/DynamoDBUtilsTest.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/task/StateStoreWaitForFiles.java
java/core/src/main/java/sleeper/core/util/PollWithRetries.java
java/core/src/test/java/sleeper/core/util/PollWithRetriesTest.java
java/statestore-lambda/src/main/java/sleeper/statestore/committer/lambda/StateStoreCommitterLambda.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3149
- Updated PollWithRetriesTest

Issue 3149 - Track retries instead of polls in PollWithRetries

---

scripts/cli/environment/.dockerignore
scripts/cli/environment/Dockerfile
scripts/cli/environment/scripts/subcommands/adduser.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/3163

Issue 3163 - Fix environment CLI permissions

---

example/full/instance.properties
java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
java/configuration/src/main/java/sleeper/configuration/Utils.java
java/configuration/src/main/java/sleeper/configuration/properties/instance/GarbageCollectionProperty.java
java/configuration/src/test/java/sleeper/configuration/properties/InstancePropertiesTest.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/2511
-  Testing provided by expanding instance properties

2511 Configure timeout for garbage collector lambda

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsWaitForJobs.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/LocalStackSystemTestDrivers.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SystemTestDrivers.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/CompactionDriver.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/SystemTestCompaction.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/gc/SystemTestGarbageCollection.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/InvokeIngestTasksDriver.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngest.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngestBatcher.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngestByQueue.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/partitioning/SystemTestPartitioning.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/partitioning/WaitForPartitionSplitting.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/python/SystemTestPythonApi.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/python/SystemTestPythonBulkImport.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/python/SystemTestPythonIngest.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/python/SystemTestPythonQuery.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/SystemTestCluster.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/util/PollWithRetriesDriver.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/util/WaitForJobs.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryCompaction.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestByQueue.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3180

Issue 3180 - Avoid waits in system test DSL tests

---

java/cdk/src/main/java/sleeper/cdk/stack/StateStoreCommitterStack.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/LocalStackSleeperInstanceDriver.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3134
- Resolves https://github.com/gchq/sleeper/issues/3177
- Execution of existing System Tests with particular focus on StateStoreCommitterThroughputST.java

Issue 3134 - High throughput FIFO queue for state store committer

---

java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionJobStatusStore.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobFilesAssignedStatus.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobInputFilesAssignedStatus.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/job/status/CompactionJobStatus.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/job/CompactionJobStatusTestData.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStore.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStoreTest.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusFormat.java
java/compaction/compaction-status-store/src/main/java/sleeper/compaction/status/store/job/DynamoDBCompactionJobStatusStore.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobCreatedIT.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/job/StoreCompactionJobUpdatesIT.java
java/compaction/compaction-status-store/src/test/java/sleeper/compaction/status/store/testutils/DynamoDBCompactionJobStatusStoreTestBase.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3197
- Updated InMemoryCompactionJobStatusStoreTest, StoreCompactionJobUpdatesIT

Issue 3197 - Support compaction input files assigned event in status store

---

java/compaction/compaction-core/src/test/java/sleeper/compaction/testutils/InMemoryCompactionJobStatusStore.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/CreateCompactionJobs.java
java/compaction/compaction-job-creation/src/main/java/sleeper/compaction/job/creation/commit/AssignJobIdToFiles.java
java/compaction/compaction-job-creation/src/test/java/sleeper/compaction/job/creation/CreateCompactionJobsTest.java
java/statestore-commit/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
java/statestore-commit/src/test/java/sleeper/statestore/committer/StateStoreCommitterTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3198
- Updated CreateCompactionJobsTest
- Updated StateStoreCommitterTest

Issue 3198 - Submit compaction files assigned event

---

java/compaction/compaction-core/src/main/java/sleeper/compaction/job/CompactionRunner.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionRunnerFactory.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTestBase.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/DefaultCompactionRunnerFactory.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/ECSCompactionTaskRunner.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/JavaCompactionRunner.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactionRunnerTestBase.java
java/compaction/compaction-rust/src/main/java/sleeper/compaction/rust/RustCompactionRunner.java
java/compaction/compaction-rust/src/test/java/sleeper/compaction/rust/RustCompactionRunnerIT.java
java/compaction/compaction-rust/src/test/java/sleeper/compaction/rust/RustCompactionRunnerLocalStackIT.java
java/core/src/main/java/sleeper/core/statestore/PartitionStore.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3290

Issue 3290 - Load TableProperties and Partition in CompactionTask

---

java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3271
- Update CompactionTaskTest

Issue 3271 - Discard compactions for deleted tables

---

CHANGELOG.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/3286
- Just changelog

Issue 3286 - Changelog for 0.25 release

---

NOTICES

PR"
- Resolves https://github.com/gchq/sleeper/issues/3261
- Just NOTICES

Issue 3261 - Update NOTICES for 0.25 release

---

java/clients/pom.xml
java/clients/src/main/java/sleeper/clients/AdminClient.java
java/clients/src/main/java/sleeper/clients/deploy/DeployExistingInstance.java
java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
java/clients/src/main/java/sleeper/clients/teardown/RemoveECRRepositories.java
java/clients/src/main/java/sleeper/clients/teardown/TearDownClients.java
java/clients/src/main/java/sleeper/clients/util/EcrRepositoryCreator.java
java/clients/src/test/java/sleeper/clients/testutil/ClientWiremockTestHelper.java
java/common/common-task/src/test/java/sleeper/task/common/WiremockTestHelper.java
java/configuration/pom.xml
java/configuration/src/main/java/sleeper/configuration/utils/AwsV2ClientHelper.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/CleanUpDeletedSleeperInstances.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperInstanceDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSystemTestDeploymentDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3267

Issue 3267 - Upgrade ECR client to SDK v2

---

java/clients/pom.xml
java/clients/src/main/java/sleeper/clients/status/update/PauseSystem.java
java/clients/src/main/java/sleeper/clients/status/update/RestartSystem.java
java/clients/src/main/java/sleeper/clients/teardown/ShutdownSystemProcesses.java
java/clients/src/main/java/sleeper/clients/teardown/TearDownClients.java
java/clients/src/test/java/sleeper/clients/testutil/ClientWiremockTestHelper.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/AwsSnapshotsDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3282

Issue 3282 - Upgrade CloudWatch Events client to SDK v2

---

java/bulk-import/bulk-import-starter/pom.xml
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceConfiguration.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceFleets.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrInstanceGroups.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/EmrPlatformExecutor.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/PersistentEmrPlatformExecutor.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/PlatformExecutor.java
java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrPlatformExecutorTest.java
java/clients/pom.xml
java/clients/src/main/java/sleeper/clients/AdminClient.java
java/clients/src/main/java/sleeper/clients/status/report/IngestJobStatusReport.java
java/clients/src/main/java/sleeper/clients/status/report/ingest/job/PersistentEMRStepCount.java
java/clients/src/main/java/sleeper/clients/teardown/ShutdownSystemProcesses.java
java/clients/src/main/java/sleeper/clients/teardown/TearDownClients.java
java/clients/src/main/java/sleeper/clients/teardown/TerminateEMRClusters.java
java/clients/src/main/java/sleeper/clients/util/EmrUtils.java
java/clients/src/test/java/sleeper/clients/testutil/ClientWiremockTestHelper.java
java/common/common-task/src/test/java/sleeper/task/common/WiremockTestHelper.java
java/system-test/system-test-drivers/pom.xml
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/AwsIngestReportsDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3276

Issue 3276 - Upgrade EMR client to SDK v2

---

code-style/dependency-check-suppressions.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3342
- Just updating suppressions

Issue 3342 - Update suppression for AWS CDK dependencies

---

code-style/dependency-check-suppressions.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3351
- Just dependency check suppresssions

Issue 3351 - Update suppression for AWS CDK dependencies

---

java/clients/src/main/java/sleeper/clients/deploy/UploadDockerImages.java
java/core/src/main/java/sleeper/core/properties/SleeperProperties.java
java/core/src/test/java/sleeper/core/properties/SleeperPropertiesTest.java
java/core/src/test/java/sleeper/core/properties/validation/OptionalStackTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3371
- Updated SleeperPropertiesTest, OptionalStacksTest

Issue 3371 - Fix passing empty optional stacks to CDK

---

java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/BulkImportStarterLambda.java
java/clients/src/main/java/sleeper/clients/deploy/UploadDockerImages.java
java/core/src/main/java/sleeper/core/properties/SleeperProperties.java
java/core/src/test/java/sleeper/core/properties/SleeperPropertiesTest.java
java/core/src/test/java/sleeper/core/properties/validation/OptionalStackTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3373

Issue 3373 - Fix BulkImportStarterLambda loading instance properties

---

java/clients/src/main/java/sleeper/clients/teardown/TearDownInstance.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/TearDownMavenSystemTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3378

Issue 3378 - Fix teardown scripts

---

code-style/dependency-check-suppressions.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3385
- Just updating dependency check suppressions

Issue 3385 - Add suppression for Hadoop not caught by CPE

---

java/pom.xml
java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperty.java
java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestStandaloneProperties.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSystemTestResources.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestParameters.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/SystemTestParametersTestHelper.java
scripts/test/deployAll/system-test-instance.properties
scripts/test/maven/deployTest.sh
scripts/test/maven/system-test-standalone.properties

PR"
- Resolves https://github.com/gchq/sleeper/issues/3376

Issue 3376 - Configure Maven system tests from template

---

java/cdk/src/main/java/sleeper/cdk/util/AutoDeleteS3Objects.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3403

Issue 3403 - Raise timeout for autodelete lambda

---

example/full/instance.properties
java/bulk-import/bulk-import-common/src/main/java/sleeper/bulkimport/configuration/ConfigurationUtils.java
java/core/src/main/java/sleeper/core/properties/PropertyGroup.java
java/core/src/main/java/sleeper/core/properties/SleeperPropertiesPrettyPrinter.java
java/core/src/main/java/sleeper/core/properties/deploy/GeneratePropertiesTemplates.java
java/core/src/main/java/sleeper/core/properties/instance/EMRProperty.java
java/core/src/main/java/sleeper/core/properties/instance/InstancePropertyGroup.java
java/core/src/test/java/sleeper/core/properties/SleeperPropertiesPrettyPrinterTest.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/3201

Issue 3201 - Lower Spark executor memory overhead

---

.github/config/chunks.yaml
.github/workflows/chunk-clients-cdk.yaml
java/build-uptime-lambda/pom.xml
java/build-uptime-lambda/src/main/java/sleeper/build/uptime/lambda/BuildUptimeCondition.java
java/build-uptime-lambda/src/main/java/sleeper/build/uptime/lambda/BuildUptimeEvent.java
java/build-uptime-lambda/src/main/java/sleeper/build/uptime/lambda/BuildUptimeEventSerDe.java
java/build-uptime-lambda/src/main/java/sleeper/build/uptime/lambda/BuildUptimeLambda.java
java/build-uptime-lambda/src/main/java/sleeper/build/uptime/lambda/GetS3ObjectAsString.java
java/build-uptime-lambda/src/main/java/sleeper/build/uptime/lambda/NightlyTestSummaryTable.java
java/build-uptime-lambda/src/test/java/sleeper/build/uptime/lambda/BuildUptimeLambdaIT.java
java/build-uptime-lambda/src/test/java/sleeper/build/uptime/lambda/LocalStackTestHelper.java
java/build-uptime-lambda/src/test/java/sleeper/build/uptime/lambda/WiremockTestHelper.java
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3411
- BuildUptimeLambdaIT

Issue 3411 - Lambda to start and stop EC2s

---

code-style/dependency-check-suppressions.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3435

Issue 3435 - Suppress false positive dependency check for HK2 library

---

docs/02-deployment-guide.md
java/cdk-environment/src/main/java/sleeper/environment/cdk/SleeperEnvironmentCdkApp.java
java/cdk-environment/src/main/java/sleeper/environment/cdk/buildec2/BuildEC2Deployment.java
java/cdk-environment/src/main/java/sleeper/environment/cdk/builduptime/AutoShutdownSchedule.java
java/cdk-environment/src/main/java/sleeper/environment/cdk/builduptime/BuildUptimeDeployment.java
java/cdk-environment/src/main/java/sleeper/environment/cdk/config/AppContext.java
java/cdk-environment/src/main/java/sleeper/environment/cdk/config/AppParameters.java
java/cdk-environment/src/main/java/sleeper/environment/cdk/networking/NetworkingDeployment.java
java/cdk-environment/src/main/java/sleeper/environment/cdk/nightlytests/NightlyTestBucket.java
java/cdk-environment/src/main/java/sleeper/environment/cdk/nightlytests/NightlyTestDeployment.java
java/cdk-environment/src/main/java/sleeper/environment/cdk/nightlytests/NightlyTestUptimeSchedules.java
scripts/cli/environment/scripts/subcommands/add.sh
scripts/cli/environment/scripts/subcommands/connect.sh
scripts/cli/environment/scripts/subcommands/deploy.sh
scripts/cli/environment/scripts/subcommands/setuser.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/3427

Issue 3427 - Combine cdk-environment into one stack

---

example/full/instance.properties
java/cdk-environment/src/main/java/sleeper/environment/cdk/buildec2/BuildEC2Image.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportStack.java
java/core/src/main/java/sleeper/core/properties/instance/EMRProperty.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/3414

Issue 3414 - Encrypt EBS volumes

---

example/full/instance.properties
java/cdk/src/main/java/sleeper/cdk/stack/AthenaStack.java
java/core/src/main/java/sleeper/core/properties/instance/AthenaProperty.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/3333

Issue 3333 - Add property to set Athena spill master key

---

.gitignore
java/core/src/main/java/sleeper/core/properties/SleeperProperties.java
java/pom.xml
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestParameters.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/SystemTestParametersTestHelper.java
java/system-test/system-test-suite/src/main/java/sleeper/systemtest/suite/fixtures/SystemTestInstance.java
scripts/test/deployAll/deployTest.sh
scripts/test/deployAll/system-test-instance.properties.template
scripts/test/maven/deployTest.sh
scripts/test/maven/system-test-instance.properties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/3430

Issue 3430 - Override instance properties in system tests

---

java/cdk-environment/src/main/java/sleeper/environment/cdk/nightlytests/NightlyTestDeployment.java
java/cdk-environment/src/main/java/sleeper/environment/cdk/nightlytests/NightlyTestUptimeSchedules.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3439

Issue 3439 - Grant access to nightly test bucket

---

java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3447
- Tested in AWS with EmrBulkImportST

Issue 3447 - Fix EMR EBS encryption key

---

java/build-uptime-lambda/pom.xml
java/bulk-import/bulk-import-starter/pom.xml
java/cdk-environment/pom.xml
java/clients/pom.xml
java/clients/src/main/java/sleeper/clients/QueryLambdaClient.java
java/clients/src/main/java/sleeper/clients/status/report/DeadLettersStatusReport.java
java/clients/src/main/java/sleeper/clients/status/report/RetryMessages.java
java/clients/src/main/java/sleeper/clients/status/report/StatusReport.java
java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceIT.java
java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceTestBase.java
java/clients/src/test/java/sleeper/clients/deploy/docker/SendFilesToIngestIT.java
java/common/common-job/pom.xml
java/common/common-task/pom.xml
java/pom.xml
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/MultipleQueries.java
java/system-test/system-test-drivers/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3275
- Some covered by existing tests
- Raised separate issues to improve the tests, and finish the upgrade of SendFilesToIngest:
- https://github.com/gchq/sleeper/issues/3449
- https://github.com/gchq/sleeper/issues/3455

Issue 3275 - Upgrade SQS SDK in clients module

---

java/clients/src/main/java/sleeper/clients/docker/DeployDockerInstance.java
java/clients/src/main/java/sleeper/clients/docker/SendFilesToIngest.java
java/clients/src/main/java/sleeper/clients/docker/TearDownDockerInstance.java
java/clients/src/main/java/sleeper/clients/docker/stack/CompactionDockerStack.java
java/clients/src/main/java/sleeper/clients/docker/stack/IngestDockerStack.java
java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceIT.java
java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceTestBase.java
java/clients/src/test/java/sleeper/clients/deploy/docker/SendFilesToIngestIT.java
java/core/src/test/java/sleeper/core/CommonTestConstants.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/AwsStateStoreCommitterDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/statestore/AwsStateStoreCommitterDriverIT.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/LocalStackSleeperInstanceDriver.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/LocalStackSystemTestDrivers.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/testutil/LocalStackSystemTestExtension.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3449
- Updated SendFilesToIngestIT

Issue 3449 - Integration test SQS SDK v2, upgrade in `SendFilesToIngest`

---

code-style/dependency-check-suppressions.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3473

Issue 3473 - Suppress DOMPurify dependency check failure

---

java/cdk/src/main/java/sleeper/cdk/stack/CompactionStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3450

Issue 3450 - Add explicit dependency on auto scaling permission

---

java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
java/cdk/src/main/java/sleeper/cdk/util/Utils.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3475

Issue 3475 - Configure logging for EKS bulk import state machine

---

java/ingest/ingest-runner/src/main/java/sleeper/ingest/impl/recordbatch/arrow/ArrowIngestSupport.java
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/2015

Issue 2015 - Upgrade Arrow to 17.0.0

---

code-style/dependency-check-suppressions.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3495

Issue 3495 - Suppress jetty-http vulnerability

---

.github/pull_request_template.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/3497
- Just PR template

Issue 3497 - Remove note in PR template about NOTICES

---

java/cdk-environment/src/main/java/sleeper/environment/cdk/builduptime/BuildUptimeDeployment.java
java/cdk-environment/src/main/java/sleeper/environment/cdk/config/AppParameters.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3505

Issue 3505 - Set log retention for build uptime lambda

---

java/clients/src/main/java/sleeper/clients/deploy/PopulateInstanceProperties.java
java/clients/src/main/java/sleeper/clients/teardown/RemoveECRRepositories.java
java/clients/src/test/java/sleeper/clients/deploy/PopulatePropertiesTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3555

Issue 3555 - Tear down lambda ECR repositories

---

docs/02-deployment-guide.md
java/cdk-environment/src/main/resources/cloud-init.sh
scripts/test/nightly/runTests.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/3592
- Tested manually in AWS

Issue 3592 - Don't overwrite settings on build EC2 startup

---

java/cdk/src/main/java/sleeper/cdk/stack/TransactionLogStateStoreStack.java
java/clients/src/test/java/sleeper/clients/status/update/DeleteTableIT.java
java/statestore-lambda/src/main/java/sleeper/statestore/snapshot/TransactionLogSnapshotCreationLambda.java
java/statestore-lambda/src/main/java/sleeper/statestore/snapshot/TransactionLogSnapshotDeletionLambda.java
java/statestore-lambda/src/main/java/sleeper/statestore/transaction/TransactionLogTransactionDeletionLambda.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStore.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogStateStoreCreator.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/TransactionLogTransactionDeleter.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotCreator.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotMetadataStore.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotMetadataStoreCreator.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotStore.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/LatestSnapshots.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/SnapshotType.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotDeleter.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotMetadata.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotSerDe.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreDynamoDBSpecificIT.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreOneTableTestBase.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotMetadataStoreIT.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotStoreBasePathTest.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/InMemoryTransactionLogSnapshotMetadataStore.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotCreatorIT.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotDeleterIT.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotSerDeIT.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotTestBase.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogTransactionDeleterTest.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperTablesDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/AwsSnapshotsDriver.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3587

Issue 3587 - Create package for transaction log snapshots code

---

java/cdk/src/main/java/sleeper/cdk/stack/TransactionLogSnapshotStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3604
- Covered in nightly tests

Issue 3604 - Set queue visibility timeout for snapshot creation

---

scripts/cli/runInDocker.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/3448
- Following bug steps within parent ticket and repeating locally to see new message.
separate issue for that below. [None necessary for this ticket]

Update to improve error handling for docker image not present

---

java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
java/core/src/main/java/sleeper/core/deploy/DeployInstanceConfiguration.java
java/core/src/main/java/sleeper/core/deploy/DeployInstanceConfigurationFromTemplates.java
java/core/src/main/java/sleeper/core/deploy/PopulateInstanceProperties.java
java/core/src/test/java/sleeper/core/deploy/DeployInstanceConfigurationFromTemplatesIT.java
java/core/src/test/java/sleeper/core/deploy/DeployInstanceConfigurationIT.java
java/core/src/test/java/sleeper/core/deploy/PopulateInstancePropertiesTest.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/cdk/DeployNewTestInstance.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperInstanceDriver.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3615
- Updated DeployInstanceConfigurationFromTemplatesIT

Issue 3615 - Move property population to static constructor

---

java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskAssignFilesTest.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskCommitTest.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTerminateTest.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTest.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTestBase.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/SqsCompactionQueueHandler.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3563
- Updated CompactionTaskAssignFilesTest

Issue 3563 - Handle invalid job while waiting for file assignment

---

.github/workflows/rust-tests.yaml
rust/Cargo.lock
rust/compaction/Cargo.toml
rust/compaction/src/details.rs
rust/compaction/tests/compaction_helpers.rs
rust/compaction/tests/compaction_test.rs

PR"
- Resolves https://github.com/gchq/sleeper/issues/3477
- compaction_test.rs

Issue 3477 - Rust compaction integration tests

---

java/compaction/compaction-core/src/main/java/sleeper/compaction/task/CompactionTask.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskAssignFilesTest.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskCommitTest.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/task/CompactionTaskTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3617
- Updated CompactionTaskAssignFilesTest, CompactionTaskCommitTest

Issue 3617 - Discard invalid compaction on commit

---

docs/02-deployment-guide.md
java/clients/src/main/java/sleeper/clients/deploy/DeployNewInstance.java
java/core/src/main/java/sleeper/core/deploy/DeployInstanceConfiguration.java
java/core/src/main/java/sleeper/core/deploy/DeployInstanceConfigurationFromTemplates.java
java/core/src/test/java/sleeper/core/deploy/DeployInstanceConfigurationIT.java
java/core/src/test/java/sleeper/core/deploy/PopulateInstancePropertiesTest.java
java/core/src/test/java/sleeper/core/deploy/PopulatePropertiesTestHelper.java
scripts/deploy/deployNew.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/3513
- Updated DeployInstanceConfigurationIT

Issue 3513 - Deploy an instance with no tables

---

code-style/dependency-check-suppressions.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3663
- Maven build execution

Update new dependency check suppressions

---

java/cdk/src/main/java/sleeper/cdk/stack/DashboardStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3674

Issue 3674 - Deploy dashboard stack with no tables

---

example/full/instance.properties
java/core/src/main/java/sleeper/core/properties/instance/DefaultProperty.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/3665
- Just description changes

Issue 3665 - Improve descriptions of default lambda concurrency properties

---

java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/CompactionJob.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/core/task/StateStoreWaitForFiles.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
java/core/src/main/java/sleeper/core/statestore/CheckFileAssignmentsRequest.java
java/core/src/main/java/sleeper/core/statestore/FileReferenceStoreQueries.java
java/core/src/test/java/sleeper/core/statestore/testutils/InMemoryFileReferenceStoreTest.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStoreTest.java
java/statestore/src/test/java/sleeper/statestore/dynamodb/DynamoDBFileReferenceStoreIT.java
java/statestore/src/test/java/sleeper/statestore/s3/S3FileReferenceStoreIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3699
- Updated tests to use new method signature

Issue 3699 - Check many job file assignments in one query

---

.github/workflows/chunk.yaml
.github/workflows/docker-cli-image.yaml
.github/workflows/docker-cli.yaml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3656
- Ran in Actions

Issue 3656 - Upgrade upload/download artifact actions

---

.gitignore
java/clients/src/main/java/sleeper/clients/status/report/statestore/QueryStateStoreCommitterLogs.java
java/clients/src/main/java/sleeper/clients/status/report/statestore/StateStoreCommitSummary.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
java/core/src/test/java/sleeper/core/statestore/FileReferenceFactory.java
java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitRequestDeserialiser.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/AwsStateStoreCommitterDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/statestore/SystemTestStateStoreFakeCommits.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/StateStoreCommitterThroughputST.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3676
- Updated StateStoreCommitterThroughputST
- Passed in AWS

Issue 3676 - System test throughput for large commits

---

java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/SleeperInstanceTablesLocalIT.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SystemTestContext.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceContext.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/extension/SleeperSystemTestExtension.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/SleeperInstanceTablesTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3707
- Updated SleeperInstanceTablesTest

Issue 3707 - Generate system test table names from test name

---

java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/CompactionJobSerDe.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatchRequest.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatchRequestSerDe.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/CompactionJobSerDeTest.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/CompactionJobSerDeTest.shouldConvertCompactionJobBatchToFromJson.approved.json
java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatchRequestSerDeTest.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatchRequestSerDeTest.shouldConvertRequestToFromJson.approved.json
java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatcherTest.java
java/core/src/main/java/sleeper/core/table/TableFilePaths.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3703
- CompactionJobDispatchRequestSerDeTest
- Updated CompactionJobSerDeTest
- Updated CompactionJobDispatcherTest

Issue 3703 - Serialization for compaction dispatch

---

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionPerformanceST.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3732
- Just updating performance assertion

Issue 3732 - Lower asserted compaction performance range

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/statestore/StateStoreCommitterLogEntries.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3733

Issue 3733 - Find commits per second by averaging over runs

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/instance/AwsSleeperTablesDriver.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/instance/AwsSleeperTablesDriverIT.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperInstance.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSleeperInstances.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SleeperTablesDriver.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceContext.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/extension/SleeperSystemTestExtension.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemorySleeperTablesDriver.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3705
- Passed in AWS

Issue 3705 - Take tables offline after system tests

---

README.md
docs/05-ingest.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/3730
- None required as documentation

Update documentation details for EMRServerlessBulkImportStack

---

rust/compaction/tests/compaction_helpers.rs

PR"
- Resolves https://github.com/gchq/sleeper/issues/3757

Issue 3757 - Resolve Clippy problems in compaction_helpers.rs

---

java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/SystemTestCompaction.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/WaitForCompactionJobCreation.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3763

Issue 3763 - Wait for compaction creation to commit when splitting files in system tests

---

rust/Cargo.lock
rust/compaction/Cargo.toml
rust/compaction/src/datafusion/sketch.rs
rust/compaction/src/datafusion/udf.rs

PR"
- Resolves https://github.com/gchq/sleeper/issues/3670
All unit tests still applicable.

Issue 3670 - Upgrade DataFusion to 43.0.0

---

java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionTaskResources.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3777

Issue 3777 - Add DescribeInstanceTypes permission to compaction task creation lambda

---

rust/compaction/src/datafusion/udf.rs

PR"
- Resolves https://github.com/gchq/sleeper/issues/3786

Issue 3786 - Add extra ScalarValue cases for DataFusion 43

---

.github/workflows/rust-audit.yaml
rust/Cargo.lock
scripts/cli/builder/Dockerfile

PR"
- Resolves https://github.com/gchq/sleeper/issues/3795

Issue 3795 - Fix `cargo audit` problem

---

.github/workflows/dependency-check.yaml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3810
- Will run in GitHub Actions

Issue 3810 - Temporarily disable dependency checks

---

java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatcher.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/dispatch/CompactionJobDispatcherTest.java
java/compaction/compaction-job-creation-lambda/src/main/java/sleeper/compaction/job/creation/lambda/CompactionJobDispatchLambda.java
java/compaction/compaction-job-creation-lambda/src/test/java/sleeper/compaction/job/creation/lambda/CompactionJobDispatchLambdaIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3840
- Updated CompactionJobDispatcherTest

Issue 3840 - Handle partial batch failures in compaction dispatch

---

java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogDeletionTracker.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogDeletionTrackerTest.java
java/statestore-lambda/src/main/java/sleeper/statestore/lambda/transaction/TransactionLogTransactionDeletionLambda.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStoreNoSnapshots.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotCreator.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStoreIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3807
- TransactionLogDeletionTrackerTest

Issue 3807 - Improvements to transaction deletion logs

---

java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/SystemTestCompaction.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3854
- Ran MultipleTablesST and PartitionSplittingST in AWS

Issue 3854 - Increase wait for forced compaction creation

---

java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/creation/CreateCompactionJobs.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3863

Issue 3863 - Adjust log messages in CreateCompactionJobs.batchCreateJobs

---

docs/02-deployment-guide.md
docs/04-tables.md
docs/06-status.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/3831

Issue 3831 - Rearrange scripts documentation

---

docs/11-deploy-to-localstack.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/3869

Issue 3869 - Link to issue on compaction in LocalStack

---

java/build/src/test/resources/examples/maven/configuration/pom.xml
java/bulk-import/bulk-import-eks/pom.xml
java/bulk-import/bulk-import-runner/pom.xml
java/parquet/pom.xml
java/pom.xml
java/sketches/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3887
- Testing in AWS

Issue 3887 - Manage dependencies on EKS

---

CHANGELOG.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/3879
- Just changelog

Issue 3879 - Changelog for release 0.27

---

example/full/instance.properties
java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
java/core/src/main/java/sleeper/core/properties/instance/BatcherProperty.java
java/core/src/main/java/sleeper/core/properties/instance/GarbageCollectionProperty.java
java/core/src/main/java/sleeper/core/properties/instance/PartitionSplittingProperty.java
java/core/src/main/java/sleeper/core/properties/instance/QueryProperty.java
java/core/src/main/java/sleeper/core/properties/instance/TableStateProperty.java
java/core/src/main/java/sleeper/core/properties/validation/SleeperPropertyValueUtils.java
java/core/src/test/java/sleeper/core/properties/instance/InstancePropertiesTest.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/3909

Issue 3909 - Configure GC lambda timeout in seconds

---

java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionJobResources.java
java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionTaskResources.java
java/cdk/src/main/java/sleeper/cdk/stack/core/TransactionLogSnapshotStack.java
java/cdk/src/main/java/sleeper/cdk/stack/core/TransactionLogTransactionStack.java
java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestBatcherStack.java
java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestStack.java
java/cdk/src/main/java/sleeper/cdk/stack/query/KeepLambdaWarmStack.java
java/cdk/src/main/java/sleeper/cdk/util/Utils.java
java/core/src/main/java/sleeper/core/deploy/SleeperScheduleRule.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3866

Issue 3866 - Add missing descriptions

---

NOTICES
java/build/src/main/java/sleeper/build/notices/NoticeDeclaration.java
java/build/src/test/java/sleeper/build/notices/CheckNoticesTest.java
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3930
- Just dependency changes

Issue 3930 - Tidy dependencies

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/AwsIngestTasksDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/AwsInvokeIngestTasksDriver.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsSystemTestDrivers.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/SystemTestDrivers.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/IngestTasksDriver.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngest.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngestBatcher.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/SystemTestIngestByQueue.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/ingest/WaitForIngestTasks.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/SystemTestInstanceConfiguration.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/python/SystemTestPythonIngest.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/SystemTestCluster.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/util/SystemTestDriversBase.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/InvokeIngestTasksTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/SystemTestIngestBatcherTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/SystemTestIngestTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/ingest/WaitForIngestTasksTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/instance/MultipleTablesTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/reporting/SystemTestReportingTest.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/InMemorySystemTestDrivers.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestBatcherDriver.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/testutil/drivers/InMemoryIngestByQueue.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestBatcherST.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceST.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestST.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/MultipleTablesST.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/PythonIngestST.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/SetupInstanceST.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3726
- Updated & renamed WaitForIngestTasksTest
- Ran quick system test suite in AWS

Issue 3726 - Enable ingest task creation schedule in system tests

---

.github/workflows/chunk.yaml
.github/workflows/rust-audit.yaml
.github/workflows/rust-cache.yaml
.github/workflows/rust-lint.yaml
.github/workflows/rust-tests.yaml
rust/compaction/src/details.rs
rust/rust_sketch/src/quantiles.rs

PR"
- Resolves https://github.com/gchq/sleeper/issues/3954
- Running in GitHub Actions

Issue 3954 - Upgrade Rust & sccache in GitHub Actions

---

.github/workflows/dependency-check.yaml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3811
- Running in GitHub Actions

Issue 3811 - Re-enable dependency checks

---

java/core/src/main/java/sleeper/core/statestore/transactionlog/AddTransactionRequest.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionBodyPointer.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionBodyStore.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogEntry.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionBodyStore.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStateStoreTestBase.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogs.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3899

Issue 3899 - State store method to add a transaction from S3

---

.devcontainer/devcontainer.json
docs/12-dev-guide.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4038
- Just dev container configuration and documentation

Issue 4038 - Create missing folders when starting dev container, improve docs

---

java/core/src/main/java/sleeper/core/statestore/transactionlog/AddTransactionRequest.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionBodyPointer.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogEntry.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStateStoreNoSnapshots.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/S3TransactionBodyStore.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStoreIT.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreDynamoDBSpecificIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4041
- Updated DynamoDBTransactionLogStoreIT, TransactionLogStateStoreDynamoDBSpecificIT

Issue 4041 - Split transaction upload to s3 out of transaction log store

---

java/core/src/main/java/sleeper/core/range/RegionSerDe.java
java/core/src/main/java/sleeper/core/statestore/ReplaceFileReferencesRequest.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDe.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeAddFiles.approved.txt
java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeAddSplitFile.approved.txt
java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeInitialisePartitions.approved.txt
java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeReplaceFileReferences.approved.txt
java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeReplaceFileReferencesWithTrackingIds.approved.txt
java/core/src/test/java/sleeper/core/statestore/transactionlog/transactions/TransactionSerDeTest.shouldSerDeSplitFileReferences.approved.txt

PR"
- Resolves https://github.com/gchq/sleeper/issues/3898
- Updated TransactionSerDeTest

Issue 3898 - Add tracking metadata to compaction commit transaction

---

rust/compaction/src/datafusion/udf.rs

PR"
- Resolves https://github.com/gchq/sleeper/issues/4092
- Function change for future proofing

Issue 4092 - Update functions in SketchUDF Impl

---

java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/4077

Issue 4077 - Upgrade AWS SDK v2

---

scripts/cli/environment/buildMaven.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/4107
- Will run in GHA

Issue 4107 - Add also-make flag in CLI environment build script

---

docs/deployment-guide.md
docs/getting-started.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4099

Issue 4099 - Document using Sleeper environment EC2 with multiple users

---

example/full/instance.properties
java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionJobResources.java
java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionStack.java
java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionTaskResources.java
java/cdk/src/main/java/sleeper/cdk/stack/core/CoreStacks.java
java/cdk/src/main/java/sleeper/cdk/stack/core/LoggingStack.java
java/cdk/src/main/java/sleeper/cdk/stack/core/StateStoreCommitterStack.java
java/core/src/main/java/sleeper/core/deploy/LambdaHandler.java
java/core/src/main/java/sleeper/core/deploy/SqsQueues.java
java/core/src/main/java/sleeper/core/properties/instance/CdkDefinedInstanceProperty.java
java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/3906

Issue 3906 - Deploy compaction commit batcher lambda

---

example/full/instance.properties
example/full/table.properties
java/athena/src/main/java/sleeper/athena/record/IteratorApplyingRecordHandler.java
java/clients/src/main/java/sleeper/clients/QueryClient.java
java/clients/src/test/java/sleeper/clients/admin/InstanceConfigurationScreenTest.java
java/clients/src/test/java/sleeper/clients/deploy/docker/DockerInstanceTestBase.java
java/core/src/main/java/sleeper/core/properties/instance/TableDefaultProperty.java
java/core/src/main/java/sleeper/core/properties/table/TableProperty.java
java/parquet/src/main/java/sleeper/parquet/record/ParquetRecordReader.java
java/query/query-lambda/src/main/java/sleeper/query/lambda/SqsLeafPartitionQueryProcessor.java
java/query/query-lambda/src/main/java/sleeper/query/lambda/SqsQueryProcessor.java
java/query/query-runner/src/main/java/sleeper/query/runner/recordretrieval/LeafPartitionRecordRetrieverImpl.java
java/query/query-runner/src/test/java/sleeper/query/runner/recordretrieval/QueryExecutorIT.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/query/DirectQueryDriver.java
java/trino/src/main/java/sleeper/trino/remotesleeperconnection/SleeperRawAwsConnection.java
scripts/templates/instanceproperties.template

… property
PR"
- Resolves https://github.com/gchq/sleeper/issues/3928
- Execution of existing tests

Issue 3928 Optimise Parquet Read Parameters

---

.github/config/chunks.yaml
.github/workflows/chunk-clients-cdk.yaml
.github/workflows/chunk-common.yaml
.github/workflows/chunk-compaction.yaml
.github/workflows/chunk-ingest.yaml
.github/workflows/chunk-query.yaml
.github/workflows/chunk-rust.yaml
java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/CompactionJobSerDeTest.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/CompactionJobSerDeTest.shouldConvertCompactionJobBatchToFromJson.approved.json
java/compaction/compaction-core/src/test/java/sleeper/compaction/core/job/CompactionJobSerDeTest.shouldConvertCompactionJobToFromJsonWithIterator.approved.json
java/compaction/compaction-job-execution/pom.xml
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerIteratorIT.java
java/example-iterators/pom.xml
java/example-iterators/src/main/java/sleeper/example/iterator/AdditionIterator.java
java/example-iterators/src/main/java/sleeper/example/iterator/AgeOffIterator.java
java/example-iterators/src/main/java/sleeper/example/iterator/SecurityFilteringIterator.java
java/example-iterators/src/test/java/sleeper/example/iterator/AdditionIteratorTest.java
java/example-iterators/src/test/java/sleeper/example/iterator/AgeOffIteratorTest.java
java/example-iterators/src/test/java/sleeper/example/iterator/SecurityFilteringIteratorTest.java
java/ingest/ingest-runner/pom.xml
java/ingest/ingest-runner/src/test/java/sleeper/ingest/runner/IngestRecordsIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/runner/IngestRecordsResultIT.java
java/ingest/ingest-runner/src/test/java/sleeper/ingest/runner/impl/IngestCoordinatorCommonIT.java
java/pom.xml
java/query/query-core/pom.xml
java/query/query-core/src/test/java/sleeper/query/core/recordretrieval/QueryExecutorTest.java
java/query/query-runner/pom.xml
java/query/query-runner/src/test/java/sleeper/query/runner/recordretrieval/QueryExecutorIT.java
scripts/build/buildForTest.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/4133

Issue 4133 - Move example iterators to a new module & build fat jar

---

java/clients/src/test/java/sleeper/clients/status/report/ingest/job/IngestJobStatusReporterTestData.java
java/clients/src/test/java/sleeper/clients/status/report/ingest/job/JsonIngestJobStatusReporterAllQueryTest.java
java/clients/src/test/java/sleeper/clients/status/report/ingest/job/StandardIngestJobStatusReporterAllQueryTest.java
java/clients/src/test/java/sleeper/clients/status/report/ingest/job/StandardIngestJobStatusReporterDetailedQueryTest.java
java/clients/src/test/resources/reports/ingest/job/json/bulkImport/finishedJob.json
java/clients/src/test/resources/reports/ingest/job/standard/all/bulkImport/finishedJob.txt
java/clients/src/test/resources/reports/ingest/job/standard/detailed/bulkImport/finishedJob.txt
java/core/src/test/java/sleeper/core/tracker/ingest/job/IngestJobStatusTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4151
- Added reporting tests, added a test in IngestJobStatusTest

Issue 4151 - Bulk import reporting tests

---

example/full/instance.properties
java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestBatcherStack.java
java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestStack.java
java/cdk/src/main/java/sleeper/cdk/stack/query/QueryStack.java
java/core/src/main/java/sleeper/core/properties/instance/BatcherProperty.java
java/core/src/main/java/sleeper/core/properties/instance/CommonProperty.java
java/core/src/main/java/sleeper/core/properties/instance/IngestProperty.java
java/core/src/main/java/sleeper/core/properties/instance/QueryProperty.java
java/core/src/main/java/sleeper/core/properties/validation/SleeperPropertyValueUtils.java
java/core/src/test/java/sleeper/core/properties/instance/InstancePropertiesTest.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/task/IngestJobQueueConsumer.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/3606
- Execution of existing tests as part of build

Issue 3606 - Replace queue visibility timeout instance property

---

java/bulk-import/bulk-import-runner/src/main/java/sleeper/bulkimport/runner/BulkImportJobDriver.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/commit/CompactionCommitBatcher.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/creation/AssignJobIdToFiles.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollector.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/impl/commit/AddFilesToStateStore.java
java/statestore/src/main/java/sleeper/statestore/commit/S3StateStoreCommitRequestUploader.java
java/statestore/src/main/java/sleeper/statestore/commit/SqsFifoStateStoreCommitRequestSender.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4165

Issue 4165 - Adjust logging when sending state store commit requests

---

example/full/instance.properties
java/core/src/main/java/sleeper/core/properties/instance/CommonProperty.java
java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java
java/core/src/main/java/sleeper/core/properties/validation/SleeperPropertyValueUtils.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/4162

Issue 4162 - Fix compaction commit batcher reserved concurrency

---

CHANGELOG.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4127

Issue 4127 - Changelog for 0.28.0 release

---

java/clients/pom.xml
java/pom.xml
java/splitter/splitter-lambda/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/4201

Issue 4201 - Apply ServicesResourceTransformer for all fat jars

---

.github/workflows/dependency-check.yaml
NOTICES
code-style/dependency-check-suppressions.xml
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/4222

Issue 4222 - Resolve dependency check failure for json-smart

---

java/core/src/main/java/sleeper/core/statestore/transactionlog/StateStoreFiles.java
java/statestore/src/main/java/sleeper/statestore/StateStoreArrowFileStore.java
java/statestore/src/main/java/sleeper/statestore/StateStoreFilesArrowFormat.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4191

Issue 4191 - Log file reference count

---

example/full/instance.properties
example/full/table.properties
java/core/src/main/java/sleeper/core/properties/instance/TableDefaultProperty.java
java/core/src/main/java/sleeper/core/properties/table/TableProperty.java
java/statestore/src/main/java/sleeper/statestore/StateStoreArrowFileStore.java
java/statestore/src/main/java/sleeper/statestore/StateStoreFilesArrowFormat.java
java/statestore/src/main/java/sleeper/statestore/StateStorePartitionsArrowFormat.java
java/statestore/src/main/java/sleeper/statestore/s3/S3FileReferenceStore.java
java/statestore/src/main/java/sleeper/statestore/s3/S3PartitionStore.java
java/statestore/src/main/java/sleeper/statestore/s3/S3StateStore.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotStore.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotSerDe.java
java/statestore/src/test/java/sleeper/statestore/StateStoreFilesArrowFormatTest.java
java/statestore/src/test/java/sleeper/statestore/StateStorePartitionsArrowFormatTest.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotSerDeIT.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/4192
- Updated StateStoreFilesArrowFormatTest

Issue 4192 - Use Arrow record batches in snapshots

---

java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogHead.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/log/TransactionLogRange.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/log/TransactionLogStore.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStore.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/InMemoryTransactionLogStoreTest.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStore.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/DynamoDBTransactionLogStoreIT.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogTransactionDeleterTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4245
- Updated existing tests to use new method signature

Issue 4245 - Read transactions from log by range

---

java/example-iterators/src/main/java/sleeper/example/iterator/AdditionIterator.java
java/example-iterators/src/test/java/sleeper/example/iterator/AdditionIteratorTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4254
- Existing tests extended, no new functionality added

Issue 4254 - Simplified AdditionIterator

---

java/core/src/main/java/sleeper/core/statestore/DelegatingStateStore.java
java/core/src/main/java/sleeper/core/statestore/FileReferenceStore.java
java/core/src/main/java/sleeper/core/statestore/PartitionStore.java
java/core/src/main/java/sleeper/core/statestore/StateStore.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/AddTransactionRequest.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogStateStore.java
java/core/src/test/java/sleeper/core/statestore/transactionlog/TransactionLogStateStoreLogSpecificTest.java
java/statestore-committer-core/src/main/java/sleeper/statestore/committer/StateStoreCommitter.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/TransactionLogStateStoreDynamoDBSpecificIT.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/TransactionLogSnapshotCreatorIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4270
- Build of application and existing test suite

Issue 4270 - Add Transaction To State Store Interface

---

.github/workflows/dependency-check.yaml

PR"
- Resolves https://github.com/gchq/sleeper/issues/4292
- Just updating workflow

Issue 4292 - Temporarily disable dependency check plugin

---

java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/CompactionJobCommitterOrSendToLambda.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskCommitTest.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskTestBase.java
java/core/src/main/java/sleeper/core/statestore/ReplaceFileReferencesRequest.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/transaction/impl/ReplaceFileReferencesTransaction.java
java/core/src/test/java/sleeper/core/statestore/testutils/InMemoryTransactionLogsPerTable.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4323
- Updated CompactionTaskCommitTest

Issue 4323 - Handle sync/asynchronous commit of compaction job tracker updates

---

java/cdk/src/main/java/sleeper/cdk/stack/core/CoreStacks.java
java/cdk/src/main/java/sleeper/cdk/stack/core/TransactionLogTransactionStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4355

Issue 4355 - Transaction log follower permissions

---

java/cdk/src/main/java/sleeper/cdk/stack/core/CoreStacks.java
java/cdk/src/main/java/sleeper/cdk/stack/core/StateStoreStacks.java
java/cdk/src/main/java/sleeper/cdk/stack/core/TransactionLogStateStoreStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4355

Issue 4355 - Grant access to follower to read all snapshots table

---

scripts/build/build.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/4331
- Build of application

Issue 4331 - Improve maven start up message

---

docs/development/release-process.md
docs/development/roadmap.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4234
- Just updating documentation

Issue 4234 - Update roadmap

---

.github/workflows/dependency-check.yaml
code-style/dependency-check-suppressions.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/4293
- See GitHub Actions checks

Issue 4293 - Re-enable dependency checks

---

CHANGELOG.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4385

Issue 4385 - Changelog for 0.29

---

rust/Cross.sccache.toml
rust/Cross.toml

PR"
- Resolves https://github.com/gchq/sleeper/issues/4419
- Build issue for C/C++ code

Issue 4419 - Change from GCC to Clang for C/C++ code

---

java/compaction/compaction-job-creation/pom.xml
java/query/query-runner/pom.xml
java/statestore-committer-core/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/3832
- Full build of application

Issue 3832 - Stop building unused fat jars

---

java/core/src/main/java/sleeper/core/properties/instance/CompactionProperty.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4440

Issue 4440 - Set missing compaction property flags to trigger CDK deployment

---

java/common/localstack-test/src/main/java/sleeper/localstack/test/LocalStackTestBase.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorIT.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4442

Issue 4442 - Garbage collector unit tests

---

NOTICES
java/cdk/pom.xml
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/4325
- EksBulkImportST passed in AWS

Issue 4325 - Upgrade Kubernetes to v1.32

---

java/clients/src/main/java/sleeper/clients/status/update/DeleteTable.java
java/clients/src/test/java/sleeper/clients/status/update/DeleteTableIT.java
java/statestore/src/main/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotMetadataStore.java
java/statestore/src/test/java/sleeper/statestore/transactionlog/snapshots/DynamoDBTransactionLogSnapshotMetadataStoreIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4317
- Updated DeleteTableIT, DynamoDBTransactionLogSnapshotMetadataStoreIT

Issue 4317 - Clear snapshot metadata on Sleeper table deletion

---

java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionJobResources.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4466
- Will test in AWS by manually creating full compaction multiple times quickly

Issue 4466 - Grant sending batches straight to DLQ from compaction dispatcher

---

example/full/instance.properties
java/core/src/main/java/sleeper/core/properties/instance/GarbageCollectionProperty.java
java/core/src/main/java/sleeper/core/table/TableFilePaths.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/FailedGarbageCollectionException.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/FileToDelete.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/FilesToDelete.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/FilesToDeleteInBucket.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollector.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollectorLambda.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/TableFilesDeleted.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/FileToDeleteTest.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/FilesToDeleteTest.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorTest.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/4401
- Added FilesToDeleteTest
- Updated GarbageCollectorS3IT

Issue 4401 - GC batch deletion with S3

---

example/full/instance.properties
java/core/src/main/java/sleeper/core/properties/instance/GarbageCollectionProperty.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/FilesToDeleteInBucket.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollector.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/FilesToDeleteTest.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/4485
- Updated FilesToDeleteTest, GarbageCollectorS3IT

Issue 4485 - Multiple requests to S3 per batch of files to delete

---

java/core/src/main/java/sleeper/core/util/ThreadSleep.java
java/core/src/test/java/sleeper/core/util/ThreadSleepTestHelper.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollector.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollectorLambda.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/S3DeleteFiles.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorS3IT.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorTest.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorTestBase.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorWiremockS3IT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4493
- New tests within GarbageCollectorWiremockS3IT

Issue 4493 - Handle rate limit in GC

---

.vscode/settings.json
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/BulkImportStarterRetryStrategy.java
java/bulk-import/bulk-import-starter/src/main/java/sleeper/bulkimport/starter/executor/PlatformExecutor.java
java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrServerlessPlatformExecutorWiremockIT.java
java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/PersistentEmrPlatformExecutorWiremockIT.java
java/bulk-import/bulk-import-starter/src/test/resources/example/persistent-emr/addjobflow-request.json
java/bulk-import/bulk-import-starter/src/test/resources/example/persistent-emr/listclusters-response.json
java/clients/src/test/java/sleeper/clients/testutil/ClientWiremockTestHelper.java
java/common/common-task/src/test/java/sleeper/task/common/EC2InstanceDetailsIT.java
java/common/common-task/src/test/java/sleeper/task/common/RunECSTasksIT.java
java/common/common-task/src/test/java/sleeper/task/common/WiremockAwsV2ClientHelper.java
java/common/localstack-test/src/main/java/sleeper/localstack/test/WiremockAwsV2ClientHelper.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4381
- Resolves https://github.com/gchq/sleeper/issues/4504
- Resolves https://github.com/gchq/sleeper/issues/4505
- PersistentEmrPlatformExecutorWiremockIT

Issue 4381 - Rate limiting for starting EMR bulk export

---

java/clients/src/main/java/sleeper/clients/util/BucketUtils.java

- [ x] My PR addresses the following issues and references them in the PR title. For example, "Issue 1234 - My Sleeper
PR"
- Resolves https://github.com/gchq/sleeper/issues/4492
- [x ] My PR adds the following tests __OR__ does not need testing for this extremely good reason:
- Execution of existing test suites
- [x ] In case of new functionality, my PR adds documentation that describes how to use it, or I have linked to a
- [x ] If I have added or removed any dependencies from the project, I have updated the [NOTICES](/NOTICES) file.

Issue 4492 - Raise batch size in BucketUtils.deleteObjectsInBucketWithPrefix

---

example/full/instance.properties
example/full/table.properties
java/bulk-export/bulk-export-core/src/main/java/sleeper/bulkexport/core/recordretrieval/BulkExportQuerySplitter.java
java/bulk-export/bulk-export-core/src/test/java/sleeper/bulkexport/core/recordretrieval/BulkExportQuerySplitterTest.java
java/core/src/main/java/sleeper/core/properties/instance/QueryProperty.java
java/core/src/main/java/sleeper/core/properties/table/TableProperty.java
java/query/query-core/src/main/java/sleeper/query/core/recordretrieval/QueryExecutor.java
java/query/query-core/src/test/java/sleeper/query/core/recordretrieval/QueryExecutorTest.java
scripts/templates/instanceproperties.template

PR"
- Resolves https://github.com/gchq/sleeper/issues/4518
- Execution of tests affected by change

Issue 4518: Change query processor cache timeout property

---

docs/development/roadmap.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4528

Issue 4528 - Link roadmap to new epic

---

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionCommitThroughputST.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4538
- CompactionCommitThroughputST passed in AWS

Issue 4538 - Raise timeout waiting for commits in CompactionCommitThroughputST

---

docs/usage-guide.md
java/clients/src/main/java/sleeper/clients/SleeperClient.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4474

Issue 4474 - Add SleeperClient to documentation

---

java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrPlatformExecutorWiremockIT.java
java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/PersistentEmrPlatformExecutorWiremockIT.java
java/bulk-import/bulk-import-starter/src/test/resources/example/emr/runjobflow-request.json

PR"
- Resolves https://github.com/gchq/sleeper/issues/4539
- Added EmrPlatformExecutorWiremockIT
- Updated PersistentEmrPlatformExecutorWiremockIT

Issue 4539 - Align WireMock bulk import executor tests

---

docs/development/release-process.md
docs/development/system-tests.md
scripts/test/nightly/README.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/3687

Issue 3687 - Update release process

---

docs/deployment-guide.md
docs/development/deployment-improvements.md
docs/development/roadmap.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4560

Issue 4560 - Document potential deployment improvements

---

docs/usage/ingest.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4536

Issue 4536 - Overview of ingest & job tracker

---

java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionTrackerStack.java
java/cdk/src/main/java/sleeper/cdk/stack/core/TableIndexStack.java
java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestBatcherStack.java
java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestTrackerStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4357
- Small change that will be covered by overnight tests.

Issue 4357 - Updated deprecated methods with replacement version

---

.github/workflows/chunk.yaml
.github/workflows/rust-audit.yaml
.github/workflows/rust-cache.yaml
.github/workflows/rust-lint.yaml
.github/workflows/rust-tests.yaml
rust/Cross.sccache.toml

PR"
- Resolves https://github.com/gchq/sleeper/issues/4609
- Will run in GitHub Actions automatically, see checks

Issue 4609 - Upgrade mozilla-actions/sccache-action

---

rust/rust_sketch/build.rs

PR"
- Resolves https://github.com/gchq/sleeper/issues/4616
- Update version of dependency

Issue 4616- Bump version of C++ Apache DataSketches library

---

java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/impl/IngestCoordinator.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/json/TasksSummaryJson.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsDrainSqsQueue.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/compaction/SystemTestCompaction.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4630
- Just small adjustments to tests

Issue 4630 - Intermittent nightly test failures

---

java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/AwsDrainSqsQueue.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4646
- Covered in nightly system tests

Issue 4646 - Set wait time draining queues in system tests to maximum

---

docs/deployment-guide.md
docs/usage-guide.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4641

Issue 4641 - Links to configuration property documentation

---

CHANGELOG.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4632
- Just changelog

Issue 4632 - Changelog for 0.30.0

---

docs/development/roadmap.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4633
- Just roadmap

Issue 4633 - Update roadmap for 0.30.0

---

scripts/cli/builder/Dockerfile
shell.nix

PR"
- Resolves https://github.com/gchq/sleeper/issues/4650
- Execution of existing build process

4650- Update to docker file to include clang

---

docs/development/release-process.md
python/setup.py

PR"
- Resolves https://github.com/gchq/sleeper/issues/4684
- Just version number & documentation

Issue 4684 - Fix Python snapshot version number

---

java/clients/src/main/java/sleeper/clients/api/SleeperClient.java
java/core/src/main/java/sleeper/core/properties/table/TablePropertiesProvider.java
java/core/src/main/java/sleeper/core/properties/table/TablePropertiesStore.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4663

4663 - Update JavaDoc for SleeperClient getTableProperties by tableName

---

.github/workflows/chunk.yaml
.github/workflows/rust-audit.yaml
.github/workflows/rust-cache.yaml
.github/workflows/rust-lint.yaml
.github/workflows/rust-tests.yaml
rust/Cross.sccache.toml

PR"
- Resolves https://github.com/gchq/sleeper/issues/4697
- See GitHub Actions checks

Issue 4697 - Upgrade sccache-action

---

rust/compaction/src/datafusion.rs
rust/compaction/tests/compaction_test.rs

PR"
- Resolves https://github.com/gchq/sleeper/issues/4695
- Test added in rust/compaction/tests/compaction_test.rs

Issue 4695 - Don't make assumptions about row key column positions.

---

java/clients/src/main/java/sleeper/clients/api/SleeperClient.java
java/clients/src/test/java/sleeper/clients/api/SleeperClientTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4664
- New tests in SleeperClientTest.java

Issue 4664 - New method for doesTableExist

---

docs/developer-guide.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4702

Issue 4702 - Expand Javadoc section of developer guide

---

CHANGELOG.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4727

Issue 4727 - Add version 0.30.1 to changelog

---

java/configurationV2/pom.xml
java/configurationV2/src/main/java/sleeper/configurationv2/properties/S3InstanceProperties.java
java/configurationV2/src/main/java/sleeper/configurationv2/properties/S3TableProperties.java
java/configurationV2/src/main/java/sleeper/configurationv2/table/index/DynamoDBTableIdFormat.java
java/configurationV2/src/main/java/sleeper/configurationv2/table/index/DynamoDBTableIndex.java
java/configurationV2/src/main/java/sleeper/configurationv2/table/index/DynamoDBTableIndexCreator.java
java/configurationV2/src/test/java/sleeper/configurationv2/properties/S3PropertiesReloaderIT.java
java/configurationV2/src/test/java/sleeper/configurationv2/properties/SaveLocalPropertiesS3IT.java
java/configurationV2/src/test/java/sleeper/configurationv2/properties/TablePropertiesITBase.java
java/configurationV2/src/test/java/sleeper/configurationv2/properties/TablePropertiesProviderIT.java
java/configurationV2/src/test/java/sleeper/configurationv2/table/index/DynamoDBTableIndexDynamoSpecificIT.java
java/configurationV2/src/test/java/sleeper/configurationv2/table/index/DynamoDBTableIndexIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/2938
- DynamoDBTableIndexIT
- DynamoDBTableIndexDynamoSpecificIT

2938 aws sdk v2 implementation of table index

---

java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestClusterStack.java
java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestProperty.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4748
- Deployed in AWS

Issue 4748 - Deploy system test queue

---

java/compaction/compaction-rust/src/main/java/sleeper/compaction/rust/RustBridge.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4774
- Remove un-uncessary path

Issue 4774 - Remove Rust search path

---

java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/executor/EmrPlatformExecutorWiremockIT.java
java/bulk-import/bulk-import-starter/src/test/resources/example/emr/runjobflow-request.json
java/configurationV2/src/main/java/sleeper/configurationv2/jars/S3UserJarsLoader.java
java/configurationV2/src/test/java/sleeper/configurationv2/jars/S3UserJarsLoaderIT.java
java/core/src/test/java/sleeper/core/properties/testutils/InstancePropertiesTestHelper.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3270
- S3UserJarsLoaderIT

Issue 3270 - Convert S3UserJarsLoader to SDK v2

---

docs/usage/export.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/3551

Missing bulk export documentation pull request comments 

---

docs/developer-guide.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4782

Issue 4782 - Document ordering of elements in a Java class

---

docs/developer-guide.md
docs/getting-started.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4784

Issue 4784 - Update dependency versions

---

docs/developer-guide.md
docs/development/conventions.md
docs/development/test-strategy.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4786

Issue 4786 - Split up developer guide

---

java/compaction/compaction-rust/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/4792
Paths removed

Issue 4792 - Remove library paths

---

java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/instance/DeployedSystemTestResources.java
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/SystemTestCluster.java
java/system-test/system-test-dsl/src/test/java/sleeper/systemtest/dsl/extension/SleeperSystemTestExtension.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/3947

Issue 3947 - Thread safety in DeployedSystemTestResources

---

rust/Cargo.lock
rust/Cross.sccache.toml
rust/Dockerfile.sccache.aarch64-unknown-linux-gnu
rust/cross-prebuild.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/4798
- Fixes a compilation failure.

Issue 4798 - Update cross to Clang-20

---

java/statestorev2/pom.xml
java/statestorev2/src/main/java/sleeper/statestorev2/transactionlog/snapshots/DynamoDBTransactionLogSnapshotCreator.java
java/statestorev2/src/main/java/sleeper/statestorev2/transactionlog/snapshots/DynamoDBTransactionLogSnapshotSaver.java
java/statestorev2/src/main/java/sleeper/statestorev2/transactionlog/snapshots/TransactionLogSnapshotDeleter.java
java/statestorev2/src/test/java/sleeper/statestorev2/transactionlog/TransactionLogStateStoreDynamoDBSpecificIT.java
java/statestorev2/src/test/java/sleeper/statestorev2/transactionlog/TransactionLogStateStoreOneTableTestBase.java
java/statestorev2/src/test/java/sleeper/statestorev2/transactionlog/snapshots/TransactionLogSnapshotTestBase.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4802

Issue 4802: Removal of hadoop from statestoreV2

---

code-style/dependency-check-suppressions.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/4814

Issue 4814 - Suppress dependency check failure

---

docs/development/conventions.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4797

Issue 4797 - Add access levels, final, this to coding conventions

---

java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestBatcherStack.java
java/ingest/ingest-batcher-submitter/pom.xml
java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitDeadLetterQueue.java
java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitter.java
java/ingest/ingest-batcher-submitter/src/main/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambda.java
java/ingest/ingest-batcher-submitter/src/test/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambdaIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4721
- IngestBatcherSubmitterLambdaIT updated.

4721 ingest batcher submitter discards submitted requests if theres a network failure

---

.github/config/chunks.yaml
.github/workflows/chunk-query.yaml
java/query/pom.xml
java/query/query-runnerv2/pom.xml
java/query/query-runnerv2/src/main/java/sleeper/query/runnerv2/output/NoResultsOutput.java
java/query/query-runnerv2/src/main/java/sleeper/query/runnerv2/output/S3ResultsOutput.java
java/query/query-runnerv2/src/main/java/sleeper/query/runnerv2/output/SQSResultsOutput.java
java/query/query-runnerv2/src/main/java/sleeper/query/runnerv2/output/WebSocketOutput.java
java/query/query-runnerv2/src/main/java/sleeper/query/runnerv2/output/WebSocketResultsOutput.java
java/query/query-runnerv2/src/main/java/sleeper/query/runnerv2/recordretrieval/LeafPartitionRecordRetrieverImpl.java
java/query/query-runnerv2/src/main/java/sleeper/query/runnerv2/recordretrieval/RetrieveTask.java
java/query/query-runnerv2/src/main/java/sleeper/query/runnerv2/tracker/DynamoDBQueryTracker.java
java/query/query-runnerv2/src/main/java/sleeper/query/runnerv2/tracker/DynamoDBQueryTrackerCreator.java
java/query/query-runnerv2/src/main/java/sleeper/query/runnerv2/tracker/DynamoDBQueryTrackerEntry.java
java/query/query-runnerv2/src/main/java/sleeper/query/runnerv2/tracker/QueryStatusReportListeners.java
java/query/query-runnerv2/src/main/java/sleeper/query/runnerv2/tracker/WebSocketQueryStatusReportDestination.java
java/query/query-runnerv2/src/test/java/sleeper/query/runnerv2/output/S3ResultsOutputIT.java
java/query/query-runnerv2/src/test/java/sleeper/query/runnerv2/output/WebSocketResultsOutputIT.java
java/query/query-runnerv2/src/test/java/sleeper/query/runnerv2/recordretrieval/QueryExecutorIT.java
java/query/query-runnerv2/src/test/java/sleeper/query/runnerv2/tracker/DynamoDBQueryTrackerIT.java
java/query/query-runnerv2/src/test/java/sleeper/query/runnerv2/tracker/TrackedQueryTestHelper.java
java/query/query-runnerv2/src/test/java/sleeper/query/runnerv2/tracker/WebSocketQueryStatusReportDestinationIT.java

PR"
- Will follow up with stacked PR

Issue 4828 - Copy query-runner module for v2 migration

---

java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestDataGenerationJob.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomData.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/ingest/SystemTestDataGenerationJobSender.java
java/system-test/system-test-drivers/src/test/java/sleeper/systemtest/drivers/ingest/SystemTestDataGenerationJobSenderIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4838
- SystemTestDataGenerationJobSenderIT

Issue 4838 - Fix SystemTestDataGenerationJobSender

---

.github/config/chunks.yaml
.github/workflows/chunk-common.yaml
code-style/checkstyle-idea/checkstyle-suppressions.xml
code-style/checkstyle-suppressions.xml
java/common/common-jobv2/pom.xml
java/common/common-jobv2/src/main/java/sleeper/common/jobv2/EC2ContainerMetadata.java
java/common/common-jobv2/src/main/java/sleeper/common/jobv2/action/Action.java
java/common/common-jobv2/src/main/java/sleeper/common/jobv2/action/ActionException.java
java/common/common-jobv2/src/main/java/sleeper/common/jobv2/action/ChangeMessageVisibilityTimeoutAction.java
java/common/common-jobv2/src/main/java/sleeper/common/jobv2/action/DeleteMessageAction.java
java/common/common-jobv2/src/main/java/sleeper/common/jobv2/action/MessageReference.java
java/common/common-jobv2/src/main/java/sleeper/common/jobv2/action/thread/PeriodicActionRunnable.java
java/common/common-jobv2/src/test/java/sleeper/common/jobv2/action/ChangeMessageVisibilityTimeoutActionIT.java
java/common/common-jobv2/src/test/java/sleeper/common/jobv2/action/DeleteMessageActionIT.java
java/common/common-jobv2/src/test/java/sleeper/common/jobv2/action/thread/PeriodicActionRunnableIT.java
java/common/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/4821
- Tests copied from v1 package

4821: Copy common-job into common-jobv2 package

---

java/common/common-jobv2/pom.xml
java/common/common-jobv2/src/main/java/sleeper/common/jobv2/action/ChangeMessageVisibilityTimeoutAction.java
java/common/common-jobv2/src/main/java/sleeper/common/jobv2/action/DeleteMessageAction.java
java/common/common-jobv2/src/main/java/sleeper/common/jobv2/action/MessageReference.java
java/common/common-jobv2/src/test/java/sleeper/common/jobv2/action/ChangeMessageVisibilityTimeoutActionIT.java
java/common/common-jobv2/src/test/java/sleeper/common/jobv2/action/DeleteMessageActionIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4821
- Tests copied from V1 package

4821: Upgrade common-jobv2 to use aws v2 code

---

java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestClusterStack.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4859
- Just CDK changes

Issue 4859 - Fix setting system test properties for queues

---

java/distribution/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/4861

Issue 4861 - Add missing dependencies to distribution module

---

README.md
docs/deployment-guide.md
docs/deployment/instance-configuration.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/4759

Issue 4759 - Simplify readme

---

.github/config/chunks.yaml
.github/workflows/chunk-ingest.yaml
java/ingest/ingest-batcher-submitterv2/pom.xml
java/ingest/ingest-batcher-submitterv2/src/main/java/sleeper/ingest/batcher/submitterv2/IngestBatcherSubmitDeadLetterQueue.java
java/ingest/ingest-batcher-submitterv2/src/main/java/sleeper/ingest/batcher/submitterv2/IngestBatcherSubmitter.java
java/ingest/ingest-batcher-submitterv2/src/main/java/sleeper/ingest/batcher/submitterv2/IngestBatcherSubmitterLambda.java
java/ingest/ingest-batcher-submitterv2/src/test/java/sleeper/ingest/batcher/submitterv2/IngestBatcherSubmitterLambdaIT.java
java/ingest/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/4870
- IngestBatcherSubmitterLambdaIT updated from v1.

4870-migrate-ingest-batcher-job-submitter-module-to-aws-sdk-v2

---

.github/workflows/chunk-ingest.yaml
java/ingest/ingest-batcher-job-creator/pom.xml
java/ingest/ingest-batcher-job-creator/src/main/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambda.java
java/ingest/ingest-batcher-job-creator/src/main/java/sleeper/ingest/batcher/job/creator/SQSIngestBatcherQueueClient.java
java/ingest/ingest-batcher-job-creator/src/test/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambdaIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4869
- Execution of existing test suites

Issue 4869: Update ingest batcher job to use sdk v2

---

java/clients/pom.xml
java/clients/src/main/java/sleeper/clients/admin/AdminClient.java
java/clients/src/main/java/sleeper/clients/admin/AdminClientTrackerFactory.java
java/clients/src/main/java/sleeper/clients/admin/properties/AdminClientPropertiesStore.java
java/clients/src/test/java/sleeper/clients/admin/AdminClientIT.java
java/clients/src/test/java/sleeper/clients/admin/TableSelectHelperIT.java
java/clients/src/test/java/sleeper/clients/admin/properties/AdminClientPropertiesStoreIT.java
java/clients/src/test/java/sleeper/clients/admin/properties/UpdatePropertiesWithTextEditorIT.java
java/clients/src/test/java/sleeper/clients/admin/testutils/AdminClientITBase.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4892

Issue 4892 - Migrate AdminClient to AWS SDK v2

---

NOTICES
java/bulk-export/bulk-export-planner/pom.xml
java/bulk-export/bulk-export-task-creator/pom.xml
java/bulk-import/bulk-import-starter/pom.xml
java/cdk-custom-resources/pom.xml
java/compaction/compaction-job-creation-lambda/pom.xml
java/compaction/compaction-task-creation/pom.xml
java/garbage-collector/pom.xml
java/ingest/ingest-batcher-job-creator/pom.xml
java/ingest/ingest-batcher-submitter/pom.xml
java/ingest/ingest-batcher-submitterv2/pom.xml
java/ingest/ingest-starter/pom.xml
java/metrics/pom.xml
java/partitions/splitter-lambda/pom.xml
java/pom.xml
java/query/query-lambda/pom.xml
java/statestore-lambda/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/4917

Issue 4917 - Add dependency convergence rule to maven-enforcer-plugin

---

.github/workflows/chunk-common.yaml
java/common/localstack-test/src/main/java/sleeper/localstack/test/LocalStackTestBase.java
java/garbage-collector/src/main/java/sleeper/garbagecollector/GarbageCollectorLambda.java
java/statestore-lambda/pom.xml
java/statestore-lambda/src/main/java/sleeper/statestore/lambda/committer/CompactionCommitBatcherLambda.java
java/statestore-lambda/src/main/java/sleeper/statestore/lambda/committer/StateStoreCommitterLambda.java
java/statestore-lambda/src/main/java/sleeper/statestore/lambda/snapshot/TransactionLogSnapshotCreationLambda.java
java/statestore-lambda/src/main/java/sleeper/statestore/lambda/snapshot/TransactionLogSnapshotCreationTriggerLambda.java
java/statestore-lambda/src/main/java/sleeper/statestore/lambda/snapshot/TransactionLogSnapshotDeletionLambda.java
java/statestore-lambda/src/main/java/sleeper/statestore/lambda/snapshot/TransactionLogSnapshotDeletionTriggerLambda.java
java/statestore-lambda/src/main/java/sleeper/statestore/lambda/transaction/DynamoDBStreamTransactionLogEntryMapper.java
java/statestore-lambda/src/main/java/sleeper/statestore/lambda/transaction/TransactionLogFollowerLambda.java
java/statestore-lambda/src/main/java/sleeper/statestore/lambda/transaction/TransactionLogTransactionDeletionLambda.java
java/statestore-lambda/src/main/java/sleeper/statestore/lambda/transaction/TransactionLogTransactionDeletionTriggerLambda.java
java/statestore-lambda/src/test/java/sleeper/statestore/lambda/committer/CompactionCommitBatcherLambdaIT.java
java/statestore-lambda/src/test/java/sleeper/statestore/lambda/committer/StateStoreCommitterLambdaTest.java
java/statestore-lambda/src/test/java/sleeper/statestore/lambda/transaction/DynamoDBStreamTransactionLogEntryMapperTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4852

Issue 4852: Update state-store-lambda to AWS sdk v2

---

java/clients/src/test/java/sleeper/clients/deploy/localstack/DockerInstanceIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4820
- Only updated DockerInstanceIT

Issue 4820 - Finish migration of DockerInstanceIT

---

.github/workflows/chunk-rust.yaml
java/compaction/compaction-rust/pom.xml
java/compaction/compaction-rust/src/test/java/sleeper/compaction/rust/RustCompactionRunnerIT.java
java/compaction/compaction-rust/src/test/java/sleeper/compaction/rust/RustCompactionRunnerLocalStackIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4997

Issue 4997 - Upgrade compaction-rust to use sketchesv2

---

java/system-test/system-test-data-generation/pom.xml
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/ECSSystemTestTask.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/GenerateRandomDataFiles.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomData.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataToDocker.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataViaBatcher.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomDataViaQueue.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/InstanceIngestSession.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/MultipleQueries.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/RandomRecordSupplier.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomData.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataDirect.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataFiles.java
java/system-test/system-test-data-generation/src/test/java/sleeper/systemtest/datageneration/SystemTestTaskIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/4854
- Existing tests updated

Issue 4854 - migrate system test data generation to aws sdk v2

---

java/pom.xml

PR"
- Resolves https://github.com/gchq/sleeper/issues/5029

Issue 5029 - Ban duplicate dependencies in poms

---

java/athena/src/test/java/sleeper/athena/composite/AthenaHandlerTest.java
java/bulk-import/bulk-import-starter/src/test/java/sleeper/bulkimport/starter/BulkImportStarterLambdaHandlerTest.java
java/bulk-import/bulk-import-starterv2/src/test/java/sleeper/bulkimport/starterv2/BulkImportStarterLambdaHandlerTest.java
java/cdk-custom-resources/src/test/java/sleeper/cdk/custom/CdkCustomLambdaHandlerTest.java
java/compaction/compaction-job-creation-lambda/src/test/java/sleeper/compaction/job/creation/lambda/CompactionJobCreationLambdaHandlerTest.java
java/compaction/compaction-task-creation/src/test/java/sleeper/compaction/task/creation/CompactionTaskCreationLambdaHandlerTest.java
java/core/src/main/java/sleeper/core/deploy/LambdaHandler.java
java/garbage-collector/src/test/java/sleeper/garbagecollector/GarbageCollectorLambdaHandlerTest.java
java/ingest/ingest-batcher-job-creator/src/test/java/sleeper/ingest/batcher/job/creator/IngestBatcherJobCreatorLambdaHandlerTest.java
java/ingest/ingest-batcher-submitter/src/test/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambdaHandlerTest.java
java/ingest/ingest-taskrunner/src/test/java/sleeper/ingest/taskrunner/RunIngestTasksLambdaHandlerTest.java
java/ingest/ingest-taskrunner/src/test/java/sleeper/ingest/taskrunner/RunIngestTasksLambdaTest.java
java/metrics/src/test/java/sleeper/metrics/TableMetricsLambdaHandlerTest.java
java/partitions/splitter-lambda/src/test/java/sleeper/splitter/lambda/PartitionSplitterLambdaHandlerTest.java
java/query/query-lambda/src/test/java/sleeper/query/lambda/QueryLambdaHandlerTest.java
java/query/query-lambdav2/src/test/java/sleeper/query/lambda/QueryLambdaHandlerTest.java
java/statestore-lambda/src/test/java/sleeper/statestore/lambda/StateStoreLambdaHandlerTest.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/5031
- Added XLambdaHandlerTest classes to cover all lambda declarations

Issue 5031 - Fix ingest starter lambda

---

java/clients/src/main/java/sleeper/clients/query/QueryWebSocketClient.java
java/clients/src/main/java/sleeper/clients/query/QueryWebSocketCommandLineClient.java
java/clients/src/test/java/sleeper/clients/query/FakeWebSocketClient.java
java/clients/src/test/java/sleeper/clients/query/QueryWebSocketClientTest.java
java/clients/src/test/java/sleeper/clients/query/QueryWebSocketCommandLineClientTest.java
java/system-test/system-test-drivers/src/main/java/sleeper/systemtest/drivers/util/SystemTestClients.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/5068
- Updated QueryWebSocketClientTest
- [x ] In case of new functionality, my PR adds documentation that describes how to use it, or I have linked to a

Issue 5068 - Set timeout for QueryWebSocketClient

---

java/ingest/ingest-batcher-submitter/pom.xml
java/ingest/ingest-batcher-submitter/src/test/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambdaIT.java
java/ingest/ingest-batcher-submitter/src/test/java/sleeper/ingest/batcher/submitter/IngestBatcherSubmitterLambdaWireMockIT.java

…nt left for guidance on continuing
PR"
- Resolves https://github.com/gchq/sleeper/issues/XXX
- MyUnitTest

Issue: 4806: Test unexpected network failure looking for files to submit to ingest batcher

---

java/query/query-lambda/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
java/query/query-runner/src/main/java/sleeper/query/runner/tracker/WebSocketQueryStatusReportDestination.java
java/query/query-runner/src/test/java/sleeper/query/runner/tracker/WebSocketQueryStatusReportDestinationIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/5080
- Updated WebSocketQueryStatusReportDestinationIT

Issue 5080 - Fix web socket query results

---

python/setup.py

PR"
- Resolves https://github.com/gchq/sleeper/issues/5131

Issue 5131 - Fix Python build configuration

---

docs/usage/python-api.md
python/src/sleeper/client.py
python/src/sleeper/ingest.py
python/src/sleeper/properties/cdk_defined_properties.py
python/tests/sleeper/localstack.py
python/tests/sleeper/properties/instance_properties_helper.py
python/tests/sleeper/test_bulk_export.py
python/tests/sleeper/test_ingest.py

PR"
- Resolves https://github.com/gchq/sleeper/issues/5134
- test_ingest.py

Issue 5134 - Fix ingest via Python

---

java/compaction/compaction-rust/src/test/java/sleeper/compaction/rust/RustCompactionRunnerIT.java

PR"
-Resolves https://github.com/gchq/sleeper/issues/5144
- New test in RustCompactionRunnerIT

Issue 5144 -Integration test for DataFusion aggregation

---

NOTICES
python/setup.py
python/src/sleeper/properties/instance_properties.py
python/tests/sleeper/properties/test_instance_properties.py

PR"
- Resolves https://github.com/gchq/sleeper/issues/5175
- Updated test_instance_properties.py

Issue 5175 - Use jproperties in Python API

---

python/pyproject.toml
python/tests/sleeper/properties/test_config_bucket_localstack.py
python/tests/sleeper/properties/test_instance_properties.py
python/tests/sleeper/test_bulk_export.py
python/tests/sleeper/test_ingest.py
python/tests/sleeper/test_ingest_batcher.py

PR"
- Resolves https://github.com/gchq/sleeper/issues/5178
- Converted existing tests

Issue 5178 - Use test names starting with "should" in Python

---

rust/compaction/src/datafusion.rs
rust/compaction/src/datafusion/sketch_udf.rs

PR"
- Resolves https://github.com/gchq/sleeper/issues/5186

Issue 5186 - Add extra sort stage to workaround DF breaking sort order

---

java/bulk-export/bulk-export-task-execution/src/test/java/sleeper/bulkexport/taskexecution/ECSBulkExportTaskRunnerLocalStackIT.java

This is stacked on the following PR, with refactoring and comments added for a code review:
- https://github.com/gchq/sleeper/pull/5145

Issue 4757 - Review ECSBulkExportTaskRunnerLocalStackIT

---

.github/workflows/chunk.yaml
.github/workflows/rust-audit.yaml
.github/workflows/rust-cache.yaml
.github/workflows/rust-lint.yaml
.github/workflows/rust-tests.yaml
rust/Cargo.toml
rust/compaction/src/datafusion.rs

PR"
- Resolves https://github.com/gchq/sleeper/issues/4887
- 

Issue 4887: Update rust to latest stable version

---

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/CompactionDataFusionPerformanceST.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/5254
- Updated CompactionDataFusionPerformanceST

Issue 5254 - Update DataFusion compaction performance assertion

---

NOTICES
code-style/dependency-check-suppressions.xml
java/core/pom.xml
java/core/src/test/java/sleeper/core/statestore/transactionlog/transaction/TransactionSerDeTest.java
java/pom.xml
java/system-test/system-test-dsl/src/main/java/sleeper/systemtest/dsl/sourcedata/GenerateNumberedValue.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/5272

Issue 5272 - Resolve dependency check failures

---

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/IngestPerformanceST.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/5283
- Just performance assertion

Issue 5283 - Adjust ingest performance assertion

---

java/query/query-lambda/src/test/java/sleeper/query/lambda/SqsQueryProcessorLambdaIT.java
java/query/query-runner/src/main/java/sleeper/query/runner/output/WebSocketResultsOutput.java
java/query/query-runner/src/main/java/sleeper/query/runner/tracker/WebSocketQueryStatusReportDestination.java
java/query/query-runner/src/main/java/sleeper/query/runner/websocket/QueryWebSocketMessageSerDe.java
java/query/query-runner/src/main/java/sleeper/query/runner/websocket/QueryWebSocketRowsException.java
java/query/query-runner/src/test/java/sleeper/query/runner/output/WebSocketResultsOutputIT.java
java/query/query-runner/src/test/java/sleeper/query/runner/tracker/WebSocketQueryStatusReportDestinationIT.java

PR"
- Resolves https://github.com/gchq/sleeper/issues/5287

Issue 5287 - Use web socket message serialiser in query runner

---

scripts/utility/runCompactionTasks.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/5263
- No new tests added but script tested locally.

Issue 5263 - Wrong package name in runCompactionTasks.sh

---

NOTICES
rust/Cargo.lock
rust/Cargo.toml
rust/rust_sketch/Cargo.toml
rust/sccache-source.sh

PR"
- Resolves https://github.com/gchq/sleeper/issues/5328
- MyUnitTest

Issue 5328 - Remove explicit dependency to Rust openssl

---

.github/pull_request_template.md

PR"
- Resolves https://github.com/gchq/sleeper/issues/5374
- Just PR template

Issue 5374 - Fix links in PR template

---

rust/sleeper_df/src/datafusion.rs

PR"
- Resolves https://github.com/gchq/sleeper/issues/5248

Issue 5248 - Implement SortExec check

---

java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/ParallelCompactionsST.java

- Resolves https://github.com/gchq/sleeper/issues/5373
- Just editing test parameters
- Will run in AWS

Issue 5373 - Increase number of compactions in ParallelCompactionsST

---

java/bulk-export/bulk-export-task-execution/src/main/java/sleeper/bulkexport/taskexecution/ECSBulkExportTaskRunner.java
java/bulk-export/bulk-export-task-execution/src/test/java/sleeper/bulkexport/taskexecution/ECSBulkExportTaskRunnerLocalStackIT.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/core/job/CompactionRunner.java
java/compaction/compaction-core/src/main/java/sleeper/compaction/core/task/CompactionTask.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskTestBase.java
java/compaction/compaction-datafusion/src/main/java/sleeper/compaction/datafusion/DataFusionCompactionRunner.java
java/compaction/compaction-datafusion/src/test/java/sleeper/compaction/datafusion/DataFusionCompactionRunnerIT.java
java/compaction/compaction-datafusion/src/test/java/sleeper/compaction/datafusion/DataFusionCompactionRunnerLocalStackIT.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/JavaCompactionRunner.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactionRunnerTestBase.java
java/parquet/src/main/java/sleeper/parquet/utils/RangeQueryUtils.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/investigate/InvestigateCompactionChangingNumberOfRows.java
java/system-test/system-test-suite/src/test/java/sleeper/systemtest/suite/investigate/InvestigateDataFusionCompactionOOM.java

- Resolves https://github.com/gchq/sleeper/issues/5229
- MyUnitTest

5229 stop passing full partition to compaction runner

---

rust/build-in-docker.sh

- Resolves https://github.com/gchq/sleeper/issues/5489
- No new functionality

Issue 5489 - Add package target to Cargo command

---

java/core/src/test/java/sleeper/core/partition/PartitionTreeNearestCommonAncestorTest.java

- Resolves https://github.com/gchq/sleeper/issues/5491
- Updated PartitionTreeNearestCommonAncestorTest

Issue 5491 Tidy PartitionTreeNearestCommonAncestorTest

---

java/cdk/src/main/java/sleeper/cdk/stack/AthenaStack.java
java/cdk/src/main/java/sleeper/cdk/stack/GarbageCollectorStack.java
java/cdk/src/main/java/sleeper/cdk/stack/PartitionSplittingStack.java
java/cdk/src/main/java/sleeper/cdk/stack/TableMetricsStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkexport/BulkExportStack.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkexport/BulkExportTaskResources.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/CommonEmrBulkImportHelper.java
java/cdk/src/main/java/sleeper/cdk/stack/bulkimport/EksBulkImportStack.java
java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionJobResources.java
java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionOnEc2Resources.java
java/cdk/src/main/java/sleeper/cdk/stack/compaction/CompactionTaskResources.java
java/cdk/src/main/java/sleeper/cdk/stack/core/PropertiesStack.java
java/cdk/src/main/java/sleeper/cdk/stack/core/StateStoreCommitterStack.java
java/cdk/src/main/java/sleeper/cdk/stack/core/TransactionLogSnapshotStack.java
java/cdk/src/main/java/sleeper/cdk/stack/core/TransactionLogTransactionStack.java
java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestBatcherStack.java
java/cdk/src/main/java/sleeper/cdk/stack/ingest/IngestStack.java
java/cdk/src/main/java/sleeper/cdk/stack/query/KeepLambdaWarmStack.java
java/cdk/src/main/java/sleeper/cdk/stack/query/QueryStack.java
java/cdk/src/main/java/sleeper/cdk/stack/query/WebSocketQueryStack.java
java/cdk/src/main/java/sleeper/cdk/util/AutoDeleteS3Objects.java
java/cdk/src/main/java/sleeper/cdk/util/Utils.java
java/core/src/main/java/sleeper/core/util/EnvironmentUtils.java
java/system-test/system-test-cdk/src/main/java/sleeper/systemtest/cdk/SystemTestClusterStack.java

- Resolves https://github.com/gchq/sleeper/issues/5494
- Just moving code

Issue 5494 - Extract EnvironmentUtils

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/question.md

- Resolves https://github.com/gchq/sleeper/issues/5465
- Just issue templates

Issue 5465 - Update issue templates

---

java/compaction/compaction-datafusion/src/main/java/sleeper/compaction/datafusion/DataFusionCompactionRunner.java
java/compaction/compaction-datafusion/src/test/java/sleeper/compaction/datafusion/DataFusionCompactionRunnerIT.java
java/core/src/test/java/sleeper/core/schema/SchemaTestHelper.java

- Resolves https://github.com/gchq/sleeper/issues/5523
- In DataFusionCompactionRunnerIT

Issue 5523 - FFI layer is not transferring region data to Rust correctly

---

java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestDataGenerationJob.java
java/system-test/system-test-configuration/src/main/java/sleeper/systemtest/configuration/SystemTestDataGenerationJobStore.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/IngestRandomData.java
java/system-test/system-test-data-generation/src/main/java/sleeper/systemtest/datageneration/WriteRandomDataFiles.java
java/system-test/system-test-data-generation/src/test/java/sleeper/systemtest/datageneration/ECSSystemTestTaskIT.java

- Resolves https://github.com/gchq/sleeper/issues/5540
- Updated ECSSystemTestTaskIT

Issue 5540 - Remove SystemTestDataGenerationJob.jobId

---

java/compaction/compaction-core/src/main/java/sleeper/compaction/core/task/CompactionTask.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskTestBase.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/CompactionTaskTestHelper.java
java/compaction/compaction-core/src/test/java/sleeper/compaction/core/task/FakeMessageHandle.java
java/compaction/compaction-datafusion/pom.xml
java/compaction/compaction-datafusion/src/test/java/sleeper/compaction/datafusion/DataFusionCompactionRunnerIT.java
java/compaction/compaction-datafusion/src/test/java/sleeper/compaction/datafusion/DataFusionCompactionRunnerLocalStackIT.java
java/compaction/compaction-job-execution/pom.xml
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/ECSCompactionTaskRunnerLocalStackIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerEmptyOutputIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerIteratorIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/JavaCompactionRunnerLocalStackIT.java
java/compaction/compaction-job-execution/src/test/java/sleeper/compaction/job/execution/testutils/CompactionRunnerTestBase.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogFileReferenceStore.java
java/core/src/main/java/sleeper/core/statestore/transactionlog/TransactionLogPartitionStore.java
java/core/src/main/java/sleeper/core/tracker/compaction/job/query/CompactionJobRun.java
java/core/src/main/java/sleeper/core/util/ThreadSleep.java
java/core/src/test/java/sleeper/core/tracker/compaction/job/CompactionJobTrackerTestHelper.java

- Resolves https://github.com/gchq/sleeper/issues/5546

Issue 5546 - Refactor compaction runner tests

---

.github/workflows/dependency-check.yaml

- Resolves https://github.com/gchq/sleeper/issues/5548
- Covered by existing GitHub Actions workflows

Issue 5548 - Re-enable dependency checks

---

java/athena/src/main/java/sleeper/athena/record/IteratorApplyingRecordHandler.java
java/athena/src/test/java/sleeper/athena/record/IteratorApplyingRecordHandlerIT.java
java/compaction/compaction-job-execution/src/main/java/sleeper/compaction/job/execution/JavaCompactionRunner.java
java/configuration/src/test/java/sleeper/configuration/jars/S3UserJarsLoaderIT.java
java/core/src/main/java/sleeper/core/iterator/AgeOffFilter.java
java/core/src/main/java/sleeper/core/iterator/AgeOffIterator.java
java/core/src/main/java/sleeper/core/iterator/Aggregation.java
java/core/src/main/java/sleeper/core/iterator/AggregationFilteringIterator.java
java/core/src/main/java/sleeper/core/iterator/ConfigStringAggregationFilteringIterator.java
java/core/src/main/java/sleeper/core/iterator/IteratorConfig.java
java/core/src/main/java/sleeper/core/iterator/IteratorFactory.java
java/core/src/main/java/sleeper/core/iterator/SortedRowIterator.java
java/core/src/main/java/sleeper/core/iterator/SortedRowIterators.java
java/core/src/test/java/sleeper/core/iterator/AgeOffIteratorTest.java
java/core/src/test/java/sleeper/core/iterator/AggregationFilteringIteratorTest.java
java/core/src/test/java/sleeper/core/iterator/ConfigStringAggregationFilteringIteratorTest.java
java/core/src/test/java/sleeper/core/iterator/IteratorFactoryTest.java
java/core/src/test/java/sleeper/core/iterator/testutil/LimitingConfigStringIterator.java
java/core/src/test/java/sleeper/core/iterator/testutil/SortedRowIteratorTestHelper.java
java/example-iterators/src/main/java/sleeper/example/iterator/AdditionIterator.java
java/example-iterators/src/main/java/sleeper/example/iterator/FixedAgeOffIterator.java
java/example-iterators/src/main/java/sleeper/example/iterator/SecurityFilteringIterator.java
java/example-iterators/src/test/java/sleeper/example/iterator/AdditionIteratorTest.java
java/example-iterators/src/test/java/sleeper/example/iterator/FixedAgeOffIteratorTest.java
java/example-iterators/src/test/java/sleeper/example/iterator/SecurityFilteringIteratorTest.java
java/ingest/ingest-runner/src/main/java/sleeper/ingest/runner/impl/RowIteratorWithSleeperIteratorApplied.java
java/query/query-core/src/main/java/sleeper/query/core/rowretrieval/LeafPartitionQueryExecutor.java

- Resolves https://github.com/gchq/sleeper/issues/5561
- Updated IteratorFactoryTest, AggregationFilteringIteratorTest

Issue 5561 - Combine new filter/aggregation configuration with custom iterators

---

docs/usage/tables.md

- Resolves https://github.com/gchq/sleeper/issues/5784

Issue 5784 - Fix use of schema template file in documentation
